// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.28/00       [334848]
Creator        : han
Date           : Tue Dec  7 21:45:05 2021
Host           : Linux sukla01 3.10.0-327.36.3.el7.x86_64 #1 SMP Thu Oct 20 04:56:07 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk02/calib3/usr/han/mc/random
Training events: 5067409
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,172]
N200                          N200                          N200                          N200                                                            'F'    [7,955]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [1.97109591961,105256.398438]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.332784891129,0.999793052673]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.322455346584,0.996899008751]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [0.724473893642,89.9999923706]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-326.031768799,361.014984131]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [1.52587890625e-05,45.8233795166]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.685668647289,94.3646697998]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.00536481430754,87.3727264404]
DWall                         DWall                         DWall                         DWall                                                           'F'    [200.000976562,1676.24499512]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [201.668197632,4647.00341797]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 9.95637142782483;
   fWeightMatrix0to1[1][0] = 49.884262757461;
   fWeightMatrix0to1[2][0] = 4.22732486312409;
   fWeightMatrix0to1[3][0] = 15.0875395699243;
   fWeightMatrix0to1[4][0] = -13.6244902865956;
   fWeightMatrix0to1[5][0] = -11.7019322085564;
   fWeightMatrix0to1[6][0] = -14.6016586228676;
   fWeightMatrix0to1[7][0] = 37.7359289861848;
   fWeightMatrix0to1[8][0] = -7.37391862617246;
   fWeightMatrix0to1[9][0] = -21.9992451973528;
   fWeightMatrix0to1[10][0] = -24.3437847626979;
   fWeightMatrix0to1[11][0] = 8.47417786045201;
   fWeightMatrix0to1[12][0] = -11.9405907997092;
   fWeightMatrix0to1[0][1] = -12.0067375679393;
   fWeightMatrix0to1[1][1] = 7.10203010119049;
   fWeightMatrix0to1[2][1] = -2.65398784053667;
   fWeightMatrix0to1[3][1] = 1.71697900717539;
   fWeightMatrix0to1[4][1] = 28.2292472505173;
   fWeightMatrix0to1[5][1] = 19.2312224050786;
   fWeightMatrix0to1[6][1] = 18.9470688921297;
   fWeightMatrix0to1[7][1] = -14.5401620409803;
   fWeightMatrix0to1[8][1] = 12.4544503405886;
   fWeightMatrix0to1[9][1] = 19.5577173790738;
   fWeightMatrix0to1[10][1] = 9.30167571071462;
   fWeightMatrix0to1[11][1] = -6.83495053429291;
   fWeightMatrix0to1[12][1] = 23.1597803708861;
   fWeightMatrix0to1[0][2] = 3.07210490944633;
   fWeightMatrix0to1[1][2] = -27.0322704523651;
   fWeightMatrix0to1[2][2] = -2.59658925027063;
   fWeightMatrix0to1[3][2] = -7.52494169317497;
   fWeightMatrix0to1[4][2] = -6.78129773612895;
   fWeightMatrix0to1[5][2] = -0.513053908450565;
   fWeightMatrix0to1[6][2] = -1.70042216915172;
   fWeightMatrix0to1[7][2] = -8.33827850568563;
   fWeightMatrix0to1[8][2] = -1.08252287362318;
   fWeightMatrix0to1[9][2] = -1.33936543962834;
   fWeightMatrix0to1[10][2] = 6.25222550152367;
   fWeightMatrix0to1[11][2] = 6.45004148474067;
   fWeightMatrix0to1[12][2] = -7.11422257199667;
   fWeightMatrix0to1[0][3] = 1.55715101398802;
   fWeightMatrix0to1[1][3] = 1.54494275273631;
   fWeightMatrix0to1[2][3] = 3.92848576329996;
   fWeightMatrix0to1[3][3] = 0.101546829291039;
   fWeightMatrix0to1[4][3] = 0.352559309698251;
   fWeightMatrix0to1[5][3] = 2.06252248247618;
   fWeightMatrix0to1[6][3] = 1.40822215600207;
   fWeightMatrix0to1[7][3] = 2.21171878271964;
   fWeightMatrix0to1[8][3] = 4.65371939800784;
   fWeightMatrix0to1[9][3] = 4.2505721098979;
   fWeightMatrix0to1[10][3] = 0.54974660744752;
   fWeightMatrix0to1[11][3] = 1.59867397105615;
   fWeightMatrix0to1[12][3] = -1.23256115640784;
   fWeightMatrix0to1[0][4] = 0.803695574110722;
   fWeightMatrix0to1[1][4] = 0.625528497253224;
   fWeightMatrix0to1[2][4] = -0.11711570323106;
   fWeightMatrix0to1[3][4] = -0.411197967762729;
   fWeightMatrix0to1[4][4] = 1.61803805886586;
   fWeightMatrix0to1[5][4] = -1.78746774341721;
   fWeightMatrix0to1[6][4] = -0.392919787951942;
   fWeightMatrix0to1[7][4] = -2.45585222421313;
   fWeightMatrix0to1[8][4] = -1.67378051211648;
   fWeightMatrix0to1[9][4] = -0.288125190050056;
   fWeightMatrix0to1[10][4] = 0.333233813025752;
   fWeightMatrix0to1[11][4] = 0.444003637861076;
   fWeightMatrix0to1[12][4] = 3.43905289516639;
   fWeightMatrix0to1[0][5] = -5.84797891323311;
   fWeightMatrix0to1[1][5] = -0.844063176644987;
   fWeightMatrix0to1[2][5] = -0.0140566962083533;
   fWeightMatrix0to1[3][5] = -0.613045709667526;
   fWeightMatrix0to1[4][5] = -0.838332474732482;
   fWeightMatrix0to1[5][5] = 4.27499386606456;
   fWeightMatrix0to1[6][5] = 1.81521042468313;
   fWeightMatrix0to1[7][5] = 0.0981071025883338;
   fWeightMatrix0to1[8][5] = 1.93408633627687;
   fWeightMatrix0to1[9][5] = 2.56021468056481;
   fWeightMatrix0to1[10][5] = -1.85818541163308;
   fWeightMatrix0to1[11][5] = 0.34744073038866;
   fWeightMatrix0to1[12][5] = -11.2858977330805;
   fWeightMatrix0to1[0][6] = 2.38251695432036;
   fWeightMatrix0to1[1][6] = -1.44935379883337;
   fWeightMatrix0to1[2][6] = -0.334281599133447;
   fWeightMatrix0to1[3][6] = 3.64851276471791;
   fWeightMatrix0to1[4][6] = 1.64904740965285;
   fWeightMatrix0to1[5][6] = -2.15299403031948;
   fWeightMatrix0to1[6][6] = 0.143516368434186;
   fWeightMatrix0to1[7][6] = 3.40149923539485;
   fWeightMatrix0to1[8][6] = 1.4637690440655;
   fWeightMatrix0to1[9][6] = -1.33484891101256;
   fWeightMatrix0to1[10][6] = -0.249174322957684;
   fWeightMatrix0to1[11][6] = -0.364577529811936;
   fWeightMatrix0to1[12][6] = -11.6698914758446;
   fWeightMatrix0to1[0][7] = -0.0285006151962909;
   fWeightMatrix0to1[1][7] = 1.91638484371809;
   fWeightMatrix0to1[2][7] = -1.85104206951887;
   fWeightMatrix0to1[3][7] = 1.03295743114865;
   fWeightMatrix0to1[4][7] = 0.916532678005337;
   fWeightMatrix0to1[5][7] = -4.25647667430118;
   fWeightMatrix0to1[6][7] = -1.80806832039511;
   fWeightMatrix0to1[7][7] = -0.156682013609001;
   fWeightMatrix0to1[8][7] = 2.83330514139737;
   fWeightMatrix0to1[9][7] = -3.38373236282418;
   fWeightMatrix0to1[10][7] = 1.62664547928678;
   fWeightMatrix0to1[11][7] = 0.173620155123632;
   fWeightMatrix0to1[12][7] = 5.53523642482649;
   fWeightMatrix0to1[0][8] = 0.260719755601744;
   fWeightMatrix0to1[1][8] = 0.78927356733695;
   fWeightMatrix0to1[2][8] = -3.02519162528039;
   fWeightMatrix0to1[3][8] = 3.57473859411608;
   fWeightMatrix0to1[4][8] = -2.49901715170062;
   fWeightMatrix0to1[5][8] = -0.183828254263258;
   fWeightMatrix0to1[6][8] = -0.313387261929908;
   fWeightMatrix0to1[7][8] = 0.558070785722973;
   fWeightMatrix0to1[8][8] = 0.138711104233984;
   fWeightMatrix0to1[9][8] = 4.96364532564904;
   fWeightMatrix0to1[10][8] = 0.328966133891179;
   fWeightMatrix0to1[11][8] = -0.0485304113079557;
   fWeightMatrix0to1[12][8] = 2.22243328140056;
   fWeightMatrix0to1[0][9] = 1.06291698610815;
   fWeightMatrix0to1[1][9] = -0.163501380903085;
   fWeightMatrix0to1[2][9] = 0.313295765127274;
   fWeightMatrix0to1[3][9] = -0.086001175964235;
   fWeightMatrix0to1[4][9] = 1.73134078503843;
   fWeightMatrix0to1[5][9] = -0.736598338406862;
   fWeightMatrix0to1[6][9] = 0.0852532441555962;
   fWeightMatrix0to1[7][9] = 0.516765746586148;
   fWeightMatrix0to1[8][9] = 0.312498810958728;
   fWeightMatrix0to1[9][9] = 0.11393075686931;
   fWeightMatrix0to1[10][9] = 0.493461883897857;
   fWeightMatrix0to1[11][9] = 1.05395958100794;
   fWeightMatrix0to1[12][9] = -1.5536881964847;
   fWeightMatrix0to1[0][10] = 0.882848270191553;
   fWeightMatrix0to1[1][10] = -0.911429412229657;
   fWeightMatrix0to1[2][10] = 0.632395382174443;
   fWeightMatrix0to1[3][10] = 1.86532187759371;
   fWeightMatrix0to1[4][10] = -0.284773785831046;
   fWeightMatrix0to1[5][10] = -2.85252910042684;
   fWeightMatrix0to1[6][10] = 1.19275902104619;
   fWeightMatrix0to1[7][10] = -2.08394379083123;
   fWeightMatrix0to1[8][10] = -2.26535610290866;
   fWeightMatrix0to1[9][10] = 0.358359432775899;
   fWeightMatrix0to1[10][10] = -0.782983891443198;
   fWeightMatrix0to1[11][10] = 1.49659035213626;
   fWeightMatrix0to1[12][10] = -0.660962890493895;
   fWeightMatrix0to1[0][11] = -1.04316046293002;
   fWeightMatrix0to1[1][11] = -2.05257418122379;
   fWeightMatrix0to1[2][11] = -0.890502392294041;
   fWeightMatrix0to1[3][11] = 5.14358487662151;
   fWeightMatrix0to1[4][11] = 0.496261943086495;
   fWeightMatrix0to1[5][11] = 0.814681923068262;
   fWeightMatrix0to1[6][11] = -0.000455953347188175;
   fWeightMatrix0to1[7][11] = -3.73771025729836;
   fWeightMatrix0to1[8][11] = 0.504263853136137;
   fWeightMatrix0to1[9][11] = 2.03627206589248;
   fWeightMatrix0to1[10][11] = -2.71990333554784;
   fWeightMatrix0to1[11][11] = -10.6429902973512;
   fWeightMatrix0to1[12][11] = 0.0790273702703786;
   fWeightMatrix0to1[0][12] = 2.02865865514746;
   fWeightMatrix0to1[1][12] = 27.4039921619436;
   fWeightMatrix0to1[2][12] = 1.12896804680305;
   fWeightMatrix0to1[3][12] = 5.9718091513768;
   fWeightMatrix0to1[4][12] = 8.3083950639934;
   fWeightMatrix0to1[5][12] = 1.23765602692359;
   fWeightMatrix0to1[6][12] = 1.9054287081071;
   fWeightMatrix0to1[7][12] = 10.4210645814143;
   fWeightMatrix0to1[8][12] = 1.07471412840991;
   fWeightMatrix0to1[9][12] = -4.29088376230554;
   fWeightMatrix0to1[10][12] = -7.84881045674496;
   fWeightMatrix0to1[11][12] = -1.39225023752827;
   fWeightMatrix0to1[12][12] = 4.92849719042221;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.13606622651283;
   fWeightMatrix1to2[1][0] = 1.56026469135779;
   fWeightMatrix1to2[2][0] = 2.47634792414513;
   fWeightMatrix1to2[3][0] = -0.924992231545923;
   fWeightMatrix1to2[4][0] = 2.71270877234778;
   fWeightMatrix1to2[5][0] = 2.99499623358434;
   fWeightMatrix1to2[6][0] = 3.48004886607061;
   fWeightMatrix1to2[7][0] = -0.917806562318271;
   fWeightMatrix1to2[8][0] = 1.28609672926816;
   fWeightMatrix1to2[9][0] = 2.17826804241944;
   fWeightMatrix1to2[10][0] = -1.33621115941361;
   fWeightMatrix1to2[0][1] = -5.86877051738756;
   fWeightMatrix1to2[1][1] = 2.31922241197769;
   fWeightMatrix1to2[2][1] = 5.81296475901118;
   fWeightMatrix1to2[3][1] = -4.465628502888;
   fWeightMatrix1to2[4][1] = 5.84609521906805;
   fWeightMatrix1to2[5][1] = 0.653028147929131;
   fWeightMatrix1to2[6][1] = -3.26654937872631;
   fWeightMatrix1to2[7][1] = 4.92708256811971;
   fWeightMatrix1to2[8][1] = 0.365801052923806;
   fWeightMatrix1to2[9][1] = -6.37479169755619;
   fWeightMatrix1to2[10][1] = -3.27635916580498;
   fWeightMatrix1to2[0][2] = -1.08731167191404;
   fWeightMatrix1to2[1][2] = 0.854725302557969;
   fWeightMatrix1to2[2][2] = 1.36964909428916;
   fWeightMatrix1to2[3][2] = -0.710283482626184;
   fWeightMatrix1to2[4][2] = -3.89988616661676;
   fWeightMatrix1to2[5][2] = -1.0581019828266;
   fWeightMatrix1to2[6][2] = 0.688196262137094;
   fWeightMatrix1to2[7][2] = 0.125619885614113;
   fWeightMatrix1to2[8][2] = -5.31633943714954;
   fWeightMatrix1to2[9][2] = 2.33739841721569;
   fWeightMatrix1to2[10][2] = -1.25719896042577;
   fWeightMatrix1to2[0][3] = -3.32765230163742;
   fWeightMatrix1to2[1][3] = -2.19392470835828;
   fWeightMatrix1to2[2][3] = 2.70853134996409;
   fWeightMatrix1to2[3][3] = 2.64712693957259;
   fWeightMatrix1to2[4][3] = 0.025813665578399;
   fWeightMatrix1to2[5][3] = 1.5242106604529;
   fWeightMatrix1to2[6][3] = 0.284322439263516;
   fWeightMatrix1to2[7][3] = 2.99338732015519;
   fWeightMatrix1to2[8][3] = 1.9318183820131;
   fWeightMatrix1to2[9][3] = -2.2678088848366;
   fWeightMatrix1to2[10][3] = -3.26139184771721;
   fWeightMatrix1to2[0][4] = 1.60305767639475;
   fWeightMatrix1to2[1][4] = 0.932337798027246;
   fWeightMatrix1to2[2][4] = -3.98055885440584;
   fWeightMatrix1to2[3][4] = -0.0850658881139012;
   fWeightMatrix1to2[4][4] = -0.672580718317336;
   fWeightMatrix1to2[5][4] = 4.49010858286025;
   fWeightMatrix1to2[6][4] = -5.06956838620102;
   fWeightMatrix1to2[7][4] = 0.274770189135112;
   fWeightMatrix1to2[8][4] = 1.78631081274932;
   fWeightMatrix1to2[9][4] = -4.54587914482847;
   fWeightMatrix1to2[10][4] = 5.92860316547206;
   fWeightMatrix1to2[0][5] = -1.17824668334567;
   fWeightMatrix1to2[1][5] = -2.01754360248794;
   fWeightMatrix1to2[2][5] = -0.0688857255481129;
   fWeightMatrix1to2[3][5] = -1.46904683389611;
   fWeightMatrix1to2[4][5] = -4.65687475545873;
   fWeightMatrix1to2[5][5] = 0.32070249777902;
   fWeightMatrix1to2[6][5] = -1.7658566948513;
   fWeightMatrix1to2[7][5] = -2.07576517785647;
   fWeightMatrix1to2[8][5] = 0.781541704259165;
   fWeightMatrix1to2[9][5] = -0.560520111029888;
   fWeightMatrix1to2[10][5] = 6.58636132268145;
   fWeightMatrix1to2[0][6] = -1.62450119355324;
   fWeightMatrix1to2[1][6] = -0.379014770638666;
   fWeightMatrix1to2[2][6] = -1.94805846240928;
   fWeightMatrix1to2[3][6] = -1.56657523227642;
   fWeightMatrix1to2[4][6] = 0.626211179007593;
   fWeightMatrix1to2[5][6] = -1.86192710999767;
   fWeightMatrix1to2[6][6] = -6.67595339523719;
   fWeightMatrix1to2[7][6] = 0.566950941059933;
   fWeightMatrix1to2[8][6] = -4.25973563476038;
   fWeightMatrix1to2[9][6] = -6.75353984997435;
   fWeightMatrix1to2[10][6] = -2.2678444743775;
   fWeightMatrix1to2[0][7] = -1.0172993105349;
   fWeightMatrix1to2[1][7] = -2.9553868318091;
   fWeightMatrix1to2[2][7] = 3.08638294259598;
   fWeightMatrix1to2[3][7] = -0.502512381360444;
   fWeightMatrix1to2[4][7] = 1.03259566039064;
   fWeightMatrix1to2[5][7] = -0.647968043434306;
   fWeightMatrix1to2[6][7] = -1.00132526715779;
   fWeightMatrix1to2[7][7] = 0.313846946132895;
   fWeightMatrix1to2[8][7] = 2.31535797634076;
   fWeightMatrix1to2[9][7] = -2.03757166984052;
   fWeightMatrix1to2[10][7] = -0.119351652291337;
   fWeightMatrix1to2[0][8] = 2.41077099504352;
   fWeightMatrix1to2[1][8] = -2.73242386616877;
   fWeightMatrix1to2[2][8] = -3.05662965468243;
   fWeightMatrix1to2[3][8] = -0.0578262320264685;
   fWeightMatrix1to2[4][8] = -2.80859530515203;
   fWeightMatrix1to2[5][8] = 1.44681321356479;
   fWeightMatrix1to2[6][8] = 1.31640522117263;
   fWeightMatrix1to2[7][8] = 1.16775111736755;
   fWeightMatrix1to2[8][8] = -1.42144033976742;
   fWeightMatrix1to2[9][8] = 1.36999451771437;
   fWeightMatrix1to2[10][8] = 1.92883209462787;
   fWeightMatrix1to2[0][9] = 1.77808624575026;
   fWeightMatrix1to2[1][9] = -3.03779623076241;
   fWeightMatrix1to2[2][9] = -1.22126973461934;
   fWeightMatrix1to2[3][9] = 0.105289645571355;
   fWeightMatrix1to2[4][9] = -3.1075635351838;
   fWeightMatrix1to2[5][9] = -1.55597544716188;
   fWeightMatrix1to2[6][9] = -2.14369419123191;
   fWeightMatrix1to2[7][9] = 2.78694820403225;
   fWeightMatrix1to2[8][9] = -0.0326944853624232;
   fWeightMatrix1to2[9][9] = -1.73472099103545;
   fWeightMatrix1to2[10][9] = 1.21215434849913;
   fWeightMatrix1to2[0][10] = 1.84547807418878;
   fWeightMatrix1to2[1][10] = -4.17822661008973;
   fWeightMatrix1to2[2][10] = -3.46276508738274;
   fWeightMatrix1to2[3][10] = -2.10282915343946;
   fWeightMatrix1to2[4][10] = -3.21039071838958;
   fWeightMatrix1to2[5][10] = -0.251147597006276;
   fWeightMatrix1to2[6][10] = -0.389987337506309;
   fWeightMatrix1to2[7][10] = -4.02708462167958;
   fWeightMatrix1to2[8][10] = -1.72574871949183;
   fWeightMatrix1to2[9][10] = -0.486010029298098;
   fWeightMatrix1to2[10][10] = -2.22813109215625;
   fWeightMatrix1to2[0][11] = -3.94994863323558;
   fWeightMatrix1to2[1][11] = -1.15656459176222;
   fWeightMatrix1to2[2][11] = 3.85321847152617;
   fWeightMatrix1to2[3][11] = -0.160470760906669;
   fWeightMatrix1to2[4][11] = 3.75783615554656;
   fWeightMatrix1to2[5][11] = -4.74569342767706;
   fWeightMatrix1to2[6][11] = 1.76111552082909;
   fWeightMatrix1to2[7][11] = -3.1002160060392;
   fWeightMatrix1to2[8][11] = -2.85575349116435;
   fWeightMatrix1to2[9][11] = -4.25324943330768;
   fWeightMatrix1to2[10][11] = -0.0534136895242253;
   fWeightMatrix1to2[0][12] = 2.7816878722829;
   fWeightMatrix1to2[1][12] = 4.49169378513699;
   fWeightMatrix1to2[2][12] = -7.90551286872327;
   fWeightMatrix1to2[3][12] = -1.52688791761329;
   fWeightMatrix1to2[4][12] = -5.85438195116277;
   fWeightMatrix1to2[5][12] = -0.541956183894897;
   fWeightMatrix1to2[6][12] = -3.03833249323405;
   fWeightMatrix1to2[7][12] = -0.661169070182044;
   fWeightMatrix1to2[8][12] = 0.957212033610407;
   fWeightMatrix1to2[9][12] = -0.250214452046526;
   fWeightMatrix1to2[10][12] = 7.60213738517187;
   fWeightMatrix1to2[0][13] = 2.06154478619352;
   fWeightMatrix1to2[1][13] = -2.07644811522709;
   fWeightMatrix1to2[2][13] = -3.181539145227;
   fWeightMatrix1to2[3][13] = 0.459227368693295;
   fWeightMatrix1to2[4][13] = -2.56051457600307;
   fWeightMatrix1to2[5][13] = -4.67701484042984;
   fWeightMatrix1to2[6][13] = 7.41747780528367;
   fWeightMatrix1to2[7][13] = -0.039195413894313;
   fWeightMatrix1to2[8][13] = -0.193981607074102;
   fWeightMatrix1to2[9][13] = 4.67342075569474;
   fWeightMatrix1to2[10][13] = 4.39193268598913;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -3.46348908641096;
   fWeightMatrix2to3[0][1] = -3.54289207593253;
   fWeightMatrix2to3[0][2] = 1.86304917405135;
   fWeightMatrix2to3[0][3] = -5.02169686589234;
   fWeightMatrix2to3[0][4] = 7.58723047604793;
   fWeightMatrix2to3[0][5] = -5.15365688674926;
   fWeightMatrix2to3[0][6] = 3.69745461416309;
   fWeightMatrix2to3[0][7] = -2.77215336263931;
   fWeightMatrix2to3[0][8] = 4.531381991613;
   fWeightMatrix2to3[0][9] = -3.99130700307119;
   fWeightMatrix2to3[0][10] = -4.61741559117742;
   fWeightMatrix2to3[0][11] = 2.71118020532666;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 91;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 172;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 172;
   fMin_1[0][1] = 7;
   fMax_1[0][1] = 141;
   fMin_1[1][1] = 8;
   fMax_1[1][1] = 955;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 955;
   fMin_1[0][2] = 2.01117420197;
   fMax_1[0][2] = 105256.398438;
   fMin_1[1][2] = 1.97109591961;
   fMax_1[1][2] = 561.335266113;
   fMin_1[2][2] = 1.97109591961;
   fMax_1[2][2] = 105256.398438;
   fMin_1[0][3] = -0.311883032322;
   fMax_1[0][3] = 0.946100950241;
   fMin_1[1][3] = -0.332784891129;
   fMax_1[1][3] = 0.999793052673;
   fMin_1[2][3] = -0.332784891129;
   fMax_1[2][3] = 0.999793052673;
   fMin_1[0][4] = -0.231652453542;
   fMax_1[0][4] = 0.582291722298;
   fMin_1[1][4] = -0.322455346584;
   fMax_1[1][4] = 0.996899008751;
   fMin_1[2][4] = -0.322455346584;
   fMax_1[2][4] = 0.996899008751;
   fMin_1[0][5] = 24.3735771179;
   fMax_1[0][5] = 89.1047134399;
   fMin_1[1][5] = 0.724473893642;
   fMax_1[1][5] = 89.9999923706;
   fMin_1[2][5] = 0.724473893642;
   fMax_1[2][5] = 89.9999923706;
   fMin_1[0][6] = -234.4609375;
   fMax_1[0][6] = 177.091552734;
   fMin_1[1][6] = -326.031768799;
   fMax_1[1][6] = 361.014984131;
   fMin_1[2][6] = -326.031768799;
   fMax_1[2][6] = 361.014984131;
   fMin_1[0][7] = 0.0739173516631;
   fMax_1[0][7] = 33.5877952576;
   fMin_1[1][7] = 1.52587890625e-05;
   fMax_1[1][7] = 45.8233795166;
   fMin_1[2][7] = 1.52587890625e-05;
   fMax_1[2][7] = 45.8233795166;
   fMin_1[0][8] = 11.3343648911;
   fMax_1[0][8] = 89.6232299805;
   fMin_1[1][8] = 0.685668647289;
   fMax_1[1][8] = 94.3646697998;
   fMin_1[2][8] = 0.685668647289;
   fMax_1[2][8] = 94.3646697998;
   fMin_1[0][9] = 1.5785189867;
   fMax_1[0][9] = 69.1346893311;
   fMin_1[1][9] = 0.00536481430754;
   fMax_1[1][9] = 87.3727264404;
   fMin_1[2][9] = 0.00536481430754;
   fMax_1[2][9] = 87.3727264404;
   fMin_1[0][10] = 200.003662109;
   fMax_1[0][10] = 1669.29736328;
   fMin_1[1][10] = 200.000976562;
   fMax_1[1][10] = 1676.24499512;
   fMin_1[2][10] = 200.000976562;
   fMax_1[2][10] = 1676.24499512;
   fMin_1[0][11] = 201.668197632;
   fMax_1[0][11] = 4584.47949219;
   fMin_1[1][11] = 217.156478882;
   fMax_1[1][11] = 4647.00341797;
   fMin_1[2][11] = 201.668197632;
   fMax_1[2][11] = 4647.00341797;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
