#!/bin/bash

bin=$(pwd)/bin
pathline="export PATH=$bin:\$PATH # Install NTagLib"
ntagline="export NTAGLIBPATH=$(pwd) # Install NTagLib"

if [ $1 = "set" ]; then
    export PATH=$bin:$PATH
    export NTAGLIBPATH=$(pwd)
    echo $pathline >> ~/.bashrc
    echo $ntagline >> ~/.bashrc
    echo "[NTagLib] The path to the NTagLib executables has been added to your \$PATH."
elif [ $1 = "unset" ]; then
    export PATH=${PATH//$bin:/}
    unset NTAGLIBPATH
    sed -i '/Install NTagLib/d' ~/.bashrc
    echo "[NTagLib] The path to the NTagLib executables has been removed from your \$PATH."
else
    echo "[NTagLib] Unknown command $1! Please use either set or unset."
fi