#!/bin/csh

set bin = `pwd`/bin
set ntaglib = `pwd`
set pathline = "setenv PATH $bin\:\$PATH # Install NTagLib"
set ntagline = "setenv NTAGLIBPATH $ntaglib # Install NTagLib"

if ($1 == "set") then
    setenv PATH $bin\:$PATH
    setenv NTAGLIBPATH $PWD
    echo $pathline | tee -a ~/.{csh,tcsh}rc >/dev/null
    echo $ntagline | tee -a ~/.{csh,tcsh}rc >/dev/null
    echo "[NTagLib] The path to the NTagLib executables has been added to your PATH."
else if ($1 == "unset") then
    setenv PATH `echo $PATH | sed 's|'"${bin}:"'||g'`
    unsetenv NTAGLIBPATH
    sed -i '/Install NTag/d' ~/.{csh,tcsh}rc
    echo "[NTagLib] The path to the NTagLib executables has been removed from your PATH."
else
    echo "[NTagLib] Unknown command $1! Please use either set or unset."
endif
