#!/bin/csh

set bin = "$PWD/bin"
set pathline = "setenv PATH $bin\:\$PATH # Install NTag"
set ntagline = "setenv NTAGPATH $PWD     # Install NTag"

if ($1 == "set") then
    setenv PATH $bin\:$PATH
    setenv NTAGPATH $PWD
    echo $pathline | tee -a ~/.{csh,tcsh}rc >/dev/null
    echo $ntagline | tee -a ~/.{csh,tcsh}rc >/dev/null
    echo "[NTag] The path to the NTag executable has been added to your PATH."
    echo "[NTag] Use NTag anywhere you want!"
else if ($1 == "unset") then
    setenv PATH `echo $PATH | sed 's|'"${bin}:"'||g'`
    unsetenv NTAGPATH
    sed -i '/Install NTag/d' ~/.{csh,tcsh}rc
    echo "[NTag] The path to the NTag executable has been removed from your PATH."
else
    echo "[NTag] Unknown command $1! Please use either set or unset."
endif
