var annotated_dup =
[
    [ "ArgParser", "classArgParser.html", "classArgParser" ],
    [ "BonsaiManager", "classBonsaiManager.html", null ],
    [ "Candidate", "classCandidate.html", "classCandidate" ],
    [ "CandidateCluster", "classCandidateCluster.html", "classCandidateCluster" ],
    [ "CandidateTagger", "classCandidateTagger.html", null ],
    [ "Cluster", "classCluster.html", "classCluster" ],
    [ "EventNTagManager", "classEventNTagManager.html", null ],
    [ "MuechkTree", "classMuechkTree.html", "classMuechkTree" ],
    [ "NoiseManager", "classNoiseManager.html", null ],
    [ "NTagKerasManager", "classNTagKerasManager.html", null ],
    [ "NTagTMVAManager", "classNTagTMVAManager.html", null ],
    [ "NTagTree", "classNTagTree.html", "classNTagTree" ],
    [ "OpeningAngleStats", "structOpeningAngleStats.html", null ],
    [ "Particle", "classParticle.html", null ],
    [ "ParticleCluster", "classParticleCluster.html", "classParticleCluster" ],
    [ "PMTHit", "classPMTHit.html", null ],
    [ "PMTHitCluster", "classPMTHitCluster.html", "classPMTHitCluster" ],
    [ "Printer", "classPrinter.html", "classPrinter" ],
    [ "SKIO", "classSKIO.html", null ],
    [ "Store", "classStore.html", null ],
    [ "Taggable", "classTaggable.html", null ],
    [ "TaggableCluster", "classTaggableCluster.html", "classTaggableCluster" ],
    [ "TaggableTree", "classTaggableTree.html", "classTaggableTree" ],
    [ "TInterruptHandler", "classTInterruptHandler.html", null ],
    [ "TreeOut", "classTreeOut.html", null ],
    [ "TriggerManager", "classTriggerManager.html", null ],
    [ "TRMSFitManager", "classTRMSFitManager.html", null ],
    [ "VertexFitManager", "classVertexFitManager.html", null ]
];