// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.28/00       [334848]
Creator        : han
Date           : Tue Dec  7 21:14:14 2021
Host           : Linux sukla01 3.10.0-327.36.3.el7.x86_64 #1 SMP Thu Oct 20 04:56:07 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk02/calib3/usr/han/mc/random
Training events: 4867761
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,177]
N200                          N200                          N200                          N200                                                            'F'    [8,996]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [2.02867269516,645.847290039]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.333208173513,0.999804377556]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.315233141184,0.997069239616]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [0.803928911686,89.9999694824]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-307.227264404,354.623657227]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [3.17637022818e-05,45.6349830627]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.64941328764,94.696647644]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.0965016558766,87.3619689941]
DWall                         DWall                         DWall                         DWall                                                           'F'    [3.28723144531,1690]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [11.0913171768,4933.17626953]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 4.75282886590914;
   fWeightMatrix0to1[1][0] = 39.450776751307;
   fWeightMatrix0to1[2][0] = 15.6875703736431;
   fWeightMatrix0to1[3][0] = 13.4819158862689;
   fWeightMatrix0to1[4][0] = -10.2726606743009;
   fWeightMatrix0to1[5][0] = -8.79125387555699;
   fWeightMatrix0to1[6][0] = -11.56124468939;
   fWeightMatrix0to1[7][0] = 26.8533781023236;
   fWeightMatrix0to1[8][0] = -3.93711476118754;
   fWeightMatrix0to1[9][0] = -19.4861375017367;
   fWeightMatrix0to1[10][0] = -15.7832660536311;
   fWeightMatrix0to1[11][0] = 12.6208699214023;
   fWeightMatrix0to1[12][0] = 0.500569012156451;
   fWeightMatrix0to1[0][1] = -11.7560564326565;
   fWeightMatrix0to1[1][1] = -6.9878844260909;
   fWeightMatrix0to1[2][1] = 9.07028211427627;
   fWeightMatrix0to1[3][1] = -1.07166201048315;
   fWeightMatrix0to1[4][1] = 27.8176230082784;
   fWeightMatrix0to1[5][1] = 9.37680059118798;
   fWeightMatrix0to1[6][1] = 14.3914912763938;
   fWeightMatrix0to1[7][1] = 4.49068175372133;
   fWeightMatrix0to1[8][1] = 11.2901216633146;
   fWeightMatrix0to1[9][1] = 23.1167287565868;
   fWeightMatrix0to1[10][1] = -0.030495869776652;
   fWeightMatrix0to1[11][1] = -5.89275499661454;
   fWeightMatrix0to1[12][1] = -0.861755013425556;
   fWeightMatrix0to1[0][2] = 5.00997474655356;
   fWeightMatrix0to1[1][2] = -19.934582806738;
   fWeightMatrix0to1[2][2] = -20.1442118951952;
   fWeightMatrix0to1[3][2] = -2.29779843869306;
   fWeightMatrix0to1[4][2] = -5.50124456387783;
   fWeightMatrix0to1[5][2] = -4.65226357277334;
   fWeightMatrix0to1[6][2] = 2.79950292335482;
   fWeightMatrix0to1[7][2] = -17.8910819581246;
   fWeightMatrix0to1[8][2] = -0.428055123589959;
   fWeightMatrix0to1[9][2] = 4.50285145918103;
   fWeightMatrix0to1[10][2] = 12.9531909286695;
   fWeightMatrix0to1[11][2] = -1.66139402638976;
   fWeightMatrix0to1[12][2] = -1.25032732709453;
   fWeightMatrix0to1[0][3] = -0.26540214720205;
   fWeightMatrix0to1[1][3] = 3.32109546110496;
   fWeightMatrix0to1[2][3] = -1.58631443169103;
   fWeightMatrix0to1[3][3] = -0.0210692408313102;
   fWeightMatrix0to1[4][3] = -3.36000662745455;
   fWeightMatrix0to1[5][3] = 2.93894799396122;
   fWeightMatrix0to1[6][3] = -0.0533683139298923;
   fWeightMatrix0to1[7][3] = 3.03925717200398;
   fWeightMatrix0to1[8][3] = 10.2404962103372;
   fWeightMatrix0to1[9][3] = 4.11710971949834;
   fWeightMatrix0to1[10][3] = 3.4204903767176;
   fWeightMatrix0to1[11][3] = 1.2365813318134;
   fWeightMatrix0to1[12][3] = -2.82003701522425;
   fWeightMatrix0to1[0][4] = -0.778034227768454;
   fWeightMatrix0to1[1][4] = 0.582952255684033;
   fWeightMatrix0to1[2][4] = 0.0525008110592807;
   fWeightMatrix0to1[3][4] = 1.06722570135738;
   fWeightMatrix0to1[4][4] = 1.38704236184675;
   fWeightMatrix0to1[5][4] = 1.4702233620454;
   fWeightMatrix0to1[6][4] = 4.16318373649087;
   fWeightMatrix0to1[7][4] = -2.38927292450137;
   fWeightMatrix0to1[8][4] = 1.91834964898025;
   fWeightMatrix0to1[9][4] = -0.984308089547836;
   fWeightMatrix0to1[10][4] = -1.7157782823215;
   fWeightMatrix0to1[11][4] = -0.930484728097695;
   fWeightMatrix0to1[12][4] = -3.24496016372217;
   fWeightMatrix0to1[0][5] = 0.557108310577894;
   fWeightMatrix0to1[1][5] = 0.198700142500252;
   fWeightMatrix0to1[2][5] = -1.88318520695994;
   fWeightMatrix0to1[3][5] = 6.35979884301529;
   fWeightMatrix0to1[4][5] = -6.11924733003518;
   fWeightMatrix0to1[5][5] = 2.1991567133631;
   fWeightMatrix0to1[6][5] = -9.75674051437916;
   fWeightMatrix0to1[7][5] = 3.84006737507534;
   fWeightMatrix0to1[8][5] = 9.01158541352039;
   fWeightMatrix0to1[9][5] = 8.33901792478092;
   fWeightMatrix0to1[10][5] = 5.21479276819572;
   fWeightMatrix0to1[11][5] = -2.48400280304671;
   fWeightMatrix0to1[12][5] = -9.65426682286014;
   fWeightMatrix0to1[0][6] = 3.37620168250663;
   fWeightMatrix0to1[1][6] = -2.24876332578539;
   fWeightMatrix0to1[2][6] = 0.0167385408997453;
   fWeightMatrix0to1[3][6] = 0.0935563649200714;
   fWeightMatrix0to1[4][6] = -1.3444919289764;
   fWeightMatrix0to1[5][6] = -3.73923773893396;
   fWeightMatrix0to1[6][6] = -9.90407453034919;
   fWeightMatrix0to1[7][6] = -0.729386847730627;
   fWeightMatrix0to1[8][6] = -7.33992131898041;
   fWeightMatrix0to1[9][6] = 2.22766958634671;
   fWeightMatrix0to1[10][6] = -3.15733444151413;
   fWeightMatrix0to1[11][6] = -3.51391168338568;
   fWeightMatrix0to1[12][6] = 1.97196070761773;
   fWeightMatrix0to1[0][7] = 0.529539408481851;
   fWeightMatrix0to1[1][7] = 0.599036020036762;
   fWeightMatrix0to1[2][7] = 1.01843976241107;
   fWeightMatrix0to1[3][7] = 1.46283886255825;
   fWeightMatrix0to1[4][7] = 4.0235641876086;
   fWeightMatrix0to1[5][7] = 1.97389957982633;
   fWeightMatrix0to1[6][7] = 4.02346746646516;
   fWeightMatrix0to1[7][7] = 1.36565540621859;
   fWeightMatrix0to1[8][7] = -0.628867173289565;
   fWeightMatrix0to1[9][7] = -4.58772844834384;
   fWeightMatrix0to1[10][7] = -3.3309629716998;
   fWeightMatrix0to1[11][7] = 1.78489031743232;
   fWeightMatrix0to1[12][7] = 4.72956663629888;
   fWeightMatrix0to1[0][8] = -3.21286696746398;
   fWeightMatrix0to1[1][8] = 1.43657401028373;
   fWeightMatrix0to1[2][8] = -2.04660861422717;
   fWeightMatrix0to1[3][8] = 3.2129242257358;
   fWeightMatrix0to1[4][8] = -2.1628725586727;
   fWeightMatrix0to1[5][8] = -0.40827319225181;
   fWeightMatrix0to1[6][8] = 4.09438754175577;
   fWeightMatrix0to1[7][8] = 1.03523362000968;
   fWeightMatrix0to1[8][8] = -1.15254738704637;
   fWeightMatrix0to1[9][8] = 1.98568273757891;
   fWeightMatrix0to1[10][8] = -3.18867525932317;
   fWeightMatrix0to1[11][8] = 3.69237173067734;
   fWeightMatrix0to1[12][8] = 3.11900926761627;
   fWeightMatrix0to1[0][9] = 0.138669315571134;
   fWeightMatrix0to1[1][9] = 0.328084742160683;
   fWeightMatrix0to1[2][9] = -0.44194530554153;
   fWeightMatrix0to1[3][9] = 2.0148068170535;
   fWeightMatrix0to1[4][9] = 0.140895837562806;
   fWeightMatrix0to1[5][9] = -2.21925282214772;
   fWeightMatrix0to1[6][9] = -0.903368122050803;
   fWeightMatrix0to1[7][9] = -0.207545782376642;
   fWeightMatrix0to1[8][9] = 2.05391590852505;
   fWeightMatrix0to1[9][9] = 0.300664451029271;
   fWeightMatrix0to1[10][9] = 0.336348955135958;
   fWeightMatrix0to1[11][9] = -1.40733681567018;
   fWeightMatrix0to1[12][9] = -2.68438671811079;
   fWeightMatrix0to1[0][10] = 0.548008804902152;
   fWeightMatrix0to1[1][10] = -1.78744513417844;
   fWeightMatrix0to1[2][10] = 0.637987034739746;
   fWeightMatrix0to1[3][10] = -3.47922135018833;
   fWeightMatrix0to1[4][10] = -0.629011568295382;
   fWeightMatrix0to1[5][10] = 11.5033913464402;
   fWeightMatrix0to1[6][10] = 1.7135755139167;
   fWeightMatrix0to1[7][10] = 1.08034047094366;
   fWeightMatrix0to1[8][10] = -1.42519910370079;
   fWeightMatrix0to1[9][10] = -0.879086296149197;
   fWeightMatrix0to1[10][10] = -0.484892263950198;
   fWeightMatrix0to1[11][10] = -4.57263299852606;
   fWeightMatrix0to1[12][10] = -8.548989275862;
   fWeightMatrix0to1[0][11] = -4.47099065781269;
   fWeightMatrix0to1[1][11] = -4.46973903717628;
   fWeightMatrix0to1[2][11] = 0.226738797786177;
   fWeightMatrix0to1[3][11] = 0.806785086454836;
   fWeightMatrix0to1[4][11] = 0.0626341799237159;
   fWeightMatrix0to1[5][11] = 0.0724782027775297;
   fWeightMatrix0to1[6][11] = 1.03870134490693;
   fWeightMatrix0to1[7][11] = 0.333212819528849;
   fWeightMatrix0to1[8][11] = 0.312763902198998;
   fWeightMatrix0to1[9][11] = 0.578948930968197;
   fWeightMatrix0to1[10][11] = -1.7334034195568;
   fWeightMatrix0to1[11][11] = 0.988223242423974;
   fWeightMatrix0to1[12][11] = 1.93162929620367;
   fWeightMatrix0to1[0][12] = -3.79521043137763;
   fWeightMatrix0to1[1][12] = 10.7939814071346;
   fWeightMatrix0to1[2][12] = 4.384709853719;
   fWeightMatrix0to1[3][12] = 3.58661294998719;
   fWeightMatrix0to1[4][12] = 12.3040847538697;
   fWeightMatrix0to1[5][12] = 8.13257202865682;
   fWeightMatrix0to1[6][12] = 7.90721885923267;
   fWeightMatrix0to1[7][12] = 6.73567151307635;
   fWeightMatrix0to1[8][12] = 4.675707873119;
   fWeightMatrix0to1[9][12] = 4.46905534937548;
   fWeightMatrix0to1[10][12] = -2.58809582026772;
   fWeightMatrix0to1[11][12] = 1.63104377741507;
   fWeightMatrix0to1[12][12] = -7.10113216342421;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -4.35765190736882;
   fWeightMatrix1to2[1][0] = 3.41663726271341;
   fWeightMatrix1to2[2][0] = 3.52278711150843;
   fWeightMatrix1to2[3][0] = 0.121498656749411;
   fWeightMatrix1to2[4][0] = -3.41040819949339;
   fWeightMatrix1to2[5][0] = 0.845203665040892;
   fWeightMatrix1to2[6][0] = 1.60322385025636;
   fWeightMatrix1to2[7][0] = -1.96177484471206;
   fWeightMatrix1to2[8][0] = 1.51657722713262;
   fWeightMatrix1to2[9][0] = 1.09989140987816;
   fWeightMatrix1to2[10][0] = -3.66723699695003;
   fWeightMatrix1to2[0][1] = -2.32974393358267;
   fWeightMatrix1to2[1][1] = 2.89337656548651;
   fWeightMatrix1to2[2][1] = 8.83493557817099;
   fWeightMatrix1to2[3][1] = -0.689526813429022;
   fWeightMatrix1to2[4][1] = 4.49388036322826;
   fWeightMatrix1to2[5][1] = 0.706094592496384;
   fWeightMatrix1to2[6][1] = 2.95135675562816;
   fWeightMatrix1to2[7][1] = 0.344283334906307;
   fWeightMatrix1to2[8][1] = -3.90609098333677;
   fWeightMatrix1to2[9][1] = -3.61488193375205;
   fWeightMatrix1to2[10][1] = -2.42165990409916;
   fWeightMatrix1to2[0][2] = -4.25212488209553;
   fWeightMatrix1to2[1][2] = -3.63770764403017;
   fWeightMatrix1to2[2][2] = -1.67419330901328;
   fWeightMatrix1to2[3][2] = -3.58569885875932;
   fWeightMatrix1to2[4][2] = -3.97752339468865;
   fWeightMatrix1to2[5][2] = 5.12714091758769;
   fWeightMatrix1to2[6][2] = 4.87499132740662;
   fWeightMatrix1to2[7][2] = 7.28374530665048;
   fWeightMatrix1to2[8][2] = -4.13367724631216;
   fWeightMatrix1to2[9][2] = -0.362387090172573;
   fWeightMatrix1to2[10][2] = -5.27032518547754;
   fWeightMatrix1to2[0][3] = -1.06689416800393;
   fWeightMatrix1to2[1][3] = 1.24680706418477;
   fWeightMatrix1to2[2][3] = 0.810795569607741;
   fWeightMatrix1to2[3][3] = 2.23044991920058;
   fWeightMatrix1to2[4][3] = -1.10234673253329;
   fWeightMatrix1to2[5][3] = 0.901547711730421;
   fWeightMatrix1to2[6][3] = 2.21677365757395;
   fWeightMatrix1to2[7][3] = 1.56972364238414;
   fWeightMatrix1to2[8][3] = 4.33486397180697;
   fWeightMatrix1to2[9][3] = -1.25936838011003;
   fWeightMatrix1to2[10][3] = -1.51688367842125;
   fWeightMatrix1to2[0][4] = 0.310913539905313;
   fWeightMatrix1to2[1][4] = -3.96612858571254;
   fWeightMatrix1to2[2][4] = -5.24516726051615;
   fWeightMatrix1to2[3][4] = -1.4421397834212;
   fWeightMatrix1to2[4][4] = -3.03991476666192;
   fWeightMatrix1to2[5][4] = 5.95105210128936;
   fWeightMatrix1to2[6][4] = -5.0403660607942;
   fWeightMatrix1to2[7][4] = -4.88477020219459;
   fWeightMatrix1to2[8][4] = 2.42541959514252;
   fWeightMatrix1to2[9][4] = -4.20438755833804;
   fWeightMatrix1to2[10][4] = 7.86095686626013;
   fWeightMatrix1to2[0][5] = 3.08625033214277;
   fWeightMatrix1to2[1][5] = -3.05774918003303;
   fWeightMatrix1to2[2][5] = 0.478263232099235;
   fWeightMatrix1to2[3][5] = -1.10542373164759;
   fWeightMatrix1to2[4][5] = -2.96975773048646;
   fWeightMatrix1to2[5][5] = -0.649056058618775;
   fWeightMatrix1to2[6][5] = 0.174846429430723;
   fWeightMatrix1to2[7][5] = 1.0148781014285;
   fWeightMatrix1to2[8][5] = 7.69606639471424;
   fWeightMatrix1to2[9][5] = -2.25253980645457;
   fWeightMatrix1to2[10][5] = 1.91850059421454;
   fWeightMatrix1to2[0][6] = 1.16670419711374;
   fWeightMatrix1to2[1][6] = -0.21150371889152;
   fWeightMatrix1to2[2][6] = -2.65947385410066;
   fWeightMatrix1to2[3][6] = 0.0579753283334827;
   fWeightMatrix1to2[4][6] = -10.9695367267482;
   fWeightMatrix1to2[5][6] = 0.546199080844625;
   fWeightMatrix1to2[6][6] = -2.94122819811598;
   fWeightMatrix1to2[7][6] = -0.737104895005979;
   fWeightMatrix1to2[8][6] = -5.65221361719991;
   fWeightMatrix1to2[9][6] = -6.27834604473239;
   fWeightMatrix1to2[10][6] = 3.27940006433036;
   fWeightMatrix1to2[0][7] = -9.07648590453492;
   fWeightMatrix1to2[1][7] = -4.15741966829934;
   fWeightMatrix1to2[2][7] = 1.91059612402207;
   fWeightMatrix1to2[3][7] = 0.597017817977701;
   fWeightMatrix1to2[4][7] = -4.78294065133808;
   fWeightMatrix1to2[5][7] = -2.87659887718137;
   fWeightMatrix1to2[6][7] = 2.43203739732228;
   fWeightMatrix1to2[7][7] = 8.44459440203143;
   fWeightMatrix1to2[8][7] = 4.48073729451984;
   fWeightMatrix1to2[9][7] = 0.107696986158506;
   fWeightMatrix1to2[10][7] = -4.59388686692125;
   fWeightMatrix1to2[0][8] = 1.40321193556895;
   fWeightMatrix1to2[1][8] = -1.40437418715826;
   fWeightMatrix1to2[2][8] = -2.17034766506525;
   fWeightMatrix1to2[3][8] = 1.61507357884773;
   fWeightMatrix1to2[4][8] = 0.720238450514204;
   fWeightMatrix1to2[5][8] = 0.549559206866313;
   fWeightMatrix1to2[6][8] = -3.66517545279162;
   fWeightMatrix1to2[7][8] = -0.441770821445526;
   fWeightMatrix1to2[8][8] = 1.08030794986937;
   fWeightMatrix1to2[9][8] = -0.317871465976094;
   fWeightMatrix1to2[10][8] = 1.34722069210442;
   fWeightMatrix1to2[0][9] = -1.67394080617781;
   fWeightMatrix1to2[1][9] = -7.09442645072421;
   fWeightMatrix1to2[2][9] = -1.76035676508353;
   fWeightMatrix1to2[3][9] = 0.637496418298844;
   fWeightMatrix1to2[4][9] = -2.20470083742232;
   fWeightMatrix1to2[5][9] = 5.53131362735589;
   fWeightMatrix1to2[6][9] = -3.39578163218674;
   fWeightMatrix1to2[7][9] = 0.141481659834678;
   fWeightMatrix1to2[8][9] = -0.102276656687417;
   fWeightMatrix1to2[9][9] = -3.2312592677131;
   fWeightMatrix1to2[10][9] = 0.807666932775021;
   fWeightMatrix1to2[0][10] = -0.309809603930894;
   fWeightMatrix1to2[1][10] = -4.7457754212585;
   fWeightMatrix1to2[2][10] = -5.09507475821323;
   fWeightMatrix1to2[3][10] = -3.74106291207764;
   fWeightMatrix1to2[4][10] = 3.24317646652591;
   fWeightMatrix1to2[5][10] = -0.307055951337263;
   fWeightMatrix1to2[6][10] = -3.61167860202556;
   fWeightMatrix1to2[7][10] = -5.48093707018052;
   fWeightMatrix1to2[8][10] = 2.01020259234518;
   fWeightMatrix1to2[9][10] = -0.183522008715792;
   fWeightMatrix1to2[10][10] = 4.64474615454329;
   fWeightMatrix1to2[0][11] = -0.0657852426510093;
   fWeightMatrix1to2[1][11] = 5.30072483812196;
   fWeightMatrix1to2[2][11] = -1.43678959823701;
   fWeightMatrix1to2[3][11] = 3.82767588125832;
   fWeightMatrix1to2[4][11] = 1.91121962226208;
   fWeightMatrix1to2[5][11] = -2.40376496366283;
   fWeightMatrix1to2[6][11] = -0.696572574039731;
   fWeightMatrix1to2[7][11] = 0.448550973515298;
   fWeightMatrix1to2[8][11] = -3.67669891402006;
   fWeightMatrix1to2[9][11] = -0.0178136702358234;
   fWeightMatrix1to2[10][11] = -0.571379805546001;
   fWeightMatrix1to2[0][12] = -0.101166265197357;
   fWeightMatrix1to2[1][12] = 1.07572412757656;
   fWeightMatrix1to2[2][12] = -2.91483122038024;
   fWeightMatrix1to2[3][12] = 0.178680421171858;
   fWeightMatrix1to2[4][12] = -0.890554059096596;
   fWeightMatrix1to2[5][12] = 0.634640759162281;
   fWeightMatrix1to2[6][12] = -0.720056878514124;
   fWeightMatrix1to2[7][12] = 0.0270519674714341;
   fWeightMatrix1to2[8][12] = 1.47174596123869;
   fWeightMatrix1to2[9][12] = 1.04161822027716;
   fWeightMatrix1to2[10][12] = -0.791322684436055;
   fWeightMatrix1to2[0][13] = -0.421005863753117;
   fWeightMatrix1to2[1][13] = 0.780435681724641;
   fWeightMatrix1to2[2][13] = -5.36919187088965;
   fWeightMatrix1to2[3][13] = -1.78006894798511;
   fWeightMatrix1to2[4][13] = -1.47829633182036;
   fWeightMatrix1to2[5][13] = -6.66729352475632;
   fWeightMatrix1to2[6][13] = -2.09250893013822;
   fWeightMatrix1to2[7][13] = 4.35927231488419;
   fWeightMatrix1to2[8][13] = -1.202392308301;
   fWeightMatrix1to2[9][13] = 4.30499163410532;
   fWeightMatrix1to2[10][13] = -2.25280291328901;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -4.33018904655363;
   fWeightMatrix2to3[0][1] = -5.08256583474442;
   fWeightMatrix2to3[0][2] = 8.15440614785501;
   fWeightMatrix2to3[0][3] = 3.75166961893379;
   fWeightMatrix2to3[0][4] = 2.46690966641105;
   fWeightMatrix2to3[0][5] = -4.65988024566279;
   fWeightMatrix2to3[0][6] = 3.96020305670077;
   fWeightMatrix2to3[0][7] = -3.33858220407139;
   fWeightMatrix2to3[0][8] = 2.92556819417084;
   fWeightMatrix2to3[0][9] = -3.88219999599896;
   fWeightMatrix2to3[0][10] = -2.90608826294607;
   fWeightMatrix2to3[0][11] = -0.132326783152553;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 95;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 177;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 177;
   fMin_1[0][1] = 11;
   fMax_1[0][1] = 141;
   fMin_1[1][1] = 8;
   fMax_1[1][1] = 996;
   fMin_1[2][1] = 8;
   fMax_1[2][1] = 996;
   fMin_1[0][2] = 2.22809791565;
   fMax_1[0][2] = 54.7207717896;
   fMin_1[1][2] = 2.02867269516;
   fMax_1[1][2] = 645.847290039;
   fMin_1[2][2] = 2.02867269516;
   fMax_1[2][2] = 645.847290039;
   fMin_1[0][3] = -0.330978512764;
   fMax_1[0][3] = 0.987993121147;
   fMin_1[1][3] = -0.333208173513;
   fMax_1[1][3] = 0.999804377556;
   fMin_1[2][3] = -0.333208173513;
   fMax_1[2][3] = 0.999804377556;
   fMin_1[0][4] = -0.288459271193;
   fMax_1[0][4] = 0.835461378098;
   fMin_1[1][4] = -0.315233141184;
   fMax_1[1][4] = 0.997069239616;
   fMin_1[2][4] = -0.315233141184;
   fMax_1[2][4] = 0.997069239616;
   fMin_1[0][5] = 11.5810651779;
   fMax_1[0][5] = 88.6943359375;
   fMin_1[1][5] = 0.803928911686;
   fMax_1[1][5] = 89.9999694824;
   fMin_1[2][5] = 0.803928911686;
   fMax_1[2][5] = 89.9999694824;
   fMin_1[0][6] = -223.068527222;
   fMax_1[0][6] = 211.076660156;
   fMin_1[1][6] = -307.227264404;
   fMax_1[1][6] = 354.623657227;
   fMin_1[2][6] = -307.227264404;
   fMax_1[2][6] = 354.623657227;
   fMin_1[0][7] = 0.0796738788486;
   fMax_1[0][7] = 40.2378845215;
   fMin_1[1][7] = 3.17637022818e-05;
   fMax_1[1][7] = 45.6349830627;
   fMin_1[2][7] = 3.17637022818e-05;
   fMax_1[2][7] = 45.6349830627;
   fMin_1[0][8] = 4.78928375244;
   fMax_1[0][8] = 91.261680603;
   fMin_1[1][8] = 0.64941328764;
   fMax_1[1][8] = 94.696647644;
   fMin_1[2][8] = 0.64941328764;
   fMax_1[2][8] = 94.696647644;
   fMin_1[0][9] = 1.68654489517;
   fMax_1[0][9] = 83.5519104004;
   fMin_1[1][9] = 0.0965016558766;
   fMax_1[1][9] = 87.3619689941;
   fMin_1[2][9] = 0.0965016558766;
   fMax_1[2][9] = 87.3619689941;
   fMin_1[0][10] = 3.28723144531;
   fMax_1[0][10] = 1690;
   fMin_1[1][10] = 3.28723144531;
   fMax_1[1][10] = 1690;
   fMin_1[2][10] = 3.28723144531;
   fMax_1[2][10] = 1690;
   fMin_1[0][11] = 26.2009754181;
   fMax_1[0][11] = 4823.39990234;
   fMin_1[1][11] = 11.0913171768;
   fMax_1[1][11] = 4933.17626953;
   fMin_1[2][11] = 11.0913171768;
   fMax_1[2][11] = 4933.17626953;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
