// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : han
Date           : Tue May  3 20:30:54 2022
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk1/disk02/calib3/usr/han/mc/random
Training events: 7888634
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,936]
N200                          N200                          N200                          N200                                                            'F'    [6,1653]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [1.50743687153,765.105834961]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.331758022308,0.999809086323]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.312476426363,0.997139275074]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [0.839873731136,89.4692993164]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-297.246673584,345.846557617]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.00111616239883,45.5078163147]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.655874788761,93.5002670288]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.189099594951,86.6220550537]
DWall                         DWall                         DWall                         DWall                                                           'F'    [-100,1687.6706543]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [38.8397140503,5093.12207031]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -4.32022880609747;
   fWeightMatrix0to1[1][0] = 105.724477330584;
   fWeightMatrix0to1[2][0] = -14.5523360681148;
   fWeightMatrix0to1[3][0] = 1.41302698554556;
   fWeightMatrix0to1[4][0] = 25.8228132531047;
   fWeightMatrix0to1[5][0] = -21.9263752833152;
   fWeightMatrix0to1[6][0] = -44.3756112228788;
   fWeightMatrix0to1[7][0] = 62.2148308662626;
   fWeightMatrix0to1[8][0] = -27.093090332284;
   fWeightMatrix0to1[9][0] = -23.4687761973855;
   fWeightMatrix0to1[10][0] = -18.1007193195149;
   fWeightMatrix0to1[11][0] = -26.5886938539613;
   fWeightMatrix0to1[12][0] = 0.787823051680223;
   fWeightMatrix0to1[0][1] = 6.75190552486209;
   fWeightMatrix0to1[1][1] = -22.7163179109861;
   fWeightMatrix0to1[2][1] = 1.6768372025153;
   fWeightMatrix0to1[3][1] = -2.57706782985948;
   fWeightMatrix0to1[4][1] = 2.92796477182441;
   fWeightMatrix0to1[5][1] = 4.53568957137186;
   fWeightMatrix0to1[6][1] = 17.9174717126777;
   fWeightMatrix0to1[7][1] = 2.94753832557184;
   fWeightMatrix0to1[8][1] = 11.5218428806719;
   fWeightMatrix0to1[9][1] = 21.2117058945802;
   fWeightMatrix0to1[10][1] = -19.4201602771581;
   fWeightMatrix0to1[11][1] = 16.3814536532816;
   fWeightMatrix0to1[12][1] = 0.251923887685091;
   fWeightMatrix0to1[0][2] = -0.772675050316138;
   fWeightMatrix0to1[1][2] = -23.7814865072896;
   fWeightMatrix0to1[2][2] = 2.87043392361442;
   fWeightMatrix0to1[3][2] = -0.489808436071525;
   fWeightMatrix0to1[4][2] = -14.1527811134315;
   fWeightMatrix0to1[5][2] = 9.12168500189582;
   fWeightMatrix0to1[6][2] = 4.39482608957022;
   fWeightMatrix0to1[7][2] = -29.6261133422188;
   fWeightMatrix0to1[8][2] = -2.78705721583933;
   fWeightMatrix0to1[9][2] = -7.580375712127;
   fWeightMatrix0to1[10][2] = 25.7117480994488;
   fWeightMatrix0to1[11][2] = 3.52448111594177;
   fWeightMatrix0to1[12][2] = 5.80788478122915;
   fWeightMatrix0to1[0][3] = 5.47675468769565;
   fWeightMatrix0to1[1][3] = -0.145475033335555;
   fWeightMatrix0to1[2][3] = -25.1865778227873;
   fWeightMatrix0to1[3][3] = -6.55822008206075;
   fWeightMatrix0to1[4][3] = -3.65560346099188;
   fWeightMatrix0to1[5][3] = -10.6623974017154;
   fWeightMatrix0to1[6][3] = 1.24973304362278;
   fWeightMatrix0to1[7][3] = 2.08694958650207;
   fWeightMatrix0to1[8][3] = 2.41927375593866;
   fWeightMatrix0to1[9][3] = -2.5310862610506;
   fWeightMatrix0to1[10][3] = 0.317757010186623;
   fWeightMatrix0to1[11][3] = 6.81097515761821;
   fWeightMatrix0to1[12][3] = -0.041300680504511;
   fWeightMatrix0to1[0][4] = -0.557914153855921;
   fWeightMatrix0to1[1][4] = -1.06348666553718;
   fWeightMatrix0to1[2][4] = -2.98601731724871;
   fWeightMatrix0to1[3][4] = 3.49368987200867;
   fWeightMatrix0to1[4][4] = -0.723044018871129;
   fWeightMatrix0to1[5][4] = -3.85025203471522;
   fWeightMatrix0to1[6][4] = 6.51315951769883;
   fWeightMatrix0to1[7][4] = 0.299752732850897;
   fWeightMatrix0to1[8][4] = 1.40537929061778;
   fWeightMatrix0to1[9][4] = -3.93044121294198;
   fWeightMatrix0to1[10][4] = -0.74575959784193;
   fWeightMatrix0to1[11][4] = 2.57284806128312;
   fWeightMatrix0to1[12][4] = -0.303715535201901;
   fWeightMatrix0to1[0][5] = -3.11293511446604;
   fWeightMatrix0to1[1][5] = -0.247200079356854;
   fWeightMatrix0to1[2][5] = -4.95508849192508;
   fWeightMatrix0to1[3][5] = -8.68244124311488;
   fWeightMatrix0to1[4][5] = -4.29077712545205;
   fWeightMatrix0to1[5][5] = 0.272547307926675;
   fWeightMatrix0to1[6][5] = -5.25654969093129;
   fWeightMatrix0to1[7][5] = 11.0833511485957;
   fWeightMatrix0to1[8][5] = 5.7969530468466;
   fWeightMatrix0to1[9][5] = 5.892299565626;
   fWeightMatrix0to1[10][5] = 2.4015042352124;
   fWeightMatrix0to1[11][5] = 0.132111094953668;
   fWeightMatrix0to1[12][5] = 4.61076426126307;
   fWeightMatrix0to1[0][6] = -4.39981497727496;
   fWeightMatrix0to1[1][6] = 1.59272988427993;
   fWeightMatrix0to1[2][6] = 0.860670960698673;
   fWeightMatrix0to1[3][6] = -10.5891996047953;
   fWeightMatrix0to1[4][6] = 3.18424166254739;
   fWeightMatrix0to1[5][6] = 5.89681343290038;
   fWeightMatrix0to1[6][6] = -6.9446939389011;
   fWeightMatrix0to1[7][6] = -2.35462548764435;
   fWeightMatrix0to1[8][6] = 3.57897268407407;
   fWeightMatrix0to1[9][6] = 5.40441619645845;
   fWeightMatrix0to1[10][6] = 1.77335841955065;
   fWeightMatrix0to1[11][6] = -15.9206408861567;
   fWeightMatrix0to1[12][6] = 5.41748475855888;
   fWeightMatrix0to1[0][7] = 2.46946846580077;
   fWeightMatrix0to1[1][7] = -0.625244186010996;
   fWeightMatrix0to1[2][7] = 0.445497353690833;
   fWeightMatrix0to1[3][7] = 3.32778681794537;
   fWeightMatrix0to1[4][7] = 4.3743704631439;
   fWeightMatrix0to1[5][7] = 1.03411703619857;
   fWeightMatrix0to1[6][7] = 3.39455465956098;
   fWeightMatrix0to1[7][7] = -0.781153136359281;
   fWeightMatrix0to1[8][7] = -0.657518903405511;
   fWeightMatrix0to1[9][7] = -3.44641365216397;
   fWeightMatrix0to1[10][7] = -0.318913180810685;
   fWeightMatrix0to1[11][7] = -6.48767722986948;
   fWeightMatrix0to1[12][7] = -2.17792325713103;
   fWeightMatrix0to1[0][8] = 5.36418833474977;
   fWeightMatrix0to1[1][8] = 0.537023997553495;
   fWeightMatrix0to1[2][8] = -25.831897878699;
   fWeightMatrix0to1[3][8] = -9.64714629029028;
   fWeightMatrix0to1[4][8] = -3.62790481911437;
   fWeightMatrix0to1[5][8] = -2.51188703176341;
   fWeightMatrix0to1[6][8] = 2.93475047086686;
   fWeightMatrix0to1[7][8] = -0.231846719135134;
   fWeightMatrix0to1[8][8] = 1.20197877161778;
   fWeightMatrix0to1[9][8] = -5.65312485705126;
   fWeightMatrix0to1[10][8] = -2.37498147987212;
   fWeightMatrix0to1[11][8] = 2.81821201288351;
   fWeightMatrix0to1[12][8] = -1.20239731342936;
   fWeightMatrix0to1[0][9] = -0.803747093232973;
   fWeightMatrix0to1[1][9] = -0.307944589266449;
   fWeightMatrix0to1[2][9] = -7.54666031996426;
   fWeightMatrix0to1[3][9] = -0.783559968038413;
   fWeightMatrix0to1[4][9] = -0.759921044945119;
   fWeightMatrix0to1[5][9] = -1.01158375175595;
   fWeightMatrix0to1[6][9] = -0.652551586710859;
   fWeightMatrix0to1[7][9] = 0.0517822997424212;
   fWeightMatrix0to1[8][9] = 0.685969639629255;
   fWeightMatrix0to1[9][9] = 0.43265004462298;
   fWeightMatrix0to1[10][9] = 0.204635571928707;
   fWeightMatrix0to1[11][9] = -1.3105662426996;
   fWeightMatrix0to1[12][9] = 1.69028570197648;
   fWeightMatrix0to1[0][10] = -5.83356940302676;
   fWeightMatrix0to1[1][10] = 0.360242170045034;
   fWeightMatrix0to1[2][10] = 0.510138033945978;
   fWeightMatrix0to1[3][10] = 1.4408783537503;
   fWeightMatrix0to1[4][10] = 2.32937563321022;
   fWeightMatrix0to1[5][10] = 1.22021466415322;
   fWeightMatrix0to1[6][10] = 0.7427839148161;
   fWeightMatrix0to1[7][10] = -0.351832930647798;
   fWeightMatrix0to1[8][10] = 0.0843965759703525;
   fWeightMatrix0to1[9][10] = 0.594733016324607;
   fWeightMatrix0to1[10][10] = 0.427333363222432;
   fWeightMatrix0to1[11][10] = 0.21979446253076;
   fWeightMatrix0to1[12][10] = -16.5725633203477;
   fWeightMatrix0to1[0][11] = 1.2877181981288;
   fWeightMatrix0to1[1][11] = 0.295579941776907;
   fWeightMatrix0to1[2][11] = 1.47622920423438;
   fWeightMatrix0to1[3][11] = 1.40992467690135;
   fWeightMatrix0to1[4][11] = -0.614577208253051;
   fWeightMatrix0to1[5][11] = 0.929802138148075;
   fWeightMatrix0to1[6][11] = 0.594747362526324;
   fWeightMatrix0to1[7][11] = 0.449681762378342;
   fWeightMatrix0to1[8][11] = 3.3194014566515;
   fWeightMatrix0to1[9][11] = 2.00258603634173;
   fWeightMatrix0to1[10][11] = -0.0999234212402986;
   fWeightMatrix0to1[11][11] = 0.0752590819280135;
   fWeightMatrix0to1[12][11] = -0.227652939136279;
   fWeightMatrix0to1[0][12] = -0.894391215605586;
   fWeightMatrix0to1[1][12] = 57.5833340716067;
   fWeightMatrix0to1[2][12] = -14.9784561538636;
   fWeightMatrix0to1[3][12] = -0.998232997442628;
   fWeightMatrix0to1[4][12] = 15.1563162015957;
   fWeightMatrix0to1[5][12] = -13.5217189151006;
   fWeightMatrix0to1[6][12] = -20.0206340767689;
   fWeightMatrix0to1[7][12] = 29.3252751809625;
   fWeightMatrix0to1[8][12] = -17.395831920669;
   fWeightMatrix0to1[9][12] = -13.2427560989833;
   fWeightMatrix0to1[10][12] = -12.3232916195844;
   fWeightMatrix0to1[11][12] = -11.0796960608033;
   fWeightMatrix0to1[12][12] = -7.63968862874987;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.01695705960463;
   fWeightMatrix1to2[1][0] = 2.18023468341265;
   fWeightMatrix1to2[2][0] = -6.54076185327735;
   fWeightMatrix1to2[3][0] = -1.91906756527975;
   fWeightMatrix1to2[4][0] = -0.169085483689453;
   fWeightMatrix1to2[5][0] = 1.04666985617384;
   fWeightMatrix1to2[6][0] = -1.39282432587458;
   fWeightMatrix1to2[7][0] = -1.04326121824266;
   fWeightMatrix1to2[8][0] = -0.639603655154253;
   fWeightMatrix1to2[9][0] = 2.84651766909505;
   fWeightMatrix1to2[10][0] = 0.323330124202848;
   fWeightMatrix1to2[0][1] = -8.12673376274584;
   fWeightMatrix1to2[1][1] = -3.24891265143631;
   fWeightMatrix1to2[2][1] = 3.34858404179581;
   fWeightMatrix1to2[3][1] = 2.74748286883956;
   fWeightMatrix1to2[4][1] = 4.19827673068012;
   fWeightMatrix1to2[5][1] = 6.47163484453762;
   fWeightMatrix1to2[6][1] = 5.07037577513812;
   fWeightMatrix1to2[7][1] = -0.783740079064576;
   fWeightMatrix1to2[8][1] = 6.51144665971407;
   fWeightMatrix1to2[9][1] = 7.48650799667978;
   fWeightMatrix1to2[10][1] = -4.03511689403544;
   fWeightMatrix1to2[0][2] = 4.59895856492473;
   fWeightMatrix1to2[1][2] = -2.15996599903476;
   fWeightMatrix1to2[2][2] = -5.72041002717735;
   fWeightMatrix1to2[3][2] = -1.67555751184896;
   fWeightMatrix1to2[4][2] = 2.5762198830476;
   fWeightMatrix1to2[5][2] = -10.3184395100739;
   fWeightMatrix1to2[6][2] = 0.1981642370141;
   fWeightMatrix1to2[7][2] = 2.16514653553714;
   fWeightMatrix1to2[8][2] = -4.01411236385425;
   fWeightMatrix1to2[9][2] = -0.134686724888287;
   fWeightMatrix1to2[10][2] = 8.03296306599429;
   fWeightMatrix1to2[0][3] = -4.25684952635128;
   fWeightMatrix1to2[1][3] = -3.63408864454777;
   fWeightMatrix1to2[2][3] = -2.21443583133946;
   fWeightMatrix1to2[3][3] = -3.63784299660033;
   fWeightMatrix1to2[4][3] = -0.568959188548264;
   fWeightMatrix1to2[5][3] = 2.38196753798979;
   fWeightMatrix1to2[6][3] = 0.528486393809559;
   fWeightMatrix1to2[7][3] = -1.80560523244368;
   fWeightMatrix1to2[8][3] = -0.45854901869182;
   fWeightMatrix1to2[9][3] = -5.48096187653897;
   fWeightMatrix1to2[10][3] = -1.9407585131166;
   fWeightMatrix1to2[0][4] = -0.733228542516024;
   fWeightMatrix1to2[1][4] = 2.67003628401153;
   fWeightMatrix1to2[2][4] = -0.486355227868912;
   fWeightMatrix1to2[3][4] = -4.62915780358448;
   fWeightMatrix1to2[4][4] = 3.36234319147815;
   fWeightMatrix1to2[5][4] = -2.01289869483738;
   fWeightMatrix1to2[6][4] = 0.432037399976087;
   fWeightMatrix1to2[7][4] = -1.0572825991366;
   fWeightMatrix1to2[8][4] = -1.32044030586317;
   fWeightMatrix1to2[9][4] = -6.35874461012457;
   fWeightMatrix1to2[10][4] = 5.89671201128602;
   fWeightMatrix1to2[0][5] = 4.3984763131959;
   fWeightMatrix1to2[1][5] = -3.72443425261459;
   fWeightMatrix1to2[2][5] = -3.8444221840383;
   fWeightMatrix1to2[3][5] = -0.842418456920164;
   fWeightMatrix1to2[4][5] = 0.329744264179126;
   fWeightMatrix1to2[5][5] = -9.30274859225882;
   fWeightMatrix1to2[6][5] = -1.88730252108201;
   fWeightMatrix1to2[7][5] = 1.49851497862178;
   fWeightMatrix1to2[8][5] = -3.85204764076372;
   fWeightMatrix1to2[9][5] = -4.99462493534261;
   fWeightMatrix1to2[10][5] = 1.91303548715761;
   fWeightMatrix1to2[0][6] = -0.866963271583077;
   fWeightMatrix1to2[1][6] = 3.59872651540707;
   fWeightMatrix1to2[2][6] = 1.45093275875456;
   fWeightMatrix1to2[3][6] = -4.19141645069602;
   fWeightMatrix1to2[4][6] = -0.264371200968391;
   fWeightMatrix1to2[5][6] = -4.35797721178676;
   fWeightMatrix1to2[6][6] = -1.80205483737537;
   fWeightMatrix1to2[7][6] = 2.78791900227927;
   fWeightMatrix1to2[8][6] = -10.0370583257049;
   fWeightMatrix1to2[9][6] = -4.97863478572579;
   fWeightMatrix1to2[10][6] = 2.34277244471177;
   fWeightMatrix1to2[0][7] = 0.954416081041902;
   fWeightMatrix1to2[1][7] = -1.02292400767025;
   fWeightMatrix1to2[2][7] = -0.2709953239415;
   fWeightMatrix1to2[3][7] = 0.281063634159602;
   fWeightMatrix1to2[4][7] = 2.49387316384706;
   fWeightMatrix1to2[5][7] = -0.883202958056497;
   fWeightMatrix1to2[6][7] = 2.82821373003332;
   fWeightMatrix1to2[7][7] = -2.24484066252855;
   fWeightMatrix1to2[8][7] = 0.328681094621245;
   fWeightMatrix1to2[9][7] = -3.79380594580675;
   fWeightMatrix1to2[10][7] = 0.567316250857746;
   fWeightMatrix1to2[0][8] = 2.57021217816155;
   fWeightMatrix1to2[1][8] = -4.09108478150124;
   fWeightMatrix1to2[2][8] = -8.76664994697036;
   fWeightMatrix1to2[3][8] = -2.22210197022177;
   fWeightMatrix1to2[4][8] = -0.567790322255899;
   fWeightMatrix1to2[5][8] = -3.59490519424838;
   fWeightMatrix1to2[6][8] = -2.13905650976124;
   fWeightMatrix1to2[7][8] = 3.55516895505393;
   fWeightMatrix1to2[8][8] = -0.504415109326967;
   fWeightMatrix1to2[9][8] = -0.116587071437287;
   fWeightMatrix1to2[10][8] = 0.638803809886507;
   fWeightMatrix1to2[0][9] = 0.851155513875565;
   fWeightMatrix1to2[1][9] = -0.8465176990226;
   fWeightMatrix1to2[2][9] = -2.3108247305567;
   fWeightMatrix1to2[3][9] = 3.60471286678579;
   fWeightMatrix1to2[4][9] = 2.32724295839121;
   fWeightMatrix1to2[5][9] = 1.80920599092968;
   fWeightMatrix1to2[6][9] = -1.9319917464181;
   fWeightMatrix1to2[7][9] = 0.495436331108329;
   fWeightMatrix1to2[8][9] = -3.82971008659634;
   fWeightMatrix1to2[9][9] = -2.54930080603631;
   fWeightMatrix1to2[10][9] = 0.263626972439483;
   fWeightMatrix1to2[0][10] = 3.65343076058706;
   fWeightMatrix1to2[1][10] = -1.68344865404869;
   fWeightMatrix1to2[2][10] = 3.32257679880188;
   fWeightMatrix1to2[3][10] = -0.846618106671198;
   fWeightMatrix1to2[4][10] = -9.33091079460083;
   fWeightMatrix1to2[5][10] = -2.79422396424524;
   fWeightMatrix1to2[6][10] = -0.976415565182649;
   fWeightMatrix1to2[7][10] = -0.124505066644623;
   fWeightMatrix1to2[8][10] = 5.06437862874269;
   fWeightMatrix1to2[9][10] = 1.04565641129643;
   fWeightMatrix1to2[10][10] = 1.15888077161652;
   fWeightMatrix1to2[0][11] = -2.36044037291656;
   fWeightMatrix1to2[1][11] = 0.464801704617244;
   fWeightMatrix1to2[2][11] = -3.14711673845734;
   fWeightMatrix1to2[3][11] = -2.4568899384986;
   fWeightMatrix1to2[4][11] = 0.0823797193572214;
   fWeightMatrix1to2[5][11] = -2.70221807343666;
   fWeightMatrix1to2[6][11] = -13.141265452835;
   fWeightMatrix1to2[7][11] = 2.98810310938816;
   fWeightMatrix1to2[8][11] = 0.535935743911792;
   fWeightMatrix1to2[9][11] = -6.7340643940977;
   fWeightMatrix1to2[10][11] = -0.587224852921794;
   fWeightMatrix1to2[0][12] = -0.926908046428955;
   fWeightMatrix1to2[1][12] = 0.92454051987394;
   fWeightMatrix1to2[2][12] = -6.06519035423005;
   fWeightMatrix1to2[3][12] = 6.28663897048005;
   fWeightMatrix1to2[4][12] = -0.332920680665718;
   fWeightMatrix1to2[5][12] = 1.8188137584048;
   fWeightMatrix1to2[6][12] = -18.472973573344;
   fWeightMatrix1to2[7][12] = 0.132507300694051;
   fWeightMatrix1to2[8][12] = -4.75008245826169;
   fWeightMatrix1to2[9][12] = 0.32773864143741;
   fWeightMatrix1to2[10][12] = -15.2055764689454;
   fWeightMatrix1to2[0][13] = -1.09648032657886;
   fWeightMatrix1to2[1][13] = -0.394371330938519;
   fWeightMatrix1to2[2][13] = 1.15254435266246;
   fWeightMatrix1to2[3][13] = -6.70363073023756;
   fWeightMatrix1to2[4][13] = -3.87247566595429;
   fWeightMatrix1to2[5][13] = -0.760189728319449;
   fWeightMatrix1to2[6][13] = -0.996231820345037;
   fWeightMatrix1to2[7][13] = -1.77686740672863;
   fWeightMatrix1to2[8][13] = -1.93713155947684;
   fWeightMatrix1to2[9][13] = -5.93052612520253;
   fWeightMatrix1to2[10][13] = 14.5814933978366;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.78439962390066;
   fWeightMatrix2to3[0][1] = -4.85277746195626;
   fWeightMatrix2to3[0][2] = 2.74481129208499;
   fWeightMatrix2to3[0][3] = 2.93134055873949;
   fWeightMatrix2to3[0][4] = 6.69355849923351;
   fWeightMatrix2to3[0][5] = -4.33542691433915;
   fWeightMatrix2to3[0][6] = 4.26954182546591;
   fWeightMatrix2to3[0][7] = -2.97915286034128;
   fWeightMatrix2to3[0][8] = 4.23048808408921;
   fWeightMatrix2to3[0][9] = -6.92174645168421;
   fWeightMatrix2to3[0][10] = -7.40121720524617;
   fWeightMatrix2to3[0][11] = 5.704161417242;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 98;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 936;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 936;
   fMin_1[0][1] = 12;
   fMax_1[0][1] = 141;
   fMin_1[1][1] = 6;
   fMax_1[1][1] = 1653;
   fMin_1[2][1] = 6;
   fMax_1[2][1] = 1653;
   fMin_1[0][2] = 1.50743687153;
   fMax_1[0][2] = 402.325500488;
   fMin_1[1][2] = 1.60211503506;
   fMax_1[1][2] = 765.105834961;
   fMin_1[2][2] = 1.50743687153;
   fMax_1[2][2] = 765.105834961;
   fMin_1[0][3] = -0.278158336878;
   fMax_1[0][3] = 0.992744386196;
   fMin_1[1][3] = -0.331758022308;
   fMax_1[1][3] = 0.999809086323;
   fMin_1[2][3] = -0.331758022308;
   fMax_1[2][3] = 0.999809086323;
   fMin_1[0][4] = -0.225867435336;
   fMax_1[0][4] = 0.896410405636;
   fMin_1[1][4] = -0.312476426363;
   fMax_1[1][4] = 0.997139275074;
   fMin_1[2][4] = -0.312476426363;
   fMax_1[2][4] = 0.997139275074;
   fMin_1[0][5] = 8.76419734955;
   fMax_1[0][5] = 87.4012527466;
   fMin_1[1][5] = 0.839873731136;
   fMax_1[1][5] = 89.4692993164;
   fMin_1[2][5] = 0.839873731136;
   fMax_1[2][5] = 89.4692993164;
   fMin_1[0][6] = -218.365188599;
   fMax_1[0][6] = 282.412017822;
   fMin_1[1][6] = -297.246673584;
   fMax_1[1][6] = 345.846557617;
   fMin_1[2][6] = -297.246673584;
   fMax_1[2][6] = 345.846557617;
   fMin_1[0][7] = 0.221946671605;
   fMax_1[0][7] = 36.1951293945;
   fMin_1[1][7] = 0.00111616239883;
   fMax_1[1][7] = 45.5078163147;
   fMin_1[2][7] = 0.00111616239883;
   fMax_1[2][7] = 45.5078163147;
   fMin_1[0][8] = 4.10792016983;
   fMax_1[0][8] = 89.8745346069;
   fMin_1[1][8] = 0.655874788761;
   fMax_1[1][8] = 93.5002670288;
   fMin_1[2][8] = 0.655874788761;
   fMax_1[2][8] = 93.5002670288;
   fMin_1[0][9] = 2.11999750137;
   fMax_1[0][9] = 77.0618896484;
   fMin_1[1][9] = 0.189099594951;
   fMax_1[1][9] = 86.6220550537;
   fMin_1[2][9] = 0.189099594951;
   fMax_1[2][9] = 86.6220550537;
   fMin_1[0][10] = -100;
   fMax_1[0][10] = 1685.01037598;
   fMin_1[1][10] = -100;
   fMax_1[1][10] = 1687.6706543;
   fMin_1[2][10] = -100;
   fMax_1[2][10] = 1687.6706543;
   fMin_1[0][11] = 121.676742554;
   fMax_1[0][11] = 5016.7890625;
   fMin_1[1][11] = 38.8397140503;
   fMax_1[1][11] = 5093.12207031;
   fMin_1[2][11] = 38.8397140503;
   fMax_1[2][11] = 5093.12207031;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
