// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : han
Date           : Fri Apr 29 01:51:37 2022
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk1/disk02/calib3/usr/han/mc/thermal_train
Training events: 7039912
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,1252]
N200                          N200                          N200                          N200                                                            'F'    [7,1697]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [0,7.12239551544]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.248490303755,0.999783694744]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.23894277215,0.99675911665]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [1.20842897892,89.5685272217]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-318.177886963,500.895294189]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.100114114583,45.7541885376]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.672741055489,91.9385223389]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.22605907917,84.1522140503]
DWall                         DWall                         DWall                         DWall                                                           'F'    [-100.00012207,1689.87768555]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [39.0113334656,5090.8515625]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 35.5648679861884;
   fWeightMatrix0to1[1][0] = 58.1614940895743;
   fWeightMatrix0to1[2][0] = -25.0317594684472;
   fWeightMatrix0to1[3][0] = 12.1896110422898;
   fWeightMatrix0to1[4][0] = 40.1690964983507;
   fWeightMatrix0to1[5][0] = -19.6916903377017;
   fWeightMatrix0to1[6][0] = -23.7648768822;
   fWeightMatrix0to1[7][0] = 89.8092953552089;
   fWeightMatrix0to1[8][0] = -13.5146827470979;
   fWeightMatrix0to1[9][0] = -5.51747897083089;
   fWeightMatrix0to1[10][0] = -43.5914236520073;
   fWeightMatrix0to1[11][0] = 39.3215845152855;
   fWeightMatrix0to1[12][0] = -14.9281918243359;
   fWeightMatrix0to1[0][1] = -1.95245828745371;
   fWeightMatrix0to1[1][1] = -19.1395327990314;
   fWeightMatrix0to1[2][1] = 6.17026727127952;
   fWeightMatrix0to1[3][1] = 5.02072371579195;
   fWeightMatrix0to1[4][1] = -4.0106264447704;
   fWeightMatrix0to1[5][1] = -17.9235071040052;
   fWeightMatrix0to1[6][1] = 10.2803004394324;
   fWeightMatrix0to1[7][1] = -15.2857376945222;
   fWeightMatrix0to1[8][1] = -0.153319340439363;
   fWeightMatrix0to1[9][1] = 9.45368603691521;
   fWeightMatrix0to1[10][1] = -19.0068979908983;
   fWeightMatrix0to1[11][1] = -13.2119567522485;
   fWeightMatrix0to1[12][1] = -17.1797087684755;
   fWeightMatrix0to1[0][2] = -0.129892272349461;
   fWeightMatrix0to1[1][2] = 0.0320867034936888;
   fWeightMatrix0to1[2][2] = -0.048826499109345;
   fWeightMatrix0to1[3][2] = 0.305050610346723;
   fWeightMatrix0to1[4][2] = -0.972347853260384;
   fWeightMatrix0to1[5][2] = 0.32331800875143;
   fWeightMatrix0to1[6][2] = 0.503611739241651;
   fWeightMatrix0to1[7][2] = -0.691170906079134;
   fWeightMatrix0to1[8][2] = -0.446081473703118;
   fWeightMatrix0to1[9][2] = 0.539815150360691;
   fWeightMatrix0to1[10][2] = 0.126836997388278;
   fWeightMatrix0to1[11][2] = 0.755949644667811;
   fWeightMatrix0to1[12][2] = -0.980499375469855;
   fWeightMatrix0to1[0][3] = 0.576856541039565;
   fWeightMatrix0to1[1][3] = -2.97489472385923;
   fWeightMatrix0to1[2][3] = -22.0872749419808;
   fWeightMatrix0to1[3][3] = 4.35686423031361;
   fWeightMatrix0to1[4][3] = -8.04445641005196;
   fWeightMatrix0to1[5][3] = -5.4080761237677;
   fWeightMatrix0to1[6][3] = -8.66969420112573;
   fWeightMatrix0to1[7][3] = 0.864317477039141;
   fWeightMatrix0to1[8][3] = 1.43691859049356;
   fWeightMatrix0to1[9][3] = -2.6341492941295;
   fWeightMatrix0to1[10][3] = 0.118210196417528;
   fWeightMatrix0to1[11][3] = 3.87796483549005;
   fWeightMatrix0to1[12][3] = -1.48662748453442;
   fWeightMatrix0to1[0][4] = 0.0703757988609947;
   fWeightMatrix0to1[1][4] = -1.10662676932565;
   fWeightMatrix0to1[2][4] = -1.8216878223939;
   fWeightMatrix0to1[3][4] = -3.89805172141675;
   fWeightMatrix0to1[4][4] = -2.21274418428511;
   fWeightMatrix0to1[5][4] = 0.157500124877745;
   fWeightMatrix0to1[6][4] = 0.637502801105399;
   fWeightMatrix0to1[7][4] = -2.36334257161923;
   fWeightMatrix0to1[8][4] = 0.614113969033637;
   fWeightMatrix0to1[9][4] = 3.86726202024272;
   fWeightMatrix0to1[10][4] = -0.258349477105674;
   fWeightMatrix0to1[11][4] = 6.33632264162555;
   fWeightMatrix0to1[12][4] = -0.807097560151355;
   fWeightMatrix0to1[0][5] = -3.96691732262967;
   fWeightMatrix0to1[1][5] = -0.486295317009843;
   fWeightMatrix0to1[2][5] = 0.678256286693369;
   fWeightMatrix0to1[3][5] = 10.9991621732282;
   fWeightMatrix0to1[4][5] = 2.46377631243672;
   fWeightMatrix0to1[5][5] = -3.67429500596183;
   fWeightMatrix0to1[6][5] = -3.45304708891967;
   fWeightMatrix0to1[7][5] = 3.22737927429969;
   fWeightMatrix0to1[8][5] = 4.12549033105117;
   fWeightMatrix0to1[9][5] = -4.13889637290525;
   fWeightMatrix0to1[10][5] = -0.604244451113908;
   fWeightMatrix0to1[11][5] = -8.05797488738098;
   fWeightMatrix0to1[12][5] = -1.06261316628875;
   fWeightMatrix0to1[0][6] = -2.34157846311463;
   fWeightMatrix0to1[1][6] = 0.796106698966695;
   fWeightMatrix0to1[2][6] = 1.45275422167395;
   fWeightMatrix0to1[3][6] = -2.97837822651437;
   fWeightMatrix0to1[4][6] = 7.55248664112793;
   fWeightMatrix0to1[5][6] = -1.00028843326455;
   fWeightMatrix0to1[6][6] = -8.14537416867664;
   fWeightMatrix0to1[7][6] = 5.67700802037345;
   fWeightMatrix0to1[8][6] = 2.06488068074221;
   fWeightMatrix0to1[9][6] = -2.99407772142309;
   fWeightMatrix0to1[10][6] = 1.88374724220129;
   fWeightMatrix0to1[11][6] = -14.1343462689502;
   fWeightMatrix0to1[12][6] = 5.26346223722873;
   fWeightMatrix0to1[0][7] = 2.54632830772896;
   fWeightMatrix0to1[1][7] = 1.98548633120737;
   fWeightMatrix0to1[2][7] = -0.51316135460764;
   fWeightMatrix0to1[3][7] = -4.61450788541199;
   fWeightMatrix0to1[4][7] = 1.18230771727893;
   fWeightMatrix0to1[5][7] = 1.08217274559215;
   fWeightMatrix0to1[6][7] = -4.49940134311235;
   fWeightMatrix0to1[7][7] = -3.43057808521999;
   fWeightMatrix0to1[8][7] = -0.56231796943592;
   fWeightMatrix0to1[9][7] = 2.66252036143184;
   fWeightMatrix0to1[10][7] = -0.979090573611165;
   fWeightMatrix0to1[11][7] = 4.22772608567926;
   fWeightMatrix0to1[12][7] = -0.193973065032085;
   fWeightMatrix0to1[0][8] = 0.305727924250306;
   fWeightMatrix0to1[1][8] = -3.6115494576365;
   fWeightMatrix0to1[2][8] = -29.106937225558;
   fWeightMatrix0to1[3][8] = 1.56147416027879;
   fWeightMatrix0to1[4][8] = -6.27232969138129;
   fWeightMatrix0to1[5][8] = -2.18674150709607;
   fWeightMatrix0to1[6][8] = -4.36131909938516;
   fWeightMatrix0to1[7][8] = 0.849088568821996;
   fWeightMatrix0to1[8][8] = 1.50151943711697;
   fWeightMatrix0to1[9][8] = 3.39128625838668;
   fWeightMatrix0to1[10][8] = -0.369725190892811;
   fWeightMatrix0to1[11][8] = 5.36699902335154;
   fWeightMatrix0to1[12][8] = 2.547870124568;
   fWeightMatrix0to1[0][9] = -0.821210760645388;
   fWeightMatrix0to1[1][9] = 0.55493766452751;
   fWeightMatrix0to1[2][9] = -7.9389226285798;
   fWeightMatrix0to1[3][9] = -2.2061908084656;
   fWeightMatrix0to1[4][9] = -1.11791564270115;
   fWeightMatrix0to1[5][9] = -3.79384901777604;
   fWeightMatrix0to1[6][9] = -1.80450425171575;
   fWeightMatrix0to1[7][9] = 0.569415798714614;
   fWeightMatrix0to1[8][9] = 0.297595170183215;
   fWeightMatrix0to1[9][9] = 0.506008384323511;
   fWeightMatrix0to1[10][9] = 0.335390570932469;
   fWeightMatrix0to1[11][9] = -1.28474131693595;
   fWeightMatrix0to1[12][9] = -0.167148670500853;
   fWeightMatrix0to1[0][10] = 1.51350977389796;
   fWeightMatrix0to1[1][10] = -1.51334932792424;
   fWeightMatrix0to1[2][10] = 0.423983475143735;
   fWeightMatrix0to1[3][10] = -4.91596250987592;
   fWeightMatrix0to1[4][10] = 2.44270761556933;
   fWeightMatrix0to1[5][10] = 21.9063595297415;
   fWeightMatrix0to1[6][10] = -0.157533800593488;
   fWeightMatrix0to1[7][10] = -0.11890432111219;
   fWeightMatrix0to1[8][10] = 0.0413518131141321;
   fWeightMatrix0to1[9][10] = -0.172280256482215;
   fWeightMatrix0to1[10][10] = 0.771827074212674;
   fWeightMatrix0to1[11][10] = 0.497059207607412;
   fWeightMatrix0to1[12][10] = -13.6359330228046;
   fWeightMatrix0to1[0][11] = 2.0468543837685;
   fWeightMatrix0to1[1][11] = -2.89195290937788;
   fWeightMatrix0to1[2][11] = 1.68221948050018;
   fWeightMatrix0to1[3][11] = 0.277439131722407;
   fWeightMatrix0to1[4][11] = -0.872750842624377;
   fWeightMatrix0to1[5][11] = 0.421456502101739;
   fWeightMatrix0to1[6][11] = -0.516733217670002;
   fWeightMatrix0to1[7][11] = -0.00643089481258736;
   fWeightMatrix0to1[8][11] = 3.39730534665906;
   fWeightMatrix0to1[9][11] = 0.913304341033056;
   fWeightMatrix0to1[10][11] = -0.626406293341816;
   fWeightMatrix0to1[11][11] = -0.131749706542035;
   fWeightMatrix0to1[12][11] = 0.532792902796069;
   fWeightMatrix0to1[0][12] = 32.8270543303886;
   fWeightMatrix0to1[1][12] = 38.3130044603217;
   fWeightMatrix0to1[2][12] = -27.0249696445249;
   fWeightMatrix0to1[3][12] = 4.56919925504872;
   fWeightMatrix0to1[4][12] = 34.8306195925536;
   fWeightMatrix0to1[5][12] = -16.3778300886298;
   fWeightMatrix0to1[6][12] = -20.8654297534513;
   fWeightMatrix0to1[7][12] = 72.2687444615145;
   fWeightMatrix0to1[8][12] = -11.2352880889166;
   fWeightMatrix0to1[9][12] = 5.69763496720474;
   fWeightMatrix0to1[10][12] = -61.0240145911324;
   fWeightMatrix0to1[11][12] = 30.2041415520227;
   fWeightMatrix0to1[12][12] = -41.6810520956215;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.891506331517897;
   fWeightMatrix1to2[1][0] = 0.269226893132308;
   fWeightMatrix1to2[2][0] = 3.49463045129952;
   fWeightMatrix1to2[3][0] = 1.99855267822579;
   fWeightMatrix1to2[4][0] = 2.39338706520815;
   fWeightMatrix1to2[5][0] = 5.02950179350658;
   fWeightMatrix1to2[6][0] = 0.797859813640681;
   fWeightMatrix1to2[7][0] = -6.22602882804198;
   fWeightMatrix1to2[8][0] = 4.65947686701452;
   fWeightMatrix1to2[9][0] = 5.72391872403917;
   fWeightMatrix1to2[10][0] = -3.62778773495424;
   fWeightMatrix1to2[0][1] = -3.29399236430564;
   fWeightMatrix1to2[1][1] = 0.882940196127357;
   fWeightMatrix1to2[2][1] = 3.71783991974619;
   fWeightMatrix1to2[3][1] = -4.78985116095213;
   fWeightMatrix1to2[4][1] = 2.41246377648871;
   fWeightMatrix1to2[5][1] = 3.44672491046631;
   fWeightMatrix1to2[6][1] = 2.6865952082504;
   fWeightMatrix1to2[7][1] = -3.96065305654189;
   fWeightMatrix1to2[8][1] = 2.94444888000516;
   fWeightMatrix1to2[9][1] = 0.0134299715957555;
   fWeightMatrix1to2[10][1] = -2.39283438571521;
   fWeightMatrix1to2[0][2] = 5.32873275028963;
   fWeightMatrix1to2[1][2] = -2.53087631916595;
   fWeightMatrix1to2[2][2] = -0.158211014035148;
   fWeightMatrix1to2[3][2] = -0.167908111721371;
   fWeightMatrix1to2[4][2] = -7.65474214653311;
   fWeightMatrix1to2[5][2] = -1.26711809214999;
   fWeightMatrix1to2[6][2] = 1.08896332231761;
   fWeightMatrix1to2[7][2] = 5.70481254342619;
   fWeightMatrix1to2[8][2] = -7.48914715558332;
   fWeightMatrix1to2[9][2] = -1.4792423874373;
   fWeightMatrix1to2[10][2] = 6.78977509621637;
   fWeightMatrix1to2[0][3] = 1.02339086676455;
   fWeightMatrix1to2[1][3] = -0.598510354760353;
   fWeightMatrix1to2[2][3] = 8.45065766505923;
   fWeightMatrix1to2[3][3] = -1.11755652732575;
   fWeightMatrix1to2[4][3] = 2.70321831795964;
   fWeightMatrix1to2[5][3] = -0.00615797260533744;
   fWeightMatrix1to2[6][3] = 6.26645129061893;
   fWeightMatrix1to2[7][3] = 3.95000269390367;
   fWeightMatrix1to2[8][3] = -7.68507027599794;
   fWeightMatrix1to2[9][3] = 3.71675179669058;
   fWeightMatrix1to2[10][3] = -1.31731366623871;
   fWeightMatrix1to2[0][4] = 0.380785627526145;
   fWeightMatrix1to2[1][4] = -3.24322870375911;
   fWeightMatrix1to2[2][4] = 0.724712653299579;
   fWeightMatrix1to2[3][4] = -2.87664403367391;
   fWeightMatrix1to2[4][4] = 3.57498871724013;
   fWeightMatrix1to2[5][4] = 3.23965347911316;
   fWeightMatrix1to2[6][4] = 1.16889485925206;
   fWeightMatrix1to2[7][4] = -2.50194915589458;
   fWeightMatrix1to2[8][4] = 2.65323865602683;
   fWeightMatrix1to2[9][4] = 0.252255219878774;
   fWeightMatrix1to2[10][4] = -5.61471855150036;
   fWeightMatrix1to2[0][5] = -0.282736467681373;
   fWeightMatrix1to2[1][5] = 0.106057108240249;
   fWeightMatrix1to2[2][5] = -4.18359733564362;
   fWeightMatrix1to2[3][5] = 0.000647471641014153;
   fWeightMatrix1to2[4][5] = -4.15749984297017;
   fWeightMatrix1to2[5][5] = -4.12933902088434;
   fWeightMatrix1to2[6][5] = -1.98015778950127;
   fWeightMatrix1to2[7][5] = -1.05988766439567;
   fWeightMatrix1to2[8][5] = -2.43678975913882;
   fWeightMatrix1to2[9][5] = -1.00959788679567;
   fWeightMatrix1to2[10][5] = 2.34656506990101;
   fWeightMatrix1to2[0][6] = 1.49157794959862;
   fWeightMatrix1to2[1][6] = -3.86062398239206;
   fWeightMatrix1to2[2][6] = -6.94803123290398;
   fWeightMatrix1to2[3][6] = 1.47099304915026;
   fWeightMatrix1to2[4][6] = -4.37293716406625;
   fWeightMatrix1to2[5][6] = -0.305749907777359;
   fWeightMatrix1to2[6][6] = -3.60405431606064;
   fWeightMatrix1to2[7][6] = 0.244735102321681;
   fWeightMatrix1to2[8][6] = -6.49987339332892;
   fWeightMatrix1to2[9][6] = -3.71792848754366;
   fWeightMatrix1to2[10][6] = 4.25777995781832;
   fWeightMatrix1to2[0][7] = -8.08749418886405;
   fWeightMatrix1to2[1][7] = 2.964162282753;
   fWeightMatrix1to2[2][7] = 5.69078322885985;
   fWeightMatrix1to2[3][7] = 0.858793255693199;
   fWeightMatrix1to2[4][7] = 5.67588851533351;
   fWeightMatrix1to2[5][7] = 0.982597031223893;
   fWeightMatrix1to2[6][7] = -4.10991514929821;
   fWeightMatrix1to2[7][7] = 0.493984937234418;
   fWeightMatrix1to2[8][7] = 6.8063656349755;
   fWeightMatrix1to2[9][7] = -4.28597156279691;
   fWeightMatrix1to2[10][7] = -4.43128631869475;
   fWeightMatrix1to2[0][8] = 1.35230254315591;
   fWeightMatrix1to2[1][8] = -4.90748632390526;
   fWeightMatrix1to2[2][8] = -0.776695370681924;
   fWeightMatrix1to2[3][8] = 2.2511673189877;
   fWeightMatrix1to2[4][8] = -1.37588715429435;
   fWeightMatrix1to2[5][8] = 1.10629103469956;
   fWeightMatrix1to2[6][8] = 4.0422811565073;
   fWeightMatrix1to2[7][8] = 2.21066621540665;
   fWeightMatrix1to2[8][8] = -3.17660411431118;
   fWeightMatrix1to2[9][8] = 1.23769852927959;
   fWeightMatrix1to2[10][8] = 2.19128428935586;
   fWeightMatrix1to2[0][9] = 1.9826715850797;
   fWeightMatrix1to2[1][9] = -2.28154833421431;
   fWeightMatrix1to2[2][9] = 0.2798322000627;
   fWeightMatrix1to2[3][9] = 2.7198620219082;
   fWeightMatrix1to2[4][9] = 3.96163087999147;
   fWeightMatrix1to2[5][9] = 2.03090768980133;
   fWeightMatrix1to2[6][9] = -1.1972499919833;
   fWeightMatrix1to2[7][9] = 1.7753875570321;
   fWeightMatrix1to2[8][9] = 0.0170201382353778;
   fWeightMatrix1to2[9][9] = 2.75320296538394;
   fWeightMatrix1to2[10][9] = -2.67615634331058;
   fWeightMatrix1to2[0][10] = 4.63476106470121;
   fWeightMatrix1to2[1][10] = -9.5242200410749;
   fWeightMatrix1to2[2][10] = -1.12651128972448;
   fWeightMatrix1to2[3][10] = -6.63389771841757;
   fWeightMatrix1to2[4][10] = -8.10257351530983;
   fWeightMatrix1to2[5][10] = -2.99149869917436;
   fWeightMatrix1to2[6][10] = 2.12917196434376;
   fWeightMatrix1to2[7][10] = -2.06574861387899;
   fWeightMatrix1to2[8][10] = 2.53974930003266;
   fWeightMatrix1to2[9][10] = -1.05407827777974;
   fWeightMatrix1to2[10][10] = 10.3814384127842;
   fWeightMatrix1to2[0][11] = -4.03914847241006;
   fWeightMatrix1to2[1][11] = 0.514844463152983;
   fWeightMatrix1to2[2][11] = 2.97532417986664;
   fWeightMatrix1to2[3][11] = -2.70965902919265;
   fWeightMatrix1to2[4][11] = 0.472162279520546;
   fWeightMatrix1to2[5][11] = -4.75811369976512;
   fWeightMatrix1to2[6][11] = -0.513045650927775;
   fWeightMatrix1to2[7][11] = -0.37487420376155;
   fWeightMatrix1to2[8][11] = 2.77276896407428;
   fWeightMatrix1to2[9][11] = -2.11808130259936;
   fWeightMatrix1to2[10][11] = -2.97941688896664;
   fWeightMatrix1to2[0][12] = -1.46329292649934;
   fWeightMatrix1to2[1][12] = 0.359338094915308;
   fWeightMatrix1to2[2][12] = -7.12965064890409;
   fWeightMatrix1to2[3][12] = 1.71846015383349;
   fWeightMatrix1to2[4][12] = -4.33070295648715;
   fWeightMatrix1to2[5][12] = -3.89178790302771;
   fWeightMatrix1to2[6][12] = -6.78383534231299;
   fWeightMatrix1to2[7][12] = 2.81823571272162;
   fWeightMatrix1to2[8][12] = -16.2251300590722;
   fWeightMatrix1to2[9][12] = -0.87972675302978;
   fWeightMatrix1to2[10][12] = 1.23089780992049;
   fWeightMatrix1to2[0][13] = 3.64748290882704;
   fWeightMatrix1to2[1][13] = 6.7961360098622;
   fWeightMatrix1to2[2][13] = -2.9546978385283;
   fWeightMatrix1to2[3][13] = -0.726221641200651;
   fWeightMatrix1to2[4][13] = -3.17852043249724;
   fWeightMatrix1to2[5][13] = -3.08902716285758;
   fWeightMatrix1to2[6][13] = 2.8294439568789;
   fWeightMatrix1to2[7][13] = 4.08239519102312;
   fWeightMatrix1to2[8][13] = -6.67847397955811;
   fWeightMatrix1to2[9][13] = -2.65075804314026;
   fWeightMatrix1to2[10][13] = 2.65013920251795;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -4.77731365421318;
   fWeightMatrix2to3[0][1] = -4.00955127673236;
   fWeightMatrix2to3[0][2] = 1.38558046928807;
   fWeightMatrix2to3[0][3] = 3.64545990620088;
   fWeightMatrix2to3[0][4] = 7.08711163543493;
   fWeightMatrix2to3[0][5] = -15.0613650093239;
   fWeightMatrix2to3[0][6] = 2.58781301001696;
   fWeightMatrix2to3[0][7] = -1.68606372255334;
   fWeightMatrix2to3[0][8] = 4.67986231293762;
   fWeightMatrix2to3[0][9] = -6.83338182648855;
   fWeightMatrix2to3[0][10] = -2.90801473393328;
   fWeightMatrix2to3[0][11] = 0.288606057140504;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 62;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 1252;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 1252;
   fMin_1[0][1] = 11;
   fMax_1[0][1] = 90;
   fMin_1[1][1] = 7;
   fMax_1[1][1] = 1697;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 1697;
   fMin_1[0][2] = 0.133500054479;
   fMax_1[0][2] = 6.27590370178;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 7.12239551544;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 7.12239551544;
   fMin_1[0][3] = -0.23920622468;
   fMax_1[0][3] = 0.980847120285;
   fMin_1[1][3] = -0.248490303755;
   fMax_1[1][3] = 0.999783694744;
   fMin_1[2][3] = -0.248490303755;
   fMax_1[2][3] = 0.999783694744;
   fMin_1[0][4] = -0.20336535573;
   fMax_1[0][4] = 0.750204503536;
   fMin_1[1][4] = -0.23894277215;
   fMax_1[1][4] = 0.99675911665;
   fMin_1[2][4] = -0.23894277215;
   fMax_1[2][4] = 0.99675911665;
   fMin_1[0][5] = 15.232008934;
   fMax_1[0][5] = 83.8300628662;
   fMin_1[1][5] = 1.20842897892;
   fMax_1[1][5] = 89.5685272217;
   fMin_1[2][5] = 1.20842897892;
   fMax_1[2][5] = 89.5685272217;
   fMin_1[0][6] = -213.478469849;
   fMax_1[0][6] = 199.216888428;
   fMin_1[1][6] = -318.177886963;
   fMax_1[1][6] = 500.895294189;
   fMin_1[2][6] = -318.177886963;
   fMax_1[2][6] = 500.895294189;
   fMin_1[0][7] = 0.887758851051;
   fMax_1[0][7] = 38.635055542;
   fMin_1[1][7] = 0.100114114583;
   fMax_1[1][7] = 45.7541885376;
   fMin_1[2][7] = 0.100114114583;
   fMax_1[2][7] = 45.7541885376;
   fMin_1[0][8] = 6.22213983536;
   fMax_1[0][8] = 89.7552871704;
   fMin_1[1][8] = 0.672741055489;
   fMax_1[1][8] = 91.9385223389;
   fMin_1[2][8] = 0.672741055489;
   fMax_1[2][8] = 91.9385223389;
   fMin_1[0][9] = 2.76202082634;
   fMax_1[0][9] = 70.1032791138;
   fMin_1[1][9] = 0.22605907917;
   fMax_1[1][9] = 84.1522140503;
   fMin_1[2][9] = 0.22605907917;
   fMax_1[2][9] = 84.1522140503;
   fMin_1[0][10] = -100;
   fMax_1[0][10] = 1674.58984375;
   fMin_1[1][10] = -100.00012207;
   fMax_1[1][10] = 1689.87768555;
   fMin_1[2][10] = -100.00012207;
   fMax_1[2][10] = 1689.87768555;
   fMin_1[0][11] = 68.3819503784;
   fMax_1[0][11] = 5061.49560547;
   fMin_1[1][11] = 39.0113334656;
   fMax_1[1][11] = 5090.8515625;
   fMin_1[2][11] = 39.0113334656;
   fMax_1[2][11] = 5090.8515625;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
