// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : han
Date           : Mon May  2 17:27:00 2022
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk1/disk02/calib3/usr/han/mc/thermal_fv_train
Training events: 6994978
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,1251]
N200                          N200                          N200                          N200                                                            'F'    [7,1697]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [0,6.72770118713]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.248792737722,0.999783694744]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.231845259666,0.99675911665]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [1.05110609531,89.7110595703]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-317.221618652,502.098358154]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.0775836184621,44.5780067444]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.672741055489,93.2318954468]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.236216261983,84.6577606201]
DWall                         DWall                         DWall                         DWall                                                           'F'    [-100.00012207,1688.83044434]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [28.1468601227,5090.03271484]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 7.49320319195145;
   fWeightMatrix0to1[1][0] = 1.75024171812665;
   fWeightMatrix0to1[2][0] = -18.1507055891498;
   fWeightMatrix0to1[3][0] = -1.46649552851535;
   fWeightMatrix0to1[4][0] = 53.6877732785889;
   fWeightMatrix0to1[5][0] = -5.2641958420435;
   fWeightMatrix0to1[6][0] = -83.0647954544017;
   fWeightMatrix0to1[7][0] = 36.9011111097048;
   fWeightMatrix0to1[8][0] = -25.5543838286626;
   fWeightMatrix0to1[9][0] = 8.46035969574105;
   fWeightMatrix0to1[10][0] = -3.82939080524632;
   fWeightMatrix0to1[11][0] = 40.5364945661456;
   fWeightMatrix0to1[12][0] = -67.6838854735734;
   fWeightMatrix0to1[0][1] = -3.83749026147682;
   fWeightMatrix0to1[1][1] = 2.75032241097848;
   fWeightMatrix0to1[2][1] = 8.41457258010411;
   fWeightMatrix0to1[3][1] = -11.2598776240784;
   fWeightMatrix0to1[4][1] = -11.0500315302421;
   fWeightMatrix0to1[5][1] = -8.48124848638293;
   fWeightMatrix0to1[6][1] = 3.21662426556689;
   fWeightMatrix0to1[7][1] = -11.8133989767468;
   fWeightMatrix0to1[8][1] = 10.357415356922;
   fWeightMatrix0to1[9][1] = 1.75239657465529;
   fWeightMatrix0to1[10][1] = -10.707307276193;
   fWeightMatrix0to1[11][1] = -8.8130027616771;
   fWeightMatrix0to1[12][1] = 13.2093601927069;
   fWeightMatrix0to1[0][2] = -0.0504876833320104;
   fWeightMatrix0to1[1][2] = -0.0605288107522781;
   fWeightMatrix0to1[2][2] = -0.145494902926578;
   fWeightMatrix0to1[3][2] = -0.857316094606776;
   fWeightMatrix0to1[4][2] = -0.25732686890464;
   fWeightMatrix0to1[5][2] = -0.383451516993156;
   fWeightMatrix0to1[6][2] = 0.574375800923847;
   fWeightMatrix0to1[7][2] = -0.470783146672972;
   fWeightMatrix0to1[8][2] = -0.0878427440288815;
   fWeightMatrix0to1[9][2] = -0.696702112160983;
   fWeightMatrix0to1[10][2] = -1.0206775880348;
   fWeightMatrix0to1[11][2] = 0.737001450671895;
   fWeightMatrix0to1[12][2] = 0.460437986138712;
   fWeightMatrix0to1[0][3] = 11.9373530045528;
   fWeightMatrix0to1[1][3] = 2.34763024645006;
   fWeightMatrix0to1[2][3] = -23.2313405295726;
   fWeightMatrix0to1[3][3] = -2.3833184848844;
   fWeightMatrix0to1[4][3] = -2.79484041235165;
   fWeightMatrix0to1[5][3] = 3.96193330281671;
   fWeightMatrix0to1[6][3] = 2.61087865984851;
   fWeightMatrix0to1[7][3] = 1.29581092470904;
   fWeightMatrix0to1[8][3] = 0.808895053370034;
   fWeightMatrix0to1[9][3] = -4.63800936750467;
   fWeightMatrix0to1[10][3] = -5.85243672281011;
   fWeightMatrix0to1[11][3] = 4.9558409880784;
   fWeightMatrix0to1[12][3] = -1.65498399583208;
   fWeightMatrix0to1[0][4] = 2.27916619989628;
   fWeightMatrix0to1[1][4] = -0.877377433594831;
   fWeightMatrix0to1[2][4] = -1.98934120892232;
   fWeightMatrix0to1[3][4] = 1.19619345829742;
   fWeightMatrix0to1[4][4] = -1.85150773310636;
   fWeightMatrix0to1[5][4] = -5.59725896949478;
   fWeightMatrix0to1[6][4] = 2.79912157351814;
   fWeightMatrix0to1[7][4] = -0.511665182215659;
   fWeightMatrix0to1[8][4] = 1.67282380590144;
   fWeightMatrix0to1[9][4] = 0.959373159058821;
   fWeightMatrix0to1[10][4] = -0.478346962055009;
   fWeightMatrix0to1[11][4] = 6.60234458664163;
   fWeightMatrix0to1[12][4] = 1.21076845211386;
   fWeightMatrix0to1[0][5] = 0.486218760127847;
   fWeightMatrix0to1[1][5] = -5.85410854494986;
   fWeightMatrix0to1[2][5] = 2.15739901876675;
   fWeightMatrix0to1[3][5] = 2.96115368936418;
   fWeightMatrix0to1[4][5] = -4.00393272318135;
   fWeightMatrix0to1[5][5] = -1.06401035254361;
   fWeightMatrix0to1[6][5] = 0.999210768877745;
   fWeightMatrix0to1[7][5] = 10.3151368422459;
   fWeightMatrix0to1[8][5] = 2.03310084327261;
   fWeightMatrix0to1[9][5] = 2.69805558812064;
   fWeightMatrix0to1[10][5] = -11.7932976673503;
   fWeightMatrix0to1[11][5] = -7.88200530541506;
   fWeightMatrix0to1[12][5] = -4.1274943065191;
   fWeightMatrix0to1[0][6] = 4.97841598499007;
   fWeightMatrix0to1[1][6] = -5.55795322232582;
   fWeightMatrix0to1[2][6] = 2.87029252998699;
   fWeightMatrix0to1[3][6] = 9.75013169183142;
   fWeightMatrix0to1[4][6] = 3.99292308174944;
   fWeightMatrix0to1[5][6] = 5.18998465467751;
   fWeightMatrix0to1[6][6] = -1.81717760087984;
   fWeightMatrix0to1[7][6] = 7.07170648379487;
   fWeightMatrix0to1[8][6] = 3.86916880155487;
   fWeightMatrix0to1[9][6] = 3.53302274398665;
   fWeightMatrix0to1[10][6] = 0.641679035645693;
   fWeightMatrix0to1[11][6] = -16.398438465592;
   fWeightMatrix0to1[12][6] = -7.30627073205331;
   fWeightMatrix0to1[0][7] = 7.43419265086808;
   fWeightMatrix0to1[1][7] = 2.90507845653757;
   fWeightMatrix0to1[2][7] = -1.74044630909048;
   fWeightMatrix0to1[3][7] = -1.70070255466342;
   fWeightMatrix0to1[4][7] = -0.144002213963109;
   fWeightMatrix0to1[5][7] = -7.56998294123242;
   fWeightMatrix0to1[6][7] = 0.363782748904904;
   fWeightMatrix0to1[7][7] = 4.57231012900169;
   fWeightMatrix0to1[8][7] = -1.08547602976358;
   fWeightMatrix0to1[9][7] = -1.24381601418399;
   fWeightMatrix0to1[10][7] = 7.82483079740913;
   fWeightMatrix0to1[11][7] = 2.79900524462017;
   fWeightMatrix0to1[12][7] = 3.83663793729057;
   fWeightMatrix0to1[0][8] = 5.27726756691671;
   fWeightMatrix0to1[1][8] = 4.65049639837784;
   fWeightMatrix0to1[2][8] = -32.7361416899291;
   fWeightMatrix0to1[3][8] = -2.36838646976453;
   fWeightMatrix0to1[4][8] = -2.97418812201763;
   fWeightMatrix0to1[5][8] = -2.21338109467652;
   fWeightMatrix0to1[6][8] = 0.767844146110909;
   fWeightMatrix0to1[7][8] = -3.45067445702178;
   fWeightMatrix0to1[8][8] = 1.54993709399257;
   fWeightMatrix0to1[9][8] = -2.50910119302459;
   fWeightMatrix0to1[10][8] = 1.15916309917174;
   fWeightMatrix0to1[11][8] = 5.47076672398684;
   fWeightMatrix0to1[12][8] = -1.35376715928477;
   fWeightMatrix0to1[0][9] = 0.596976859395772;
   fWeightMatrix0to1[1][9] = -0.75166314871649;
   fWeightMatrix0to1[2][9] = -8.07713212007642;
   fWeightMatrix0to1[3][9] = 2.63488308383674;
   fWeightMatrix0to1[4][9] = 0.0289749016387284;
   fWeightMatrix0to1[5][9] = 1.22783596453704;
   fWeightMatrix0to1[6][9] = 0.636048494438138;
   fWeightMatrix0to1[7][9] = 2.42836544733771;
   fWeightMatrix0to1[8][9] = 0.0741688091915782;
   fWeightMatrix0to1[9][9] = 0.0183614691103497;
   fWeightMatrix0to1[10][9] = -2.55449353858405;
   fWeightMatrix0to1[11][9] = -0.501302228423795;
   fWeightMatrix0to1[12][9] = -0.0821061716592701;
   fWeightMatrix0to1[0][10] = -0.399032229770137;
   fWeightMatrix0to1[1][10] = -8.21821693537539;
   fWeightMatrix0to1[2][10] = -0.0361077986111263;
   fWeightMatrix0to1[3][10] = -16.2527505440669;
   fWeightMatrix0to1[4][10] = 1.12879383211225;
   fWeightMatrix0to1[5][10] = 1.07615839043128;
   fWeightMatrix0to1[6][10] = -0.193683257053463;
   fWeightMatrix0to1[7][10] = -0.220353311536275;
   fWeightMatrix0to1[8][10] = 1.44753033511056;
   fWeightMatrix0to1[9][10] = 6.37182398692422;
   fWeightMatrix0to1[10][10] = 10.8829138417642;
   fWeightMatrix0to1[11][10] = -0.23623338338749;
   fWeightMatrix0to1[12][10] = 0.0015379338723602;
   fWeightMatrix0to1[0][11] = 0.223985173250319;
   fWeightMatrix0to1[1][11] = -2.16587367752044;
   fWeightMatrix0to1[2][11] = 0.830823683426759;
   fWeightMatrix0to1[3][11] = 0.116247118275251;
   fWeightMatrix0to1[4][11] = -1.3764459271644;
   fWeightMatrix0to1[5][11] = -0.407819331517891;
   fWeightMatrix0to1[6][11] = -1.47194431549985;
   fWeightMatrix0to1[7][11] = -0.090552478514164;
   fWeightMatrix0to1[8][11] = 3.88654659301191;
   fWeightMatrix0to1[9][11] = -1.47474569744471;
   fWeightMatrix0to1[10][11] = -0.166004809455545;
   fWeightMatrix0to1[11][11] = -0.799338942886462;
   fWeightMatrix0to1[12][11] = 0.627053114953825;
   fWeightMatrix0to1[0][12] = 16.5849657005377;
   fWeightMatrix0to1[1][12] = -4.22613867800568;
   fWeightMatrix0to1[2][12] = -18.9210679847656;
   fWeightMatrix0to1[3][12] = -22.2321547711281;
   fWeightMatrix0to1[4][12] = 41.9168006896829;
   fWeightMatrix0to1[5][12] = -13.9564682332688;
   fWeightMatrix0to1[6][12] = -76.7376581730906;
   fWeightMatrix0to1[7][12] = 26.0630102393312;
   fWeightMatrix0to1[8][12] = -12.6592463447259;
   fWeightMatrix0to1[9][12] = 11.334505081315;
   fWeightMatrix0to1[10][12] = -2.89823630021149;
   fWeightMatrix0to1[11][12] = 35.041702482168;
   fWeightMatrix0to1[12][12] = -52.9289037856746;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -6.57963675552667;
   fWeightMatrix1to2[1][0] = 0.404186297716754;
   fWeightMatrix1to2[2][0] = 9.01119513116528;
   fWeightMatrix1to2[3][0] = 0.986891415175784;
   fWeightMatrix1to2[4][0] = 7.77445219973864;
   fWeightMatrix1to2[5][0] = 1.35380006142477;
   fWeightMatrix1to2[6][0] = -1.45901028924729;
   fWeightMatrix1to2[7][0] = 0.46237352192609;
   fWeightMatrix1to2[8][0] = -0.472632780772345;
   fWeightMatrix1to2[9][0] = 0.428849340641983;
   fWeightMatrix1to2[10][0] = -0.591504291932612;
   fWeightMatrix1to2[0][1] = 0.968261930787042;
   fWeightMatrix1to2[1][1] = 4.55440705630206;
   fWeightMatrix1to2[2][1] = -0.983250765783836;
   fWeightMatrix1to2[3][1] = -3.09424989741848;
   fWeightMatrix1to2[4][1] = 1.76559943873507;
   fWeightMatrix1to2[5][1] = 0.9979662175717;
   fWeightMatrix1to2[6][1] = 4.23431226981238;
   fWeightMatrix1to2[7][1] = 0.971976781912203;
   fWeightMatrix1to2[8][1] = -5.45668855746544;
   fWeightMatrix1to2[9][1] = -0.994173068747316;
   fWeightMatrix1to2[10][1] = -1.14765512014723;
   fWeightMatrix1to2[0][2] = 7.84837832049674;
   fWeightMatrix1to2[1][2] = -3.8944501620474;
   fWeightMatrix1to2[2][2] = -10.4109392017813;
   fWeightMatrix1to2[3][2] = -1.04594445373593;
   fWeightMatrix1to2[4][2] = -2.88055357996517;
   fWeightMatrix1to2[5][2] = -2.73440992790925;
   fWeightMatrix1to2[6][2] = -5.91193117015217;
   fWeightMatrix1to2[7][2] = -3.85294044704348;
   fWeightMatrix1to2[8][2] = -1.79311656329644;
   fWeightMatrix1to2[9][2] = -0.900033948040812;
   fWeightMatrix1to2[10][2] = 0.704216058836017;
   fWeightMatrix1to2[0][3] = -0.117770601060619;
   fWeightMatrix1to2[1][3] = -2.42469501904474;
   fWeightMatrix1to2[2][3] = 2.80863560261408;
   fWeightMatrix1to2[3][3] = -1.60007136158786;
   fWeightMatrix1to2[4][3] = -5.57968301814504;
   fWeightMatrix1to2[5][3] = 1.42426433704289;
   fWeightMatrix1to2[6][3] = 4.88838842085298;
   fWeightMatrix1to2[7][3] = 2.05138388439394;
   fWeightMatrix1to2[8][3] = 0.480979134732009;
   fWeightMatrix1to2[9][3] = 0.719441739625305;
   fWeightMatrix1to2[10][3] = -1.33102944650515;
   fWeightMatrix1to2[0][4] = 0.875594025405083;
   fWeightMatrix1to2[1][4] = 4.82310713527363;
   fWeightMatrix1to2[2][4] = 2.75698627174905;
   fWeightMatrix1to2[3][4] = -0.299602546411606;
   fWeightMatrix1to2[4][4] = 3.65172287537108;
   fWeightMatrix1to2[5][4] = 5.12159048710905;
   fWeightMatrix1to2[6][4] = -4.87003359401113;
   fWeightMatrix1to2[7][4] = -1.9672511747584;
   fWeightMatrix1to2[8][4] = 4.28424845069813;
   fWeightMatrix1to2[9][4] = -1.9901518067539;
   fWeightMatrix1to2[10][4] = 9.97419278940695;
   fWeightMatrix1to2[0][5] = -2.71549191573274;
   fWeightMatrix1to2[1][5] = -2.56623941769628;
   fWeightMatrix1to2[2][5] = 1.34340747733032;
   fWeightMatrix1to2[3][5] = -1.14319436041308;
   fWeightMatrix1to2[4][5] = -2.97444522405235;
   fWeightMatrix1to2[5][5] = -3.4655647624646;
   fWeightMatrix1to2[6][5] = 0.372252679727756;
   fWeightMatrix1to2[7][5] = 1.30517460065227;
   fWeightMatrix1to2[8][5] = -0.260880448342243;
   fWeightMatrix1to2[9][5] = -0.264392122925297;
   fWeightMatrix1to2[10][5] = 0.606422075936135;
   fWeightMatrix1to2[0][6] = 6.89693271908288;
   fWeightMatrix1to2[1][6] = 7.02675457717459;
   fWeightMatrix1to2[2][6] = -10.3681475481494;
   fWeightMatrix1to2[3][6] = -8.09685394717975;
   fWeightMatrix1to2[4][6] = -6.01022246779867;
   fWeightMatrix1to2[5][6] = -6.06875835062878;
   fWeightMatrix1to2[6][6] = -3.59914056219733;
   fWeightMatrix1to2[7][6] = -1.59437814638495;
   fWeightMatrix1to2[8][6] = -1.36824280344697;
   fWeightMatrix1to2[9][6] = -0.829776754719987;
   fWeightMatrix1to2[10][6] = -5.01830281401774;
   fWeightMatrix1to2[0][7] = -2.46265611507466;
   fWeightMatrix1to2[1][7] = 0.0755129390480859;
   fWeightMatrix1to2[2][7] = 3.79461286638663;
   fWeightMatrix1to2[3][7] = -3.69916365359884;
   fWeightMatrix1to2[4][7] = 1.62452417831426;
   fWeightMatrix1to2[5][7] = 1.69667087763679;
   fWeightMatrix1to2[6][7] = 1.1682942626857;
   fWeightMatrix1to2[7][7] = 0.470555140601371;
   fWeightMatrix1to2[8][7] = 1.73795787977904;
   fWeightMatrix1to2[9][7] = 0.0904312386976859;
   fWeightMatrix1to2[10][7] = 2.00274960910773;
   fWeightMatrix1to2[0][8] = 4.16226866772065;
   fWeightMatrix1to2[1][8] = 2.00262668151787;
   fWeightMatrix1to2[2][8] = -4.80741695169292;
   fWeightMatrix1to2[3][8] = 5.87858224637281;
   fWeightMatrix1to2[4][8] = -0.659825406766432;
   fWeightMatrix1to2[5][8] = -0.31631888540688;
   fWeightMatrix1to2[6][8] = -0.0131629734283297;
   fWeightMatrix1to2[7][8] = -1.2347822076081;
   fWeightMatrix1to2[8][8] = -1.45070996403318;
   fWeightMatrix1to2[9][8] = 2.23872481052588;
   fWeightMatrix1to2[10][8] = -1.6666333586528;
   fWeightMatrix1to2[0][9] = 2.04418339230439;
   fWeightMatrix1to2[1][9] = -0.997295948385929;
   fWeightMatrix1to2[2][9] = -2.36466999732315;
   fWeightMatrix1to2[3][9] = -2.21072062642301;
   fWeightMatrix1to2[4][9] = 1.3399957187082;
   fWeightMatrix1to2[5][9] = 2.85547675720861;
   fWeightMatrix1to2[6][9] = -4.28671353573527;
   fWeightMatrix1to2[7][9] = -5.61625121054237;
   fWeightMatrix1to2[8][9] = 0.956511089907177;
   fWeightMatrix1to2[9][9] = -0.949079262200577;
   fWeightMatrix1to2[10][9] = 5.90689091659408;
   fWeightMatrix1to2[0][10] = 2.37907436047749;
   fWeightMatrix1to2[1][10] = -1.62963328899124;
   fWeightMatrix1to2[2][10] = 0.21945101438279;
   fWeightMatrix1to2[3][10] = -2.23769830703269;
   fWeightMatrix1to2[4][10] = -4.63681819502793;
   fWeightMatrix1to2[5][10] = -1.11505865431614;
   fWeightMatrix1to2[6][10] = -12.1014666242366;
   fWeightMatrix1to2[7][10] = 1.08066266890712;
   fWeightMatrix1to2[8][10] = 5.82013761438228;
   fWeightMatrix1to2[9][10] = -2.62123460649523;
   fWeightMatrix1to2[10][10] = 2.49777017673552;
   fWeightMatrix1to2[0][11] = -4.9766696676539;
   fWeightMatrix1to2[1][11] = -0.748607557805578;
   fWeightMatrix1to2[2][11] = 7.26790110314298;
   fWeightMatrix1to2[3][11] = -0.286734741780672;
   fWeightMatrix1to2[4][11] = 1.40581230782216;
   fWeightMatrix1to2[5][11] = -7.43127721470908;
   fWeightMatrix1to2[6][11] = 1.00355093091878;
   fWeightMatrix1to2[7][11] = 1.25799755567438;
   fWeightMatrix1to2[8][11] = 2.46697297345991;
   fWeightMatrix1to2[9][11] = -0.348997958314614;
   fWeightMatrix1to2[10][11] = 3.76445272591947;
   fWeightMatrix1to2[0][12] = 4.70729088914456;
   fWeightMatrix1to2[1][12] = 2.25966495740293;
   fWeightMatrix1to2[2][12] = -9.46768504496271;
   fWeightMatrix1to2[3][12] = -1.16379755945764;
   fWeightMatrix1to2[4][12] = -2.39009929418284;
   fWeightMatrix1to2[5][12] = -2.73138048135765;
   fWeightMatrix1to2[6][12] = -4.24520651382927;
   fWeightMatrix1to2[7][12] = -4.12362224946377;
   fWeightMatrix1to2[8][12] = -3.72884028488401;
   fWeightMatrix1to2[9][12] = 2.52644891637109;
   fWeightMatrix1to2[10][12] = 1.01154526469759;
   fWeightMatrix1to2[0][13] = -2.93365002444137;
   fWeightMatrix1to2[1][13] = -8.57045467405852;
   fWeightMatrix1to2[2][13] = -0.627330805986301;
   fWeightMatrix1to2[3][13] = 0.539113058963867;
   fWeightMatrix1to2[4][13] = -1.49005802654648;
   fWeightMatrix1to2[5][13] = 0.295391291208332;
   fWeightMatrix1to2[6][13] = -1.38070019425383;
   fWeightMatrix1to2[7][13] = -1.20610186547493;
   fWeightMatrix1to2[8][13] = -6.67146685930175;
   fWeightMatrix1to2[9][13] = -1.57422944795689;
   fWeightMatrix1to2[10][13] = -0.52329449342188;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.73811801378701;
   fWeightMatrix2to3[0][1] = -4.45244872364721;
   fWeightMatrix2to3[0][2] = 2.51743843704213;
   fWeightMatrix2to3[0][3] = 2.68723990186222;
   fWeightMatrix2to3[0][4] = 8.22133193403762;
   fWeightMatrix2to3[0][5] = -14.3564195510121;
   fWeightMatrix2to3[0][6] = 9.03096805475409;
   fWeightMatrix2to3[0][7] = -9.63491672031729;
   fWeightMatrix2to3[0][8] = 5.24634412448956;
   fWeightMatrix2to3[0][9] = -3.68481376124624;
   fWeightMatrix2to3[0][10] = -2.41170252920976;
   fWeightMatrix2to3[0][11] = -2.21923426629247;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 66;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 1251;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 1251;
   fMin_1[0][1] = 11;
   fMax_1[0][1] = 93;
   fMin_1[1][1] = 7;
   fMax_1[1][1] = 1697;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 1697;
   fMin_1[0][2] = 0.0281683690846;
   fMax_1[0][2] = 5.60025501251;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.72770118713;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.72770118713;
   fMin_1[0][3] = -0.178191959858;
   fMax_1[0][3] = 0.950014710426;
   fMin_1[1][3] = -0.248792737722;
   fMax_1[1][3] = 0.999783694744;
   fMin_1[2][3] = -0.248792737722;
   fMax_1[2][3] = 0.999783694744;
   fMin_1[0][4] = -0.191331773996;
   fMax_1[0][4] = 0.538228750229;
   fMin_1[1][4] = -0.231845259666;
   fMax_1[1][4] = 0.99675911665;
   fMin_1[2][4] = -0.231845259666;
   fMax_1[2][4] = 0.99675911665;
   fMin_1[0][5] = 13.2630252838;
   fMax_1[0][5] = 82.5462875366;
   fMin_1[1][5] = 1.05110609531;
   fMax_1[1][5] = 89.7110595703;
   fMin_1[2][5] = 1.05110609531;
   fMax_1[2][5] = 89.7110595703;
   fMin_1[0][6] = -221.824172974;
   fMax_1[0][6] = 223.065826416;
   fMin_1[1][6] = -317.221618652;
   fMax_1[1][6] = 502.098358154;
   fMin_1[2][6] = -317.221618652;
   fMax_1[2][6] = 502.098358154;
   fMin_1[0][7] = 0.472609341145;
   fMax_1[0][7] = 35.8958587646;
   fMin_1[1][7] = 0.0775836184621;
   fMax_1[1][7] = 44.5780067444;
   fMin_1[2][7] = 0.0775836184621;
   fMax_1[2][7] = 44.5780067444;
   fMin_1[0][8] = 10.9460659027;
   fMax_1[0][8] = 89.1769866943;
   fMin_1[1][8] = 0.672741055489;
   fMax_1[1][8] = 93.2318954468;
   fMin_1[2][8] = 0.672741055489;
   fMax_1[2][8] = 93.2318954468;
   fMin_1[0][9] = 2.20644497871;
   fMax_1[0][9] = 72.0060043335;
   fMin_1[1][9] = 0.236216261983;
   fMax_1[1][9] = 84.6577606201;
   fMin_1[2][9] = 0.236216261983;
   fMax_1[2][9] = 84.6577606201;
   fMin_1[0][10] = -100;
   fMax_1[0][10] = 1685.49108887;
   fMin_1[1][10] = -100.00012207;
   fMax_1[1][10] = 1688.83044434;
   fMin_1[2][10] = -100.00012207;
   fMax_1[2][10] = 1688.83044434;
   fMin_1[0][11] = 150.12171936;
   fMax_1[0][11] = 4969.91455078;
   fMin_1[1][11] = 28.1468601227;
   fMax_1[1][11] = 5090.03271484;
   fMin_1[2][11] = 28.1468601227;
   fMax_1[2][11] = 5090.03271484;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
