// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : tyano
Date           : Mon May  1 23:18:52 2023
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/tyano/icrr/230428_Ntag_Kanemura_Izumiyama/mc_ana/ntag_train/execute_training
Training events: 3300662
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [7,60]
N200                          N200                          N200                          N200                                                            'F'    [7,90]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [0.425237357616,7.20642375946]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.166603058577,0.99974167347]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.159794196486,0.996130347252]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [1.12013208866,87.2107849121]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-307.129119873,362.735778809]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.321065783501,43.9493904114]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.752790689468,94.8423233032]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.104376614094,82.6740493774]
DWall                         DWall                         DWall                         DWall                                                           'F'    [0.00146484375,1663.40148926]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [27.0062446594,4927.81103516]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 3.12906506655163;
   fWeightMatrix0to1[1][0] = 17.050682447465;
   fWeightMatrix0to1[2][0] = 0.560951612247962;
   fWeightMatrix0to1[3][0] = 10.4268100158237;
   fWeightMatrix0to1[4][0] = -5.67484666005217;
   fWeightMatrix0to1[5][0] = -2.19460371217813;
   fWeightMatrix0to1[6][0] = -0.456050019209072;
   fWeightMatrix0to1[7][0] = 19.1283411865854;
   fWeightMatrix0to1[8][0] = -5.97205436608822;
   fWeightMatrix0to1[9][0] = -4.91306451064453;
   fWeightMatrix0to1[10][0] = -7.24062907321319;
   fWeightMatrix0to1[11][0] = 3.25622647054993;
   fWeightMatrix0to1[12][0] = -1.40544657846498;
   fWeightMatrix0to1[0][1] = -1.11539250867645;
   fWeightMatrix0to1[1][1] = 2.26632856706082;
   fWeightMatrix0to1[2][1] = -4.21570965340024;
   fWeightMatrix0to1[3][1] = -1.72706027802079;
   fWeightMatrix0to1[4][1] = -2.60659135177592;
   fWeightMatrix0to1[5][1] = -1.49252855962072;
   fWeightMatrix0to1[6][1] = 0.673224452496228;
   fWeightMatrix0to1[7][1] = -4.00806002753194;
   fWeightMatrix0to1[8][1] = 0.654558549269646;
   fWeightMatrix0to1[9][1] = 0.873516956235481;
   fWeightMatrix0to1[10][1] = -0.625073893656078;
   fWeightMatrix0to1[11][1] = 7.46193987844232;
   fWeightMatrix0to1[12][1] = 1.17017429346846;
   fWeightMatrix0to1[0][2] = 1.45578847378437;
   fWeightMatrix0to1[1][2] = -1.31864558242961;
   fWeightMatrix0to1[2][2] = -5.19590175369824;
   fWeightMatrix0to1[3][2] = -1.91977412549448;
   fWeightMatrix0to1[4][2] = 0.488272872904751;
   fWeightMatrix0to1[5][2] = 0.114881807871802;
   fWeightMatrix0to1[6][2] = 0.589909399186396;
   fWeightMatrix0to1[7][2] = 0.271764877034109;
   fWeightMatrix0to1[8][2] = 1.81357256124432;
   fWeightMatrix0to1[9][2] = 1.21422669367855;
   fWeightMatrix0to1[10][2] = 0.749854167912423;
   fWeightMatrix0to1[11][2] = 1.01150567547797;
   fWeightMatrix0to1[12][2] = 1.95502562127262;
   fWeightMatrix0to1[0][3] = 0.613852966112664;
   fWeightMatrix0to1[1][3] = 1.52734517865643;
   fWeightMatrix0to1[2][3] = -3.15492638624311;
   fWeightMatrix0to1[3][3] = 1.9151776833424;
   fWeightMatrix0to1[4][3] = 2.68039159590753;
   fWeightMatrix0to1[5][3] = -4.16418582765457;
   fWeightMatrix0to1[6][3] = -1.90814248873194;
   fWeightMatrix0to1[7][3] = 0.211612814297244;
   fWeightMatrix0to1[8][3] = 1.55998214821821;
   fWeightMatrix0to1[9][3] = 2.07195965401307;
   fWeightMatrix0to1[10][3] = 4.13485377415726;
   fWeightMatrix0to1[11][3] = 2.93669671371188;
   fWeightMatrix0to1[12][3] = 2.86015973791653;
   fWeightMatrix0to1[0][4] = -0.0400366956746723;
   fWeightMatrix0to1[1][4] = 0.106998314637546;
   fWeightMatrix0to1[2][4] = -0.426531770158679;
   fWeightMatrix0to1[3][4] = -0.0781099775167398;
   fWeightMatrix0to1[4][4] = -1.89510234167275;
   fWeightMatrix0to1[5][4] = -1.04069694095126;
   fWeightMatrix0to1[6][4] = 2.95582366056821;
   fWeightMatrix0to1[7][4] = -0.308648327069202;
   fWeightMatrix0to1[8][4] = 3.18434912944226;
   fWeightMatrix0to1[9][4] = -0.322427590301112;
   fWeightMatrix0to1[10][4] = 0.551083592187183;
   fWeightMatrix0to1[11][4] = 0.666893898542243;
   fWeightMatrix0to1[12][4] = 0.866311313388069;
   fWeightMatrix0to1[0][5] = 0.225092046990575;
   fWeightMatrix0to1[1][5] = 0.229394173939797;
   fWeightMatrix0to1[2][5] = -6.26132344919845;
   fWeightMatrix0to1[3][5] = -0.672266918079793;
   fWeightMatrix0to1[4][5] = -0.253691543527905;
   fWeightMatrix0to1[5][5] = -3.50072613266436;
   fWeightMatrix0to1[6][5] = -7.29926566431582;
   fWeightMatrix0to1[7][5] = -1.50407135459294;
   fWeightMatrix0to1[8][5] = 1.57870392591131;
   fWeightMatrix0to1[9][5] = 3.30020843394837;
   fWeightMatrix0to1[10][5] = 3.52100348985874;
   fWeightMatrix0to1[11][5] = 2.00655770105094;
   fWeightMatrix0to1[12][5] = -11.0284320132104;
   fWeightMatrix0to1[0][6] = 2.6133259605134;
   fWeightMatrix0to1[1][6] = -0.522856062166785;
   fWeightMatrix0to1[2][6] = 3.16083500311046;
   fWeightMatrix0to1[3][6] = 0.0209156279938831;
   fWeightMatrix0to1[4][6] = -1.17474087367661;
   fWeightMatrix0to1[5][6] = 2.86233901920121;
   fWeightMatrix0to1[6][6] = -9.65846200991661;
   fWeightMatrix0to1[7][6] = -0.390321870812682;
   fWeightMatrix0to1[8][6] = 0.40004252114441;
   fWeightMatrix0to1[9][6] = -2.71091301975394;
   fWeightMatrix0to1[10][6] = -0.655670663064156;
   fWeightMatrix0to1[11][6] = -3.02984845078334;
   fWeightMatrix0to1[12][6] = -2.54772052502416;
   fWeightMatrix0to1[0][7] = -1.38413792750834;
   fWeightMatrix0to1[1][7] = -0.5197693174736;
   fWeightMatrix0to1[2][7] = 2.84205683547147;
   fWeightMatrix0to1[3][7] = 1.32936617901964;
   fWeightMatrix0to1[4][7] = -3.86836093566141;
   fWeightMatrix0to1[5][7] = -1.64255115064189;
   fWeightMatrix0to1[6][7] = 3.03573794704368;
   fWeightMatrix0to1[7][7] = 1.00504858765995;
   fWeightMatrix0to1[8][7] = 0.63141397277636;
   fWeightMatrix0to1[9][7] = -0.231354895733619;
   fWeightMatrix0to1[10][7] = -0.27142753394489;
   fWeightMatrix0to1[11][7] = -1.59053535250711;
   fWeightMatrix0to1[12][7] = 6.52915839888302;
   fWeightMatrix0to1[0][8] = -2.70858185115606;
   fWeightMatrix0to1[1][8] = 0.692530554107639;
   fWeightMatrix0to1[2][8] = 0.646410510179006;
   fWeightMatrix0to1[3][8] = 4.62138445161762;
   fWeightMatrix0to1[4][8] = -2.04837270608031;
   fWeightMatrix0to1[5][8] = 1.73045670590634;
   fWeightMatrix0to1[6][8] = 0.0188105879259629;
   fWeightMatrix0to1[7][8] = 0.731410554436613;
   fWeightMatrix0to1[8][8] = -1.43006013681258;
   fWeightMatrix0to1[9][8] = 1.9847031881509;
   fWeightMatrix0to1[10][8] = -0.946348139363417;
   fWeightMatrix0to1[11][8] = 0.235704326188937;
   fWeightMatrix0to1[12][8] = 5.31282403010766;
   fWeightMatrix0to1[0][9] = 0.739769708626348;
   fWeightMatrix0to1[1][9] = -0.442690967729667;
   fWeightMatrix0to1[2][9] = 0.782513877173835;
   fWeightMatrix0to1[3][9] = -0.537465551365646;
   fWeightMatrix0to1[4][9] = -0.0836025193089682;
   fWeightMatrix0to1[5][9] = -0.117841362276028;
   fWeightMatrix0to1[6][9] = -1.09989770241105;
   fWeightMatrix0to1[7][9] = -0.264033471217806;
   fWeightMatrix0to1[8][9] = 1.64243027781808;
   fWeightMatrix0to1[9][9] = -0.934131804007687;
   fWeightMatrix0to1[10][9] = -1.73059771266537;
   fWeightMatrix0to1[11][9] = 1.60158021507918;
   fWeightMatrix0to1[12][9] = 1.42489097278061;
   fWeightMatrix0to1[0][10] = -4.72772542514301;
   fWeightMatrix0to1[1][10] = -1.09761847660104;
   fWeightMatrix0to1[2][10] = 1.07995965267488;
   fWeightMatrix0to1[3][10] = 1.75145771162739;
   fWeightMatrix0to1[4][10] = 0.0336318600948841;
   fWeightMatrix0to1[5][10] = 2.15641914502666;
   fWeightMatrix0to1[6][10] = 0.569675566274356;
   fWeightMatrix0to1[7][10] = -1.2314889402926;
   fWeightMatrix0to1[8][10] = -0.988749204406257;
   fWeightMatrix0to1[9][10] = -2.41877827944052;
   fWeightMatrix0to1[10][10] = 7.73462475913477;
   fWeightMatrix0to1[11][10] = 0.181873414517275;
   fWeightMatrix0to1[12][10] = -1.07288384659146;
   fWeightMatrix0to1[0][11] = -0.51469066300938;
   fWeightMatrix0to1[1][11] = -4.13997429640777;
   fWeightMatrix0to1[2][11] = -1.74055879546982;
   fWeightMatrix0to1[3][11] = 3.72005502784786;
   fWeightMatrix0to1[4][11] = -0.37656694120588;
   fWeightMatrix0to1[5][11] = -0.0342157985921152;
   fWeightMatrix0to1[6][11] = 1.10027920204757;
   fWeightMatrix0to1[7][11] = -2.40114554995019;
   fWeightMatrix0to1[8][11] = -7.48275696199847;
   fWeightMatrix0to1[9][11] = 3.64105183382217;
   fWeightMatrix0to1[10][11] = 0.425118735561553;
   fWeightMatrix0to1[11][11] = 0.907953346822957;
   fWeightMatrix0to1[12][11] = 0.656736465739474;
   fWeightMatrix0to1[0][12] = -0.745979755703851;
   fWeightMatrix0to1[1][12] = 17.4928620363878;
   fWeightMatrix0to1[2][12] = 2.57602570176604;
   fWeightMatrix0to1[3][12] = 6.97076134541679;
   fWeightMatrix0to1[4][12] = -4.01223850804185;
   fWeightMatrix0to1[5][12] = -6.60231357005475;
   fWeightMatrix0to1[6][12] = 0.346302460325121;
   fWeightMatrix0to1[7][12] = 16.0669810234756;
   fWeightMatrix0to1[8][12] = -5.17329149773471;
   fWeightMatrix0to1[9][12] = -3.88049763041778;
   fWeightMatrix0to1[10][12] = 1.00610692439495;
   fWeightMatrix0to1[11][12] = 7.84935339395975;
   fWeightMatrix0to1[12][12] = 0.177485067611083;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.51657965428566;
   fWeightMatrix1to2[1][0] = 2.24740316185902;
   fWeightMatrix1to2[2][0] = 1.85757141452312;
   fWeightMatrix1to2[3][0] = 2.27979740949168;
   fWeightMatrix1to2[4][0] = 2.90712581053836;
   fWeightMatrix1to2[5][0] = 1.81308477128797;
   fWeightMatrix1to2[6][0] = -1.84552896129345;
   fWeightMatrix1to2[7][0] = 1.6843211366691;
   fWeightMatrix1to2[8][0] = 1.51469345777995;
   fWeightMatrix1to2[9][0] = 1.68945240370951;
   fWeightMatrix1to2[10][0] = 0.23924978557352;
   fWeightMatrix1to2[0][1] = -6.83502179010994;
   fWeightMatrix1to2[1][1] = -0.0814501803760613;
   fWeightMatrix1to2[2][1] = 3.04138173051833;
   fWeightMatrix1to2[3][1] = -2.47324897696829;
   fWeightMatrix1to2[4][1] = -3.20219288689858;
   fWeightMatrix1to2[5][1] = -1.94935543799472;
   fWeightMatrix1to2[6][1] = 4.60220502462994;
   fWeightMatrix1to2[7][1] = 1.8112954654287;
   fWeightMatrix1to2[8][1] = 0.306188591218896;
   fWeightMatrix1to2[9][1] = -0.321584527675704;
   fWeightMatrix1to2[10][1] = -4.36470584122576;
   fWeightMatrix1to2[0][2] = 0.126725592728705;
   fWeightMatrix1to2[1][2] = -1.45528388366409;
   fWeightMatrix1to2[2][2] = 4.65365759178366;
   fWeightMatrix1to2[3][2] = 0.0591258376911591;
   fWeightMatrix1to2[4][2] = 0.220644367516915;
   fWeightMatrix1to2[5][2] = -2.6614470450884;
   fWeightMatrix1to2[6][2] = 2.44339640300217;
   fWeightMatrix1to2[7][2] = 1.36689746697146;
   fWeightMatrix1to2[8][2] = -0.11885427896862;
   fWeightMatrix1to2[9][2] = -0.69746731368713;
   fWeightMatrix1to2[10][2] = 1.49067308071988;
   fWeightMatrix1to2[0][3] = -1.63369198072262;
   fWeightMatrix1to2[1][3] = -3.36097795404501;
   fWeightMatrix1to2[2][3] = 1.42826064792617;
   fWeightMatrix1to2[3][3] = 0.462703194470136;
   fWeightMatrix1to2[4][3] = 1.47470624029416;
   fWeightMatrix1to2[5][3] = -2.07820115042832;
   fWeightMatrix1to2[6][3] = 0.668410862324781;
   fWeightMatrix1to2[7][3] = 1.40029281330828;
   fWeightMatrix1to2[8][3] = 5.1005417522565;
   fWeightMatrix1to2[9][3] = -0.132947109928399;
   fWeightMatrix1to2[10][3] = -4.34091832871252;
   fWeightMatrix1to2[0][4] = -0.46359774299962;
   fWeightMatrix1to2[1][4] = -0.417628420739815;
   fWeightMatrix1to2[2][4] = -3.19876029496634;
   fWeightMatrix1to2[3][4] = 1.44523444871994;
   fWeightMatrix1to2[4][4] = 0.417489746770742;
   fWeightMatrix1to2[5][4] = 4.81255532050958;
   fWeightMatrix1to2[6][4] = -4.9058127597515;
   fWeightMatrix1to2[7][4] = -0.383498007428627;
   fWeightMatrix1to2[8][4] = 0.536983037975251;
   fWeightMatrix1to2[9][4] = -0.897025842025843;
   fWeightMatrix1to2[10][4] = 0.21806854351434;
   fWeightMatrix1to2[0][5] = 1.23213344979195;
   fWeightMatrix1to2[1][5] = -1.48821534934029;
   fWeightMatrix1to2[2][5] = -2.38377659130486;
   fWeightMatrix1to2[3][5] = -0.0609136029356035;
   fWeightMatrix1to2[4][5] = -3.81717287896053;
   fWeightMatrix1to2[5][5] = 2.53876473380725;
   fWeightMatrix1to2[6][5] = -3.14904459688938;
   fWeightMatrix1to2[7][5] = 0.826491601245893;
   fWeightMatrix1to2[8][5] = -0.178666510828057;
   fWeightMatrix1to2[9][5] = -1.45567322517501;
   fWeightMatrix1to2[10][5] = 4.99409292793189;
   fWeightMatrix1to2[0][6] = -2.4037676233754;
   fWeightMatrix1to2[1][6] = 1.0524328379168;
   fWeightMatrix1to2[2][6] = -4.33532890402511;
   fWeightMatrix1to2[3][6] = -0.16124041586833;
   fWeightMatrix1to2[4][6] = -3.6020222995626;
   fWeightMatrix1to2[5][6] = 1.80033274293552;
   fWeightMatrix1to2[6][6] = -3.40372737375833;
   fWeightMatrix1to2[7][6] = -1.65367033467252;
   fWeightMatrix1to2[8][6] = -6.1296213941654;
   fWeightMatrix1to2[9][6] = -2.10345918161006;
   fWeightMatrix1to2[10][6] = 0.276353471668014;
   fWeightMatrix1to2[0][7] = 1.22478272182909;
   fWeightMatrix1to2[1][7] = -4.32976594568804;
   fWeightMatrix1to2[2][7] = 2.82505598871694;
   fWeightMatrix1to2[3][7] = -1.02455827079907;
   fWeightMatrix1to2[4][7] = 0.45387043696335;
   fWeightMatrix1to2[5][7] = -1.815041051247;
   fWeightMatrix1to2[6][7] = 3.87731935725921;
   fWeightMatrix1to2[7][7] = 1.88245653214744;
   fWeightMatrix1to2[8][7] = 2.16058487761906;
   fWeightMatrix1to2[9][7] = -0.571915752517077;
   fWeightMatrix1to2[10][7] = -1.73570972327745;
   fWeightMatrix1to2[0][8] = -0.184153169138496;
   fWeightMatrix1to2[1][8] = 0.565909266876958;
   fWeightMatrix1to2[2][8] = -1.84014451299082;
   fWeightMatrix1to2[3][8] = 0.0873283084527646;
   fWeightMatrix1to2[4][8] = 0.212801430920882;
   fWeightMatrix1to2[5][8] = 0.735437397137687;
   fWeightMatrix1to2[6][8] = -0.498443238653161;
   fWeightMatrix1to2[7][8] = 1.21658300289787;
   fWeightMatrix1to2[8][8] = -1.27453027551433;
   fWeightMatrix1to2[9][8] = -2.10579943553622;
   fWeightMatrix1to2[10][8] = -0.911456963152889;
   fWeightMatrix1to2[0][9] = 0.833598246508404;
   fWeightMatrix1to2[1][9] = -0.605396891254841;
   fWeightMatrix1to2[2][9] = -1.10035730321376;
   fWeightMatrix1to2[3][9] = 0.75353638305623;
   fWeightMatrix1to2[4][9] = -0.0431966105150271;
   fWeightMatrix1to2[5][9] = 3.13471679405122;
   fWeightMatrix1to2[6][9] = -3.25436011285969;
   fWeightMatrix1to2[7][9] = 0.544528520758909;
   fWeightMatrix1to2[8][9] = -2.05847723769006;
   fWeightMatrix1to2[9][9] = 1.53563839772409;
   fWeightMatrix1to2[10][9] = 3.32696951102753;
   fWeightMatrix1to2[0][10] = 3.76462272296659;
   fWeightMatrix1to2[1][10] = 2.76109126690669;
   fWeightMatrix1to2[2][10] = -2.0975232040074;
   fWeightMatrix1to2[3][10] = -7.33043059849436;
   fWeightMatrix1to2[4][10] = 0.818577883097274;
   fWeightMatrix1to2[5][10] = -3.21758072977121;
   fWeightMatrix1to2[6][10] = 0.423822305910358;
   fWeightMatrix1to2[7][10] = -0.492757597369035;
   fWeightMatrix1to2[8][10] = -1.59829943636844;
   fWeightMatrix1to2[9][10] = -1.0017433031437;
   fWeightMatrix1to2[10][10] = 4.17940874652022;
   fWeightMatrix1to2[0][11] = -5.36297497333342;
   fWeightMatrix1to2[1][11] = 1.1557060568936;
   fWeightMatrix1to2[2][11] = -0.553299486435286;
   fWeightMatrix1to2[3][11] = -1.29608873467023;
   fWeightMatrix1to2[4][11] = -1.04987300241786;
   fWeightMatrix1to2[5][11] = 0.429923257105386;
   fWeightMatrix1to2[6][11] = -1.14242755058621;
   fWeightMatrix1to2[7][11] = 1.25324485185578;
   fWeightMatrix1to2[8][11] = -1.8102351918001;
   fWeightMatrix1to2[9][11] = -1.46329610145225;
   fWeightMatrix1to2[10][11] = -5.14793304103262;
   fWeightMatrix1to2[0][12] = -0.58493485555702;
   fWeightMatrix1to2[1][12] = 1.2432072735891;
   fWeightMatrix1to2[2][12] = -6.56477505985677;
   fWeightMatrix1to2[3][12] = 1.91681533401641;
   fWeightMatrix1to2[4][12] = -5.80015086776979;
   fWeightMatrix1to2[5][12] = 6.07834458764169;
   fWeightMatrix1to2[6][12] = -6.32819023044765;
   fWeightMatrix1to2[7][12] = -0.479855657162846;
   fWeightMatrix1to2[8][12] = -3.54075238333775;
   fWeightMatrix1to2[9][12] = 0.701445032416498;
   fWeightMatrix1to2[10][12] = 1.36476639872046;
   fWeightMatrix1to2[0][13] = -3.05803339184837;
   fWeightMatrix1to2[1][13] = -0.991115556568205;
   fWeightMatrix1to2[2][13] = -3.39190226720642;
   fWeightMatrix1to2[3][13] = 0.746437971180621;
   fWeightMatrix1to2[4][13] = 3.82266773560166;
   fWeightMatrix1to2[5][13] = -0.0683611820532039;
   fWeightMatrix1to2[6][13] = -3.79225292346956;
   fWeightMatrix1to2[7][13] = 2.03255984584683;
   fWeightMatrix1to2[8][13] = 2.70490342109714;
   fWeightMatrix1to2[9][13] = -0.513416731796698;
   fWeightMatrix1to2[10][13] = -3.23218407932609;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -4.14885464121861;
   fWeightMatrix2to3[0][1] = -3.42622214542814;
   fWeightMatrix2to3[0][2] = 2.55844977515051;
   fWeightMatrix2to3[0][3] = 4.68408696748626;
   fWeightMatrix2to3[0][4] = 4.27934737484502;
   fWeightMatrix2to3[0][5] = -2.42642293357857;
   fWeightMatrix2to3[0][6] = 8.024693945739;
   fWeightMatrix2to3[0][7] = -3.74315308846367;
   fWeightMatrix2to3[0][8] = 2.47459291519792;
   fWeightMatrix2to3[0][9] = -1.99529081790704;
   fWeightMatrix2to3[0][10] = -1.85394776530589;
   fWeightMatrix2to3[0][11] = -2.38839138874744;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 7;
   fMax_1[0][0] = 60;
   fMin_1[1][0] = 7;
   fMax_1[1][0] = 27;
   fMin_1[2][0] = 7;
   fMax_1[2][0] = 60;
   fMin_1[0][1] = 7;
   fMax_1[0][1] = 90;
   fMin_1[1][1] = 7;
   fMax_1[1][1] = 77;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 90;
   fMin_1[0][2] = 0.816973388195;
   fMax_1[0][2] = 6.71464967728;
   fMin_1[1][2] = 0.425237357616;
   fMax_1[1][2] = 7.20642375946;
   fMin_1[2][2] = 0.425237357616;
   fMax_1[2][2] = 7.20642375946;
   fMin_1[0][3] = -0.166142508388;
   fMax_1[0][3] = 0.918897509575;
   fMin_1[1][3] = -0.166603058577;
   fMax_1[1][3] = 0.99974167347;
   fMin_1[2][3] = -0.166603058577;
   fMax_1[2][3] = 0.99974167347;
   fMin_1[0][4] = -0.151067644358;
   fMax_1[0][4] = 0.522512733936;
   fMin_1[1][4] = -0.159794196486;
   fMax_1[1][4] = 0.996130347252;
   fMin_1[2][4] = -0.159794196486;
   fMax_1[2][4] = 0.996130347252;
   fMin_1[0][5] = 22.1386394501;
   fMax_1[0][5] = 81.7210617065;
   fMin_1[1][5] = 1.12013208866;
   fMax_1[1][5] = 87.2107849121;
   fMin_1[2][5] = 1.12013208866;
   fMax_1[2][5] = 87.2107849121;
   fMin_1[0][6] = -203.753753662;
   fMax_1[0][6] = 190.378143311;
   fMin_1[1][6] = -307.129119873;
   fMax_1[1][6] = 362.735778809;
   fMin_1[2][6] = -307.129119873;
   fMax_1[2][6] = 362.735778809;
   fMin_1[0][7] = 6.11828660965;
   fMax_1[0][7] = 32.1110458374;
   fMin_1[1][7] = 0.321065783501;
   fMax_1[1][7] = 43.9493904114;
   fMin_1[2][7] = 0.321065783501;
   fMax_1[2][7] = 43.9493904114;
   fMin_1[0][8] = 14.5436553955;
   fMax_1[0][8] = 89.9186248779;
   fMin_1[1][8] = 0.752790689468;
   fMax_1[1][8] = 94.8423233032;
   fMin_1[2][8] = 0.752790689468;
   fMax_1[2][8] = 94.8423233032;
   fMin_1[0][9] = 3.8908367157;
   fMax_1[0][9] = 66.6053314209;
   fMin_1[1][9] = 0.104376614094;
   fMax_1[1][9] = 82.6740493774;
   fMin_1[2][9] = 0.104376614094;
   fMax_1[2][9] = 82.6740493774;
   fMin_1[0][10] = 0.0235595703125;
   fMax_1[0][10] = 1659.86779785;
   fMin_1[1][10] = 0.00146484375;
   fMax_1[1][10] = 1663.40148926;
   fMin_1[2][10] = 0.00146484375;
   fMax_1[2][10] = 1663.40148926;
   fMin_1[0][11] = 27.0062446594;
   fMax_1[0][11] = 4794.08007812;
   fMin_1[1][11] = 62.2535095215;
   fMax_1[1][11] = 4927.81103516;
   fMin_1[2][11] = 27.0062446594;
   fMax_1[2][11] = 4927.81103516;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
