// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : han
Date           : Sat Apr 30 09:41:18 2022
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk1/disk02/calib3/usr/han/mc/thermal_train
Training events: 9618642
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,196]
N200                          N200                          N200                          N200                                                            'F'    [7,1014]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [0.103398859501,6.84487342834]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.299421578646,0.999789893627]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.252111166716,0.996852099895]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [1.02786552906,89.2585067749]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-317.615234375,358.269958496]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.0651247948408,45.8720436096]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.703744113445,93.6049041748]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.203593954444,84.8523483276]
DWall                         DWall                         DWall                         DWall                                                           'F'    [3.28723144531,1690]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [10.4148588181,4940.83496094]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 4.145662189684;
   fWeightMatrix0to1[1][0] = 59.5460960701696;
   fWeightMatrix0to1[2][0] = 4.65134745078111;
   fWeightMatrix0to1[3][0] = 16.198216426893;
   fWeightMatrix0to1[4][0] = -6.56582634482125;
   fWeightMatrix0to1[5][0] = -9.55133752743575;
   fWeightMatrix0to1[6][0] = -17.7922760688688;
   fWeightMatrix0to1[7][0] = 35.5862061246498;
   fWeightMatrix0to1[8][0] = -4.80056253965852;
   fWeightMatrix0to1[9][0] = -25.1879259715827;
   fWeightMatrix0to1[10][0] = -8.12450645564739;
   fWeightMatrix0to1[11][0] = 15.1261701153015;
   fWeightMatrix0to1[12][0] = -10.8896075461694;
   fWeightMatrix0to1[0][1] = -4.70139452628434;
   fWeightMatrix0to1[1][1] = -7.49180314479356;
   fWeightMatrix0to1[2][1] = 13.5129028321874;
   fWeightMatrix0to1[3][1] = -6.92607416712744;
   fWeightMatrix0to1[4][1] = 31.7686587319471;
   fWeightMatrix0to1[5][1] = -13.62504431367;
   fWeightMatrix0to1[6][1] = 16.0886091660883;
   fWeightMatrix0to1[7][1] = -8.2652999233033;
   fWeightMatrix0to1[8][1] = 11.5119033751395;
   fWeightMatrix0to1[9][1] = 12.668365531203;
   fWeightMatrix0to1[10][1] = -9.54073663585284;
   fWeightMatrix0to1[11][1] = -12.9488747509039;
   fWeightMatrix0to1[12][1] = 48.0625111872464;
   fWeightMatrix0to1[0][2] = -0.145796897765431;
   fWeightMatrix0to1[1][2] = -0.490991346529601;
   fWeightMatrix0to1[2][2] = 1.45336262487449;
   fWeightMatrix0to1[3][2] = -1.00765054837506;
   fWeightMatrix0to1[4][2] = 2.23384117100023;
   fWeightMatrix0to1[5][2] = 0.332838473962238;
   fWeightMatrix0to1[6][2] = 0.0883909608463765;
   fWeightMatrix0to1[7][2] = -0.881447587182535;
   fWeightMatrix0to1[8][2] = 0.259790438226146;
   fWeightMatrix0to1[9][2] = 0.348817809051304;
   fWeightMatrix0to1[10][2] = 0.583006482261672;
   fWeightMatrix0to1[11][2] = 0.583951959997943;
   fWeightMatrix0to1[12][2] = 0.189799961680503;
   fWeightMatrix0to1[0][3] = 4.32076025966304;
   fWeightMatrix0to1[1][3] = 2.38283629856418;
   fWeightMatrix0to1[2][3] = 4.43051605887835;
   fWeightMatrix0to1[3][3] = 2.31095971975134;
   fWeightMatrix0to1[4][3] = -0.314554477357675;
   fWeightMatrix0to1[5][3] = -0.307106263272068;
   fWeightMatrix0to1[6][3] = -2.00610579968088;
   fWeightMatrix0to1[7][3] = 3.10940145363933;
   fWeightMatrix0to1[8][3] = -1.6629135854316;
   fWeightMatrix0to1[9][3] = 0.357367105075142;
   fWeightMatrix0to1[10][3] = 3.73667398063786;
   fWeightMatrix0to1[11][3] = -1.02069545560302;
   fWeightMatrix0to1[12][3] = 2.30415341797742;
   fWeightMatrix0to1[0][4] = 1.21413949315535;
   fWeightMatrix0to1[1][4] = 0.719630742826537;
   fWeightMatrix0to1[2][4] = -2.69334433218015;
   fWeightMatrix0to1[3][4] = -0.271755209398806;
   fWeightMatrix0to1[4][4] = 0.530584858646612;
   fWeightMatrix0to1[5][4] = -0.943696637494968;
   fWeightMatrix0to1[6][4] = 3.96965875733876;
   fWeightMatrix0to1[7][4] = -1.08404877215055;
   fWeightMatrix0to1[8][4] = -0.0445782160254769;
   fWeightMatrix0to1[9][4] = 1.09378881502362;
   fWeightMatrix0to1[10][4] = 1.45544527311155;
   fWeightMatrix0to1[11][4] = 1.44877068300703;
   fWeightMatrix0to1[12][4] = 1.39125448518642;
   fWeightMatrix0to1[0][5] = 5.1247433912007;
   fWeightMatrix0to1[1][5] = -0.896422557596153;
   fWeightMatrix0to1[2][5] = 14.078691054053;
   fWeightMatrix0to1[3][5] = -0.583436106178796;
   fWeightMatrix0to1[4][5] = -9.45856645617094;
   fWeightMatrix0to1[5][5] = 2.81047518076822;
   fWeightMatrix0to1[6][5] = -7.06338474752254;
   fWeightMatrix0to1[7][5] = 0.745668157442319;
   fWeightMatrix0to1[8][5] = 1.16786010082845;
   fWeightMatrix0to1[9][5] = -2.02230281620034;
   fWeightMatrix0to1[10][5] = 4.63718165699561;
   fWeightMatrix0to1[11][5] = -7.60974051079357;
   fWeightMatrix0to1[12][5] = -1.16100168751799;
   fWeightMatrix0to1[0][6] = 1.04780459094047;
   fWeightMatrix0to1[1][6] = -3.39418892120258;
   fWeightMatrix0to1[2][6] = -0.382110598555468;
   fWeightMatrix0to1[3][6] = -0.763544371639007;
   fWeightMatrix0to1[4][6] = -8.1373349146793;
   fWeightMatrix0to1[5][6] = -2.11321434267404;
   fWeightMatrix0to1[6][6] = -10.3284422555;
   fWeightMatrix0to1[7][6] = 0.780781849888772;
   fWeightMatrix0to1[8][6] = 0.492837908395797;
   fWeightMatrix0to1[9][6] = -1.06562823709819;
   fWeightMatrix0to1[10][6] = -0.525271695061084;
   fWeightMatrix0to1[11][6] = -9.78644392981344;
   fWeightMatrix0to1[12][6] = -3.19969456564049;
   fWeightMatrix0to1[0][7] = 6.00777501194474;
   fWeightMatrix0to1[1][7] = 1.02158674190436;
   fWeightMatrix0to1[2][7] = -6.33447654230458;
   fWeightMatrix0to1[3][7] = 0.458990890720939;
   fWeightMatrix0to1[4][7] = 6.91024851018809;
   fWeightMatrix0to1[5][7] = -0.976883718663561;
   fWeightMatrix0to1[6][7] = 1.35774102122027;
   fWeightMatrix0to1[7][7] = -3.54878791807318;
   fWeightMatrix0to1[8][7] = 2.05893763354994;
   fWeightMatrix0to1[9][7] = 1.80045829402991;
   fWeightMatrix0to1[10][7] = -1.23793708038679;
   fWeightMatrix0to1[11][7] = 5.25239365246923;
   fWeightMatrix0to1[12][7] = 0.745653154508211;
   fWeightMatrix0to1[0][8] = -2.33520841232279;
   fWeightMatrix0to1[1][8] = 1.78457801234285;
   fWeightMatrix0to1[2][8] = -3.22529716778048;
   fWeightMatrix0to1[3][8] = 4.20302148833452;
   fWeightMatrix0to1[4][8] = 1.24157194849626;
   fWeightMatrix0to1[5][8] = -5.317166748835;
   fWeightMatrix0to1[6][8] = 0.757841176535486;
   fWeightMatrix0to1[7][8] = 4.07416737232854;
   fWeightMatrix0to1[8][8] = 2.03201160609868;
   fWeightMatrix0to1[9][8] = 4.39680472958684;
   fWeightMatrix0to1[10][8] = -0.302926772751449;
   fWeightMatrix0to1[11][8] = 6.72451145103665;
   fWeightMatrix0to1[12][8] = 0.898118098635528;
   fWeightMatrix0to1[0][9] = 0.207300417287215;
   fWeightMatrix0to1[1][9] = -0.0311613129610315;
   fWeightMatrix0to1[2][9] = 0.115496979141822;
   fWeightMatrix0to1[3][9] = 1.73480978413166;
   fWeightMatrix0to1[4][9] = -1.37003556102098;
   fWeightMatrix0to1[5][9] = -1.28695220719675;
   fWeightMatrix0to1[6][9] = -1.53334558481688;
   fWeightMatrix0to1[7][9] = -0.807917367754183;
   fWeightMatrix0to1[8][9] = -0.746681811046693;
   fWeightMatrix0to1[9][9] = 0.0475582684940939;
   fWeightMatrix0to1[10][9] = 1.35281544580368;
   fWeightMatrix0to1[11][9] = -4.74444499045769;
   fWeightMatrix0to1[12][9] = -0.269434017527707;
   fWeightMatrix0to1[0][10] = -1.74107341861809;
   fWeightMatrix0to1[1][10] = 0.123588789613265;
   fWeightMatrix0to1[2][10] = -0.312670946297484;
   fWeightMatrix0to1[3][10] = -13.3331425415446;
   fWeightMatrix0to1[4][10] = -1.23233884451773;
   fWeightMatrix0to1[5][10] = -0.965312286729978;
   fWeightMatrix0to1[6][10] = 0.347697303377037;
   fWeightMatrix0to1[7][10] = 1.04375645491485;
   fWeightMatrix0to1[8][10] = -0.427859111816961;
   fWeightMatrix0to1[9][10] = 0.996660138408342;
   fWeightMatrix0to1[10][10] = 6.88217718645407;
   fWeightMatrix0to1[11][10] = -0.0947213072353347;
   fWeightMatrix0to1[12][10] = -0.477087690343719;
   fWeightMatrix0to1[0][11] = 0.650427569633186;
   fWeightMatrix0to1[1][11] = -1.26786953623218;
   fWeightMatrix0to1[2][11] = 0.939915196301237;
   fWeightMatrix0to1[3][11] = -0.635902722010073;
   fWeightMatrix0to1[4][11] = -0.250611510127181;
   fWeightMatrix0to1[5][11] = 0.581822713886231;
   fWeightMatrix0to1[6][11] = 0.994928572090024;
   fWeightMatrix0to1[7][11] = 1.12822266814676;
   fWeightMatrix0to1[8][11] = 8.11162173602256;
   fWeightMatrix0to1[9][11] = 5.45384762953566;
   fWeightMatrix0to1[10][11] = -0.839506263709051;
   fWeightMatrix0to1[11][11] = 0.323941707910575;
   fWeightMatrix0to1[12][11] = -0.135370923998016;
   fWeightMatrix0to1[0][12] = 4.86575436750424;
   fWeightMatrix0to1[1][12] = 50.2974231285697;
   fWeightMatrix0to1[2][12] = 10.6155790859621;
   fWeightMatrix0to1[3][12] = -5.05346934482055;
   fWeightMatrix0to1[4][12] = 23.4625742891524;
   fWeightMatrix0to1[5][12] = -25.7117463427495;
   fWeightMatrix0to1[6][12] = -0.391479670011063;
   fWeightMatrix0to1[7][12] = 21.8915478910153;
   fWeightMatrix0to1[8][12] = 12.1911343878236;
   fWeightMatrix0to1[9][12] = -9.51323770177149;
   fWeightMatrix0to1[10][12] = -12.8252145644202;
   fWeightMatrix0to1[11][12] = 4.92260160462439;
   fWeightMatrix0to1[12][12] = 37.9856856232114;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.63962930557985;
   fWeightMatrix1to2[1][0] = -1.55266529148749;
   fWeightMatrix1to2[2][0] = 3.44014976190563;
   fWeightMatrix1to2[3][0] = -0.286631706470819;
   fWeightMatrix1to2[4][0] = 3.27467618769824;
   fWeightMatrix1to2[5][0] = 4.29363344811012;
   fWeightMatrix1to2[6][0] = 2.00960945858637;
   fWeightMatrix1to2[7][0] = 0.376100618654331;
   fWeightMatrix1to2[8][0] = 1.69413217377995;
   fWeightMatrix1to2[9][0] = 2.70530244895605;
   fWeightMatrix1to2[10][0] = -5.82891633645821;
   fWeightMatrix1to2[0][1] = -4.14016811719874;
   fWeightMatrix1to2[1][1] = -1.33319979184456;
   fWeightMatrix1to2[2][1] = 4.84756576603497;
   fWeightMatrix1to2[3][1] = -0.920477721607362;
   fWeightMatrix1to2[4][1] = 2.81360167965595;
   fWeightMatrix1to2[5][1] = 1.71619548763592;
   fWeightMatrix1to2[6][1] = -4.08210138840606;
   fWeightMatrix1to2[7][1] = 1.28550628769325;
   fWeightMatrix1to2[8][1] = 0.0493273198233886;
   fWeightMatrix1to2[9][1] = 3.57947060517421;
   fWeightMatrix1to2[10][1] = -4.51065475952257;
   fWeightMatrix1to2[0][2] = -2.00933398729266;
   fWeightMatrix1to2[1][2] = 3.9159552852547;
   fWeightMatrix1to2[2][2] = 2.50930641123136;
   fWeightMatrix1to2[3][2] = 0.600087786763299;
   fWeightMatrix1to2[4][2] = -5.30537610002811;
   fWeightMatrix1to2[5][2] = -2.90552878197744;
   fWeightMatrix1to2[6][2] = 1.65224208742983;
   fWeightMatrix1to2[7][2] = -2.160472476878;
   fWeightMatrix1to2[8][2] = -4.83947917084038;
   fWeightMatrix1to2[9][2] = -1.04138648039364;
   fWeightMatrix1to2[10][2] = 0.189186810836925;
   fWeightMatrix1to2[0][3] = -7.95603294257908;
   fWeightMatrix1to2[1][3] = -4.61633136527123;
   fWeightMatrix1to2[2][3] = 5.93740766413727;
   fWeightMatrix1to2[3][3] = 0.329278320778648;
   fWeightMatrix1to2[4][3] = -4.08533193958914;
   fWeightMatrix1to2[5][3] = 1.83079592695013;
   fWeightMatrix1to2[6][3] = 1.76633027361736;
   fWeightMatrix1to2[7][3] = -5.04346720151321;
   fWeightMatrix1to2[8][3] = -7.56711020541949;
   fWeightMatrix1to2[9][3] = 1.17778875891866;
   fWeightMatrix1to2[10][3] = -1.0465402433878;
   fWeightMatrix1to2[0][4] = -0.651676979815078;
   fWeightMatrix1to2[1][4] = 3.24398456536216;
   fWeightMatrix1to2[2][4] = -0.419843423723854;
   fWeightMatrix1to2[3][4] = -0.576338944312048;
   fWeightMatrix1to2[4][4] = -7.95275873806912;
   fWeightMatrix1to2[5][4] = 2.5474926180226;
   fWeightMatrix1to2[6][4] = -0.117067146001606;
   fWeightMatrix1to2[7][4] = 0.409617824536657;
   fWeightMatrix1to2[8][4] = -6.64422623102314;
   fWeightMatrix1to2[9][4] = -8.71406926903144;
   fWeightMatrix1to2[10][4] = 3.62335205533401;
   fWeightMatrix1to2[0][5] = 5.4563187516968;
   fWeightMatrix1to2[1][5] = -5.68471332895133;
   fWeightMatrix1to2[2][5] = -6.18071691885334;
   fWeightMatrix1to2[3][5] = -6.03053771792744;
   fWeightMatrix1to2[4][5] = -3.82545336638231;
   fWeightMatrix1to2[5][5] = -0.0396708966014065;
   fWeightMatrix1to2[6][5] = 0.487162779016254;
   fWeightMatrix1to2[7][5] = -1.73571356782922;
   fWeightMatrix1to2[8][5] = -0.195425433471773;
   fWeightMatrix1to2[9][5] = -0.527724430611503;
   fWeightMatrix1to2[10][5] = 0.527581536985061;
   fWeightMatrix1to2[0][6] = -0.326714495294817;
   fWeightMatrix1to2[1][6] = -0.706449493525173;
   fWeightMatrix1to2[2][6] = -1.25560599534306;
   fWeightMatrix1to2[3][6] = 1.60312550791207;
   fWeightMatrix1to2[4][6] = -8.02402408644114;
   fWeightMatrix1to2[5][6] = 0.185565956379514;
   fWeightMatrix1to2[6][6] = -2.37919194384562;
   fWeightMatrix1to2[7][6] = -1.00083859664866;
   fWeightMatrix1to2[8][6] = -3.72346920149256;
   fWeightMatrix1to2[9][6] = -4.88490161121613;
   fWeightMatrix1to2[10][6] = 3.00878845963249;
   fWeightMatrix1to2[0][7] = -3.8223728519573;
   fWeightMatrix1to2[1][7] = 1.54334221013827;
   fWeightMatrix1to2[2][7] = 4.35377838772189;
   fWeightMatrix1to2[3][7] = -0.0146404816501296;
   fWeightMatrix1to2[4][7] = 1.57189461687712;
   fWeightMatrix1to2[5][7] = -0.0578758992605131;
   fWeightMatrix1to2[6][7] = 6.33022836504968;
   fWeightMatrix1to2[7][7] = 3.97426943290347;
   fWeightMatrix1to2[8][7] = 2.68297192868662;
   fWeightMatrix1to2[9][7] = 1.57007985823403;
   fWeightMatrix1to2[10][7] = -2.14560823403334;
   fWeightMatrix1to2[0][8] = 2.89595870511404;
   fWeightMatrix1to2[1][8] = 0.819592085753094;
   fWeightMatrix1to2[2][8] = -7.03295590954745;
   fWeightMatrix1to2[3][8] = -3.1031975614691;
   fWeightMatrix1to2[4][8] = -1.19151590162975;
   fWeightMatrix1to2[5][8] = -1.2258682722661;
   fWeightMatrix1to2[6][8] = 0.141690266369558;
   fWeightMatrix1to2[7][8] = 2.31978352880641;
   fWeightMatrix1to2[8][8] = 1.17141833893531;
   fWeightMatrix1to2[9][8] = -3.43357173589999;
   fWeightMatrix1to2[10][8] = 5.64292819574545;
   fWeightMatrix1to2[0][9] = 3.19601746014907;
   fWeightMatrix1to2[1][9] = 0.0447642706607664;
   fWeightMatrix1to2[2][9] = -3.66387976333405;
   fWeightMatrix1to2[3][9] = 0.701650006530641;
   fWeightMatrix1to2[4][9] = -1.50267874520312;
   fWeightMatrix1to2[5][9] = -0.265183348865235;
   fWeightMatrix1to2[6][9] = -1.77009263256304;
   fWeightMatrix1to2[7][9] = 2.06905516468647;
   fWeightMatrix1to2[8][9] = -0.771563385855944;
   fWeightMatrix1to2[9][9] = 0.44122405591173;
   fWeightMatrix1to2[10][9] = 1.30318406136726;
   fWeightMatrix1to2[0][10] = 0.796126806751391;
   fWeightMatrix1to2[1][10] = -0.392355376464344;
   fWeightMatrix1to2[2][10] = -1.58392854054498;
   fWeightMatrix1to2[3][10] = -3.29472140781647;
   fWeightMatrix1to2[4][10] = 2.50269339401177;
   fWeightMatrix1to2[5][10] = -15.0663030535722;
   fWeightMatrix1to2[6][10] = -0.66001773938487;
   fWeightMatrix1to2[7][10] = 0.0401589158652384;
   fWeightMatrix1to2[8][10] = 2.0047566234366;
   fWeightMatrix1to2[9][10] = -5.8238297864928;
   fWeightMatrix1to2[10][10] = 2.11981310404359;
   fWeightMatrix1to2[0][11] = 1.03035759069437;
   fWeightMatrix1to2[1][11] = -2.08666051572067;
   fWeightMatrix1to2[2][11] = -1.63409558123183;
   fWeightMatrix1to2[3][11] = 1.50439657740686;
   fWeightMatrix1to2[4][11] = 0.577846883069643;
   fWeightMatrix1to2[5][11] = -0.0188228159086793;
   fWeightMatrix1to2[6][11] = 4.12267361908184;
   fWeightMatrix1to2[7][11] = -7.58366727368465e-05;
   fWeightMatrix1to2[8][11] = 0.517803140318343;
   fWeightMatrix1to2[9][11] = 1.87208150341525;
   fWeightMatrix1to2[10][11] = -0.952164281180999;
   fWeightMatrix1to2[0][12] = -7.21385296527806;
   fWeightMatrix1to2[1][12] = 11.0602283307782;
   fWeightMatrix1to2[2][12] = 7.95100444855433;
   fWeightMatrix1to2[3][12] = -3.22652798192737;
   fWeightMatrix1to2[4][12] = -0.512730714693632;
   fWeightMatrix1to2[5][12] = -2.77719030830285;
   fWeightMatrix1to2[6][12] = -5.05758978961703;
   fWeightMatrix1to2[7][12] = 5.06830302565404;
   fWeightMatrix1to2[8][12] = -1.00313726374434;
   fWeightMatrix1to2[9][12] = -2.67936640436802;
   fWeightMatrix1to2[10][12] = 0.280497378108913;
   fWeightMatrix1to2[0][13] = -0.819402400105886;
   fWeightMatrix1to2[1][13] = -6.44490092388128;
   fWeightMatrix1to2[2][13] = 0.895029001098337;
   fWeightMatrix1to2[3][13] = 3.07089987541605;
   fWeightMatrix1to2[4][13] = -5.64609458336783;
   fWeightMatrix1to2[5][13] = -4.10044348454524;
   fWeightMatrix1to2[6][13] = 3.91734943512358;
   fWeightMatrix1to2[7][13] = -4.65545275973713;
   fWeightMatrix1to2[8][13] = -1.6822570068579;
   fWeightMatrix1to2[9][13] = -3.15707217500379;
   fWeightMatrix1to2[10][13] = 1.71114701420359;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -3.63385035359038;
   fWeightMatrix2to3[0][1] = -2.7327148414637;
   fWeightMatrix2to3[0][2] = 2.09563860810256;
   fWeightMatrix2to3[0][3] = 4.91574042510569;
   fWeightMatrix2to3[0][4] = 6.33733316228638;
   fWeightMatrix2to3[0][5] = -6.22458355908231;
   fWeightMatrix2to3[0][6] = 4.52746507670536;
   fWeightMatrix2to3[0][7] = -1.72123557931681;
   fWeightMatrix2to3[0][8] = 1.84618783015691;
   fWeightMatrix2to3[0][9] = -3.75437046911006;
   fWeightMatrix2to3[0][10] = -2.52035280476038;
   fWeightMatrix2to3[0][11] = -5.55431778624653;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 41;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 196;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 196;
   fMin_1[0][1] = 9;
   fMax_1[0][1] = 68;
   fMin_1[1][1] = 7;
   fMax_1[1][1] = 1014;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 1014;
   fMin_1[0][2] = 0.245210826397;
   fMax_1[0][2] = 6.12439680099;
   fMin_1[1][2] = 0.103398859501;
   fMax_1[1][2] = 6.84487342834;
   fMin_1[2][2] = 0.103398859501;
   fMax_1[2][2] = 6.84487342834;
   fMin_1[0][3] = -0.244485139847;
   fMax_1[0][3] = 0.992400825024;
   fMin_1[1][3] = -0.299421578646;
   fMax_1[1][3] = 0.999789893627;
   fMin_1[2][3] = -0.299421578646;
   fMax_1[2][3] = 0.999789893627;
   fMin_1[0][4] = -0.191745117307;
   fMax_1[0][4] = 0.891659021378;
   fMin_1[1][4] = -0.252111166716;
   fMax_1[1][4] = 0.996852099895;
   fMin_1[2][4] = -0.252111166716;
   fMax_1[2][4] = 0.996852099895;
   fMin_1[0][5] = 12.5447587967;
   fMax_1[0][5] = 88.3537368774;
   fMin_1[1][5] = 1.02786552906;
   fMax_1[1][5] = 89.2585067749;
   fMin_1[2][5] = 1.02786552906;
   fMax_1[2][5] = 89.2585067749;
   fMin_1[0][6] = -258.513397217;
   fMax_1[0][6] = 268.684631348;
   fMin_1[1][6] = -317.615234375;
   fMax_1[1][6] = 358.269958496;
   fMin_1[2][6] = -317.615234375;
   fMax_1[2][6] = 358.269958496;
   fMin_1[0][7] = 1.68883252144;
   fMax_1[0][7] = 38.5771255493;
   fMin_1[1][7] = 0.0651247948408;
   fMax_1[1][7] = 45.8720436096;
   fMin_1[2][7] = 0.0651247948408;
   fMax_1[2][7] = 45.8720436096;
   fMin_1[0][8] = 4.10679864883;
   fMax_1[0][8] = 90.6342086792;
   fMin_1[1][8] = 0.703744113445;
   fMax_1[1][8] = 93.6049041748;
   fMin_1[2][8] = 0.703744113445;
   fMax_1[2][8] = 93.6049041748;
   fMin_1[0][9] = 1.84081149101;
   fMax_1[0][9] = 71.4060745239;
   fMin_1[1][9] = 0.203593954444;
   fMax_1[1][9] = 84.8523483276;
   fMin_1[2][9] = 0.203593954444;
   fMax_1[2][9] = 84.8523483276;
   fMin_1[0][10] = 3.28723144531;
   fMax_1[0][10] = 1690;
   fMin_1[1][10] = 3.28723144531;
   fMax_1[1][10] = 1690;
   fMin_1[2][10] = 3.28723144531;
   fMax_1[2][10] = 1690;
   fMin_1[0][11] = 10.4148588181;
   fMax_1[0][11] = 4859.69189453;
   fMin_1[1][11] = 11.4100618362;
   fMax_1[1][11] = 4940.83496094;
   fMin_1[2][11] = 10.4148588181;
   fMax_1[2][11] = 4940.83496094;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
