// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : han
Date           : Fri Apr 29 04:59:39 2022
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk1/disk02/calib3/usr/han/mc/thermal_train
Training events: 9641931
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [5,163]
N200                          N200                          N200                          N200                                                            'F'    [7,968]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [0.332703500986,7.23214197159]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.199142292142,0.999812364578]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.186490550637,0.997185647488]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [1.25850713253,89.9220733643]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-329.565704346,361.686950684]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.135172307491,44.5247306824]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.698130011559,93.416595459]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.131463989615,86.5177764893]
DWall                         DWall                         DWall                         DWall                                                           'F'    [0.00048828125,1677.82714844]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [23.5629196167,4943.76708984]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 7.70840773059654;
   fWeightMatrix0to1[1][0] = 54.4944594937434;
   fWeightMatrix0to1[2][0] = 13.0869920679756;
   fWeightMatrix0to1[3][0] = 14.4481511420501;
   fWeightMatrix0to1[4][0] = -8.16759436997582;
   fWeightMatrix0to1[5][0] = -16.8531974587411;
   fWeightMatrix0to1[6][0] = -7.84781070910364;
   fWeightMatrix0to1[7][0] = 39.2042189607772;
   fWeightMatrix0to1[8][0] = -3.67024715444058;
   fWeightMatrix0to1[9][0] = -40.9263895269794;
   fWeightMatrix0to1[10][0] = -8.11257238528121;
   fWeightMatrix0to1[11][0] = 4.83180726422113;
   fWeightMatrix0to1[12][0] = -12.8194684171812;
   fWeightMatrix0to1[0][1] = -3.69682200228551;
   fWeightMatrix0to1[1][1] = -2.82444048491429;
   fWeightMatrix0to1[2][1] = -44.843944851562;
   fWeightMatrix0to1[3][1] = 0.04189131644321;
   fWeightMatrix0to1[4][1] = 19.9387361439369;
   fWeightMatrix0to1[5][1] = 4.09918047362121;
   fWeightMatrix0to1[6][1] = 3.27376422515107;
   fWeightMatrix0to1[7][1] = -17.4921306900871;
   fWeightMatrix0to1[8][1] = 8.48807892844131;
   fWeightMatrix0to1[9][1] = 18.9446668596034;
   fWeightMatrix0to1[10][1] = 20.2028723269223;
   fWeightMatrix0to1[11][1] = 23.2286900904445;
   fWeightMatrix0to1[12][1] = 26.4368620258399;
   fWeightMatrix0to1[0][2] = 0.400380236176561;
   fWeightMatrix0to1[1][2] = -0.455033204160353;
   fWeightMatrix0to1[2][2] = -1.65253170240418;
   fWeightMatrix0to1[3][2] = -1.48188832773461;
   fWeightMatrix0to1[4][2] = 1.12894929033267;
   fWeightMatrix0to1[5][2] = 0.382736567881179;
   fWeightMatrix0to1[6][2] = 0.00817104658612675;
   fWeightMatrix0to1[7][2] = -0.923968107865129;
   fWeightMatrix0to1[8][2] = 0.0128307922541535;
   fWeightMatrix0to1[9][2] = 1.20141228303096;
   fWeightMatrix0to1[10][2] = -2.46597466993713;
   fWeightMatrix0to1[11][2] = 1.7162464159521;
   fWeightMatrix0to1[12][2] = 0.260085807680178;
   fWeightMatrix0to1[0][3] = 7.13545616032825;
   fWeightMatrix0to1[1][3] = 0.870860270278961;
   fWeightMatrix0to1[2][3] = -3.11087055899876;
   fWeightMatrix0to1[3][3] = 3.42494756360216;
   fWeightMatrix0to1[4][3] = 4.77943694375654;
   fWeightMatrix0to1[5][3] = 5.95556382933823;
   fWeightMatrix0to1[6][3] = -3.28333046868358;
   fWeightMatrix0to1[7][3] = 0.671251581255766;
   fWeightMatrix0to1[8][3] = -0.022217361410723;
   fWeightMatrix0to1[9][3] = -1.32554358949856;
   fWeightMatrix0to1[10][3] = -3.37888186607206;
   fWeightMatrix0to1[11][3] = 2.22180274043212;
   fWeightMatrix0to1[12][3] = -4.10527858797015;
   fWeightMatrix0to1[0][4] = -0.253985083022645;
   fWeightMatrix0to1[1][4] = -1.99970813910911;
   fWeightMatrix0to1[2][4] = -1.40494847922602;
   fWeightMatrix0to1[3][4] = -0.831745682670606;
   fWeightMatrix0to1[4][4] = 0.36725933315446;
   fWeightMatrix0to1[5][4] = 0.283077979654257;
   fWeightMatrix0to1[6][4] = 0.718538520130253;
   fWeightMatrix0to1[7][4] = -0.865223014408851;
   fWeightMatrix0to1[8][4] = -0.79705155256524;
   fWeightMatrix0to1[9][4] = -4.20697061024136;
   fWeightMatrix0to1[10][4] = -0.317568369433549;
   fWeightMatrix0to1[11][4] = -2.53773647446535;
   fWeightMatrix0to1[12][4] = 1.77361903732576;
   fWeightMatrix0to1[0][5] = 7.15441500383846;
   fWeightMatrix0to1[1][5] = -0.508165583123027;
   fWeightMatrix0to1[2][5] = -3.76190545455745;
   fWeightMatrix0to1[3][5] = 3.86152076614927;
   fWeightMatrix0to1[4][5] = -7.24703657332265;
   fWeightMatrix0to1[5][5] = 2.86904020673437;
   fWeightMatrix0to1[6][5] = -0.770813210543293;
   fWeightMatrix0to1[7][5] = -4.94992014152067;
   fWeightMatrix0to1[8][5] = 1.99626231078218;
   fWeightMatrix0to1[9][5] = 1.3352818863618;
   fWeightMatrix0to1[10][5] = -1.48487106857683;
   fWeightMatrix0to1[11][5] = 1.64907971843075;
   fWeightMatrix0to1[12][5] = -11.8573124569993;
   fWeightMatrix0to1[0][6] = 1.10273646164283;
   fWeightMatrix0to1[1][6] = 0.0951077503444971;
   fWeightMatrix0to1[2][6] = 1.4263983198614;
   fWeightMatrix0to1[3][6] = -1.38500017414109;
   fWeightMatrix0to1[4][6] = -0.26942921376381;
   fWeightMatrix0to1[5][6] = -0.174937442669734;
   fWeightMatrix0to1[6][6] = -0.0822591931721777;
   fWeightMatrix0to1[7][6] = 1.40344982045543;
   fWeightMatrix0to1[8][6] = -0.148549922156253;
   fWeightMatrix0to1[9][6] = 3.96987833794862;
   fWeightMatrix0to1[10][6] = 3.81651624530622;
   fWeightMatrix0to1[11][6] = -1.22937279212526;
   fWeightMatrix0to1[12][6] = -10.6398841618498;
   fWeightMatrix0to1[0][7] = 2.70317367744877;
   fWeightMatrix0to1[1][7] = 0.300795264608119;
   fWeightMatrix0to1[2][7] = 1.54881167006438;
   fWeightMatrix0to1[3][7] = 0.836174192347469;
   fWeightMatrix0to1[4][7] = 4.14907713127746;
   fWeightMatrix0to1[5][7] = 0.770133112241915;
   fWeightMatrix0to1[6][7] = 4.68770748263251;
   fWeightMatrix0to1[7][7] = -1.44789599719694;
   fWeightMatrix0to1[8][7] = 0.267474926076594;
   fWeightMatrix0to1[9][7] = -2.61318467675842;
   fWeightMatrix0to1[10][7] = 0.0328733284296108;
   fWeightMatrix0to1[11][7] = -0.80598913342322;
   fWeightMatrix0to1[12][7] = 4.88087120461553;
   fWeightMatrix0to1[0][8] = -0.389244100469579;
   fWeightMatrix0to1[1][8] = 0.912942894931102;
   fWeightMatrix0to1[2][8] = -1.96508853365251;
   fWeightMatrix0to1[3][8] = 3.28234127271012;
   fWeightMatrix0to1[4][8] = 4.47839517062735;
   fWeightMatrix0to1[5][8] = 1.26442110068676;
   fWeightMatrix0to1[6][8] = 3.35220348964191;
   fWeightMatrix0to1[7][8] = 3.05616149153823;
   fWeightMatrix0to1[8][8] = 0.436677668911494;
   fWeightMatrix0to1[9][8] = -0.984639140401282;
   fWeightMatrix0to1[10][8] = -4.25336217887213;
   fWeightMatrix0to1[11][8] = 0.390520720592605;
   fWeightMatrix0to1[12][8] = -0.446779526046341;
   fWeightMatrix0to1[0][9] = 0.316187466660716;
   fWeightMatrix0to1[1][9] = 0.598344321429734;
   fWeightMatrix0to1[2][9] = -0.476690802103082;
   fWeightMatrix0to1[3][9] = -1.26811047162325;
   fWeightMatrix0to1[4][9] = 2.5568291516981;
   fWeightMatrix0to1[5][9] = -0.0615592540865003;
   fWeightMatrix0to1[6][9] = 0.361678672137158;
   fWeightMatrix0to1[7][9] = 0.805980494593741;
   fWeightMatrix0to1[8][9] = -1.2632570869513;
   fWeightMatrix0to1[9][9] = 1.82982975789994;
   fWeightMatrix0to1[10][9] = -0.0810898252190065;
   fWeightMatrix0to1[11][9] = 0.194103707055001;
   fWeightMatrix0to1[12][9] = -0.970461761485293;
   fWeightMatrix0to1[0][10] = -1.29796285800712;
   fWeightMatrix0to1[1][10] = -0.635690131967237;
   fWeightMatrix0to1[2][10] = -0.478910201450236;
   fWeightMatrix0to1[3][10] = 3.0067895753491;
   fWeightMatrix0to1[4][10] = -0.882683229544962;
   fWeightMatrix0to1[5][10] = 4.0163911765112;
   fWeightMatrix0to1[6][10] = 0.485719092327219;
   fWeightMatrix0to1[7][10] = 1.07170804721858;
   fWeightMatrix0to1[8][10] = -2.21809600730956;
   fWeightMatrix0to1[9][10] = 0.382725808397522;
   fWeightMatrix0to1[10][10] = 0.139396395376527;
   fWeightMatrix0to1[11][10] = -4.22103768550196;
   fWeightMatrix0to1[12][10] = 0.017096330195917;
   fWeightMatrix0to1[0][11] = 0.895775773635883;
   fWeightMatrix0to1[1][11] = -2.80121397933926;
   fWeightMatrix0to1[2][11] = -0.679622342321508;
   fWeightMatrix0to1[3][11] = 8.39019512285002;
   fWeightMatrix0to1[4][11] = 0.0208990309059377;
   fWeightMatrix0to1[5][11] = -0.950853597761863;
   fWeightMatrix0to1[6][11] = -0.790583341897338;
   fWeightMatrix0to1[7][11] = -1.44788795842936;
   fWeightMatrix0to1[8][11] = 10.1427810760915;
   fWeightMatrix0to1[9][11] = 3.34284865542311;
   fWeightMatrix0to1[10][11] = -0.516903659481573;
   fWeightMatrix0to1[11][11] = -1.15234758199996;
   fWeightMatrix0to1[12][11] = 1.00539103506852;
   fWeightMatrix0to1[0][12] = 7.75539308018085;
   fWeightMatrix0to1[1][12] = 48.1143088423383;
   fWeightMatrix0to1[2][12] = -31.0226199944743;
   fWeightMatrix0to1[3][12] = 9.89804488751201;
   fWeightMatrix0to1[4][12] = 10.6323422177312;
   fWeightMatrix0to1[5][12] = -7.03493414944245;
   fWeightMatrix0to1[6][12] = -5.89247310259531;
   fWeightMatrix0to1[7][12] = 19.8627675777383;
   fWeightMatrix0to1[8][12] = 11.3218044426023;
   fWeightMatrix0to1[9][12] = -25.0827906971057;
   fWeightMatrix0to1[10][12] = 11.7487470408464;
   fWeightMatrix0to1[11][12] = 21.3664726248361;
   fWeightMatrix0to1[12][12] = 13.3491992187723;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.57140666589854;
   fWeightMatrix1to2[1][0] = -0.926063165434689;
   fWeightMatrix1to2[2][0] = 4.52266299515926;
   fWeightMatrix1to2[3][0] = -0.648005628264435;
   fWeightMatrix1to2[4][0] = 1.8229269196474;
   fWeightMatrix1to2[5][0] = -3.22935791723539;
   fWeightMatrix1to2[6][0] = -1.13600181829095;
   fWeightMatrix1to2[7][0] = 2.82969198281873;
   fWeightMatrix1to2[8][0] = 5.94198389404154;
   fWeightMatrix1to2[9][0] = 0.563201734616907;
   fWeightMatrix1to2[10][0] = -3.33337247107619;
   fWeightMatrix1to2[0][1] = -5.55963911988946;
   fWeightMatrix1to2[1][1] = 0.0963087006228753;
   fWeightMatrix1to2[2][1] = 4.39639681947808;
   fWeightMatrix1to2[3][1] = -7.19515010712324;
   fWeightMatrix1to2[4][1] = -1.82707609985265;
   fWeightMatrix1to2[5][1] = 0.495988377724755;
   fWeightMatrix1to2[6][1] = -3.83657279233497;
   fWeightMatrix1to2[7][1] = 1.27901224254089;
   fWeightMatrix1to2[8][1] = 1.19278523311706;
   fWeightMatrix1to2[9][1] = -10.371754594557;
   fWeightMatrix1to2[10][1] = -6.65155803057893;
   fWeightMatrix1to2[0][2] = 10.9609337905027;
   fWeightMatrix1to2[1][2] = 0.121643145328026;
   fWeightMatrix1to2[2][2] = 0.650124879959665;
   fWeightMatrix1to2[3][2] = 0.842856752874462;
   fWeightMatrix1to2[4][2] = 1.94303204530356;
   fWeightMatrix1to2[5][2] = -3.44931407902596;
   fWeightMatrix1to2[6][2] = 10.4322579435796;
   fWeightMatrix1to2[7][2] = -2.02097959719395;
   fWeightMatrix1to2[8][2] = 2.21928044500781;
   fWeightMatrix1to2[9][2] = 0.887434376202109;
   fWeightMatrix1to2[10][2] = 1.01246488354627;
   fWeightMatrix1to2[0][3] = -1.7345373381853;
   fWeightMatrix1to2[1][3] = -2.47266767617381;
   fWeightMatrix1to2[2][3] = 2.34671300427969;
   fWeightMatrix1to2[3][3] = 2.7154767265571;
   fWeightMatrix1to2[4][3] = 0.00832313079168989;
   fWeightMatrix1to2[5][3] = -0.554648603503183;
   fWeightMatrix1to2[6][3] = 0.14778222293773;
   fWeightMatrix1to2[7][3] = 0.947641071184426;
   fWeightMatrix1to2[8][3] = 0.0858904313414907;
   fWeightMatrix1to2[9][3] = -2.15172035630329;
   fWeightMatrix1to2[10][3] = -3.83592382553777;
   fWeightMatrix1to2[0][4] = -1.44968624541184;
   fWeightMatrix1to2[1][4] = 1.55397455749234;
   fWeightMatrix1to2[2][4] = -6.64318070611278;
   fWeightMatrix1to2[3][4] = -0.78059713533546;
   fWeightMatrix1to2[4][4] = -5.48566943218352;
   fWeightMatrix1to2[5][4] = 10.5446566520897;
   fWeightMatrix1to2[6][4] = -6.10649450175163;
   fWeightMatrix1to2[7][4] = -0.880397780136962;
   fWeightMatrix1to2[8][4] = -10.6383868840103;
   fWeightMatrix1to2[9][4] = 0.17928032678496;
   fWeightMatrix1to2[10][4] = 1.89452183396596;
   fWeightMatrix1to2[0][5] = 2.03007849607546;
   fWeightMatrix1to2[1][5] = -2.7884242154572;
   fWeightMatrix1to2[2][5] = -1.62450775370385;
   fWeightMatrix1to2[3][5] = 3.24681305872403;
   fWeightMatrix1to2[4][5] = -0.717563812154473;
   fWeightMatrix1to2[5][5] = 1.76097918847002;
   fWeightMatrix1to2[6][5] = -1.19261295202292;
   fWeightMatrix1to2[7][5] = 7.04259178605156;
   fWeightMatrix1to2[8][5] = 1.05264318787842;
   fWeightMatrix1to2[9][5] = -1.23127627860316;
   fWeightMatrix1to2[10][5] = 1.28649584561343;
   fWeightMatrix1to2[0][6] = 1.56102792397285;
   fWeightMatrix1to2[1][6] = 0.268539423435639;
   fWeightMatrix1to2[2][6] = -0.836542706413332;
   fWeightMatrix1to2[3][6] = -4.92922383320974;
   fWeightMatrix1to2[4][6] = 2.77453587937561;
   fWeightMatrix1to2[5][6] = -1.99199780777376;
   fWeightMatrix1to2[6][6] = 0.383096132091137;
   fWeightMatrix1to2[7][6] = -2.65816444559002;
   fWeightMatrix1to2[8][6] = 1.58897325964235;
   fWeightMatrix1to2[9][6] = 1.08818411413908;
   fWeightMatrix1to2[10][6] = 1.65278870132213;
   fWeightMatrix1to2[0][7] = 1.49100301204354;
   fWeightMatrix1to2[1][7] = -2.71642024605312;
   fWeightMatrix1to2[2][7] = 3.77609017534389;
   fWeightMatrix1to2[3][7] = -3.85782205752384;
   fWeightMatrix1to2[4][7] = -2.53688203114763;
   fWeightMatrix1to2[5][7] = -1.61385503318865;
   fWeightMatrix1to2[6][7] = 3.24396754604715;
   fWeightMatrix1to2[7][7] = 3.06879577780623;
   fWeightMatrix1to2[8][7] = 2.33331308486558;
   fWeightMatrix1to2[9][7] = -4.78808090865976;
   fWeightMatrix1to2[10][7] = -5.12759928737622;
   fWeightMatrix1to2[0][8] = 1.93171221154999;
   fWeightMatrix1to2[1][8] = -5.08914142208579;
   fWeightMatrix1to2[2][8] = -4.00011503536649;
   fWeightMatrix1to2[3][8] = -1.1626840256192;
   fWeightMatrix1to2[4][8] = 0.464668438721174;
   fWeightMatrix1to2[5][8] = 2.80529092989139;
   fWeightMatrix1to2[6][8] = -2.4956280924973;
   fWeightMatrix1to2[7][8] = -0.757984343544928;
   fWeightMatrix1to2[8][8] = -2.1647224197891;
   fWeightMatrix1to2[9][8] = -0.639660444616096;
   fWeightMatrix1to2[10][8] = 5.01844056623472;
   fWeightMatrix1to2[0][9] = 2.11035437454467;
   fWeightMatrix1to2[1][9] = -2.60702952052859;
   fWeightMatrix1to2[2][9] = -4.75622229366433;
   fWeightMatrix1to2[3][9] = -1.46077687469812;
   fWeightMatrix1to2[4][9] = 2.0757640899571;
   fWeightMatrix1to2[5][9] = 1.66024343941374;
   fWeightMatrix1to2[6][9] = -0.0503252387452774;
   fWeightMatrix1to2[7][9] = -1.71050494503211;
   fWeightMatrix1to2[8][9] = -8.96572819340802;
   fWeightMatrix1to2[9][9] = 1.53703275570017;
   fWeightMatrix1to2[10][9] = 2.7072943031811;
   fWeightMatrix1to2[0][10] = -6.79778253014684;
   fWeightMatrix1to2[1][10] = 4.93639650937715;
   fWeightMatrix1to2[2][10] = -0.450355673790157;
   fWeightMatrix1to2[3][10] = -1.24672172887807;
   fWeightMatrix1to2[4][10] = 4.66940026678517;
   fWeightMatrix1to2[5][10] = -1.85203994252963;
   fWeightMatrix1to2[6][10] = -5.26595449903902;
   fWeightMatrix1to2[7][10] = 0.475755509128204;
   fWeightMatrix1to2[8][10] = 0.0156258864758812;
   fWeightMatrix1to2[9][10] = 1.68503393659785;
   fWeightMatrix1to2[10][10] = 0.758174867596613;
   fWeightMatrix1to2[0][11] = -2.56831367674432;
   fWeightMatrix1to2[1][11] = 7.0016032259691;
   fWeightMatrix1to2[2][11] = 0.524970889197485;
   fWeightMatrix1to2[3][11] = 2.01973876521105;
   fWeightMatrix1to2[4][11] = -0.627535029452896;
   fWeightMatrix1to2[5][11] = 2.25824238264563;
   fWeightMatrix1to2[6][11] = -0.151444937264592;
   fWeightMatrix1to2[7][11] = -0.330054320408177;
   fWeightMatrix1to2[8][11] = -3.00906043851428;
   fWeightMatrix1to2[9][11] = -0.33787784578537;
   fWeightMatrix1to2[10][11] = -0.615956893042651;
   fWeightMatrix1to2[0][12] = -6.04552610507607;
   fWeightMatrix1to2[1][12] = 0.439957098434917;
   fWeightMatrix1to2[2][12] = -5.50469845630545;
   fWeightMatrix1to2[3][12] = -1.55714995227947;
   fWeightMatrix1to2[4][12] = -4.04798583903454;
   fWeightMatrix1to2[5][12] = 6.4702966711079;
   fWeightMatrix1to2[6][12] = -0.101125250511878;
   fWeightMatrix1to2[7][12] = -1.70108837292844;
   fWeightMatrix1to2[8][12] = -10.3550602397747;
   fWeightMatrix1to2[9][12] = 1.64012473654201;
   fWeightMatrix1to2[10][12] = 2.59322397126905;
   fWeightMatrix1to2[0][13] = -4.70072526061815;
   fWeightMatrix1to2[1][13] = -2.26861960985642;
   fWeightMatrix1to2[2][13] = -2.11997251504831;
   fWeightMatrix1to2[3][13] = -1.90858695935917;
   fWeightMatrix1to2[4][13] = -0.517460930235263;
   fWeightMatrix1to2[5][13] = 0.303106704623906;
   fWeightMatrix1to2[6][13] = 5.53694370133924;
   fWeightMatrix1to2[7][13] = -0.252878536948995;
   fWeightMatrix1to2[8][13] = -8.4736302400289;
   fWeightMatrix1to2[9][13] = -0.155295624161366;
   fWeightMatrix1to2[10][13] = -1.69524736450068;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -2.26215224330419;
   fWeightMatrix2to3[0][1] = 4.88269608840315;
   fWeightMatrix2to3[0][2] = 2.05979588275311;
   fWeightMatrix2to3[0][3] = -4.68889864335565;
   fWeightMatrix2to3[0][4] = 4.16440614324793;
   fWeightMatrix2to3[0][5] = -2.69802157371797;
   fWeightMatrix2to3[0][6] = 2.24231124422252;
   fWeightMatrix2to3[0][7] = -5.65439255837139;
   fWeightMatrix2to3[0][8] = 9.34797991432031;
   fWeightMatrix2to3[0][9] = -3.15319443932369;
   fWeightMatrix2to3[0][10] = -1.99485053549228;
   fWeightMatrix2to3[0][11] = -1.18081279309096;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 6;
   fMax_1[0][0] = 42;
   fMin_1[1][0] = 5;
   fMax_1[1][0] = 163;
   fMin_1[2][0] = 5;
   fMax_1[2][0] = 163;
   fMin_1[0][1] = 9;
   fMax_1[0][1] = 68;
   fMin_1[1][1] = 7;
   fMax_1[1][1] = 968;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 968;
   fMin_1[0][2] = 0.450192004442;
   fMax_1[0][2] = 6.7804813385;
   fMin_1[1][2] = 0.332703500986;
   fMax_1[1][2] = 7.23214197159;
   fMin_1[2][2] = 0.332703500986;
   fMax_1[2][2] = 7.23214197159;
   fMin_1[0][3] = -0.166028410196;
   fMax_1[0][3] = 0.921318888664;
   fMin_1[1][3] = -0.199142292142;
   fMax_1[1][3] = 0.999812364578;
   fMin_1[2][3] = -0.199142292142;
   fMax_1[2][3] = 0.999812364578;
   fMin_1[0][4] = -0.155793592334;
   fMax_1[0][4] = 0.540582299232;
   fMin_1[1][4] = -0.186490550637;
   fMax_1[1][4] = 0.997185647488;
   fMin_1[2][4] = -0.186490550637;
   fMax_1[2][4] = 0.997185647488;
   fMin_1[0][5] = 22.3051242828;
   fMax_1[0][5] = 83.2361297607;
   fMin_1[1][5] = 1.25850713253;
   fMax_1[1][5] = 89.9220733643;
   fMin_1[2][5] = 1.25850713253;
   fMax_1[2][5] = 89.9220733643;
   fMin_1[0][6] = -277.679992676;
   fMax_1[0][6] = 180.833938599;
   fMin_1[1][6] = -329.565704346;
   fMax_1[1][6] = 361.686950684;
   fMin_1[2][6] = -329.565704346;
   fMax_1[2][6] = 361.686950684;
   fMin_1[0][7] = 3.15807723999;
   fMax_1[0][7] = 32.6282691956;
   fMin_1[1][7] = 0.135172307491;
   fMax_1[1][7] = 44.5247306824;
   fMin_1[2][7] = 0.135172307491;
   fMax_1[2][7] = 44.5247306824;
   fMin_1[0][8] = 12.6808652878;
   fMax_1[0][8] = 90.9071502686;
   fMin_1[1][8] = 0.698130011559;
   fMax_1[1][8] = 93.416595459;
   fMin_1[2][8] = 0.698130011559;
   fMax_1[2][8] = 93.416595459;
   fMin_1[0][9] = 2.27168273926;
   fMax_1[0][9] = 71.5005950928;
   fMin_1[1][9] = 0.131463989615;
   fMax_1[1][9] = 86.5177764893;
   fMin_1[2][9] = 0.131463989615;
   fMax_1[2][9] = 86.5177764893;
   fMin_1[0][10] = 0.00048828125;
   fMax_1[0][10] = 1676.78369141;
   fMin_1[1][10] = 0.00048828125;
   fMax_1[1][10] = 1677.82714844;
   fMin_1[2][10] = 0.00048828125;
   fMax_1[2][10] = 1677.82714844;
   fMin_1[0][11] = 30.6892032623;
   fMax_1[0][11] = 4859.58935547;
   fMin_1[1][11] = 23.5629196167;
   fMax_1[1][11] = 4943.76708984;
   fMin_1[2][11] = 23.5629196167;
   fMax_1[2][11] = 4943.76708984;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
