// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/38       [336422]
Creator        : han
Date           : Fri Apr 29 08:50:17 2022
Host           : Linux rz5950x.km.icrr.u-tokyo.ac.jp 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /disk1/disk02/calib3/usr/han/mc/thermal_train
Training events: 9684078
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N+1,N-1" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
NHits                         NHits                         NHits                         NHits                                                           'F'    [4,619]
N200                          N200                          N200                          N200                                                            'F'    [7,1721]
TRMS                          TRMS                          TRMS                          TRMS                                                            'F'    [0.13161996007,7.07395029068]
Beta1                         Beta1                         Beta1                         Beta1                                                           'F'    [-0.30522954464,0.999846637249]
Beta5                         Beta5                         Beta5                         Beta5                                                           'F'    [-0.230799347162,0.997701823711]
OpeningAngleMean              OpeningAngleMean              OpeningAngleMean              OpeningAngleMean                                                'F'    [1.00614476204,89.1572341919]
OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew              OpeningAngleSkew                                                'F'    [-328.751739502,354.241363525]
OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev             OpeningAngleStdev                                               'F'    [0.0839482694864,45.7636070251]
MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean              MeanDirAngleMean                                                'F'    [0.602783739567,93.8956985474]
MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS               MeanDirAngleRMS                                                 'F'    [0.130889728665,87.4943618774]
DWall                         DWall                         DWall                         DWall                                                           'F'    [3.28723144531,1690]
DWallMeanDir                  DWallMeanDir                  DWallMeanDir                  DWallMeanDir                                                    'F'    [11.4885377884,4940.76806641]
NSpec 1
Label                         Label                         Label                         I                                                               'F'    [0,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NHits", "N200", "TRMS", "Beta1", "Beta5", "OpeningAngleMean", "OpeningAngleSkew", "OpeningAngleStdev", "MeanDirAngleMean", "MeanDirAngleRMS", "DWall", "DWallMeanDir" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[14][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 9.47651662114751;
   fWeightMatrix0to1[1][0] = 54.5619585608237;
   fWeightMatrix0to1[2][0] = 11.1294736329115;
   fWeightMatrix0to1[3][0] = 15.4721234664989;
   fWeightMatrix0to1[4][0] = -23.9091877431582;
   fWeightMatrix0to1[5][0] = -30.304710677527;
   fWeightMatrix0to1[6][0] = -29.7677522053868;
   fWeightMatrix0to1[7][0] = 74.3536570704462;
   fWeightMatrix0to1[8][0] = -13.1140665383768;
   fWeightMatrix0to1[9][0] = -34.9965146006148;
   fWeightMatrix0to1[10][0] = -21.9436785247222;
   fWeightMatrix0to1[11][0] = 40.114112381015;
   fWeightMatrix0to1[12][0] = -15.793819644549;
   fWeightMatrix0to1[0][1] = -3.59538332615808;
   fWeightMatrix0to1[1][1] = -25.3194219501668;
   fWeightMatrix0to1[2][1] = -21.3205949184508;
   fWeightMatrix0to1[3][1] = 6.45795542959589;
   fWeightMatrix0to1[4][1] = 35.8040274296581;
   fWeightMatrix0to1[5][1] = 14.3086555463887;
   fWeightMatrix0to1[6][1] = 16.8030777311621;
   fWeightMatrix0to1[7][1] = 0.451746331352392;
   fWeightMatrix0to1[8][1] = 6.01557025203642;
   fWeightMatrix0to1[9][1] = 36.5043065387561;
   fWeightMatrix0to1[10][1] = 5.58528230105382;
   fWeightMatrix0to1[11][1] = 7.4926812212717;
   fWeightMatrix0to1[12][1] = -9.64486599119821;
   fWeightMatrix0to1[0][2] = -1.0926353960922;
   fWeightMatrix0to1[1][2] = -0.984783655682327;
   fWeightMatrix0to1[2][2] = -1.59789849397685;
   fWeightMatrix0to1[3][2] = -0.356900971525088;
   fWeightMatrix0to1[4][2] = 0.835484703732002;
   fWeightMatrix0to1[5][2] = 1.07460249144528;
   fWeightMatrix0to1[6][2] = -1.50230010354118;
   fWeightMatrix0to1[7][2] = -0.47368912715406;
   fWeightMatrix0to1[8][2] = 0.218031809747219;
   fWeightMatrix0to1[9][2] = 0.210127791081375;
   fWeightMatrix0to1[10][2] = 0.499564230123743;
   fWeightMatrix0to1[11][2] = -0.143338585003752;
   fWeightMatrix0to1[12][2] = -1.75122702835397;
   fWeightMatrix0to1[0][3] = 8.37619255191915;
   fWeightMatrix0to1[1][3] = 3.30691330734484;
   fWeightMatrix0to1[2][3] = -5.12446815620151;
   fWeightMatrix0to1[3][3] = 7.4601196142371;
   fWeightMatrix0to1[4][3] = 0.471515897947878;
   fWeightMatrix0to1[5][3] = -0.282542239902234;
   fWeightMatrix0to1[6][3] = 5.36301000699341;
   fWeightMatrix0to1[7][3] = -1.32697051932623;
   fWeightMatrix0to1[8][3] = -1.11732826123119;
   fWeightMatrix0to1[9][3] = 0.00906023119648865;
   fWeightMatrix0to1[10][3] = -17.4252860064279;
   fWeightMatrix0to1[11][3] = 0.509390693174729;
   fWeightMatrix0to1[12][3] = -3.8508028553983;
   fWeightMatrix0to1[0][4] = 0.895616041408263;
   fWeightMatrix0to1[1][4] = -1.62205440072771;
   fWeightMatrix0to1[2][4] = 1.65087560320021;
   fWeightMatrix0to1[3][4] = -1.17628195612211;
   fWeightMatrix0to1[4][4] = -0.172148629345708;
   fWeightMatrix0to1[5][4] = -0.727886476037722;
   fWeightMatrix0to1[6][4] = 3.29981370059861;
   fWeightMatrix0to1[7][4] = -0.258631459419075;
   fWeightMatrix0to1[8][4] = -0.232545923686155;
   fWeightMatrix0to1[9][4] = 0.34195856051319;
   fWeightMatrix0to1[10][4] = -0.121412168709347;
   fWeightMatrix0to1[11][4] = 1.15578921732508;
   fWeightMatrix0to1[12][4] = 0.947207783744792;
   fWeightMatrix0to1[0][5] = 4.25512442257188;
   fWeightMatrix0to1[1][5] = -2.08307546873768;
   fWeightMatrix0to1[2][5] = -9.12873319099422;
   fWeightMatrix0to1[3][5] = 4.1018932004661;
   fWeightMatrix0to1[4][5] = -6.08949190821581;
   fWeightMatrix0to1[5][5] = 3.66524923899057;
   fWeightMatrix0to1[6][5] = 0.410173334580992;
   fWeightMatrix0to1[7][5] = 1.52372265019339;
   fWeightMatrix0to1[8][5] = -0.414491380568196;
   fWeightMatrix0to1[9][5] = 0.699011030363534;
   fWeightMatrix0to1[10][5] = -8.06536236387428;
   fWeightMatrix0to1[11][5] = -2.51308784638987;
   fWeightMatrix0to1[12][5] = -6.74404185012299;
   fWeightMatrix0to1[0][6] = 1.48064276992452;
   fWeightMatrix0to1[1][6] = 3.53058237918177;
   fWeightMatrix0to1[2][6] = 2.58983614668909;
   fWeightMatrix0to1[3][6] = -1.27779254931854;
   fWeightMatrix0to1[4][6] = -0.786021526173089;
   fWeightMatrix0to1[5][6] = -1.71043477708167;
   fWeightMatrix0to1[6][6] = -1.39844958994257;
   fWeightMatrix0to1[7][6] = 1.48781850780418;
   fWeightMatrix0to1[8][6] = -3.70379778600862;
   fWeightMatrix0to1[9][6] = -0.672344303723496;
   fWeightMatrix0to1[10][6] = -4.89369894150381;
   fWeightMatrix0to1[11][6] = -3.65394243575596;
   fWeightMatrix0to1[12][6] = 2.17973607338315;
   fWeightMatrix0to1[0][7] = 3.90199477249682;
   fWeightMatrix0to1[1][7] = 0.0296334015914752;
   fWeightMatrix0to1[2][7] = 3.46063202219491;
   fWeightMatrix0to1[3][7] = -0.781880108967418;
   fWeightMatrix0to1[4][7] = 4.25237677160826;
   fWeightMatrix0to1[5][7] = -1.00211792062114;
   fWeightMatrix0to1[6][7] = 1.50744579553106;
   fWeightMatrix0to1[7][7] = 1.3416216304918;
   fWeightMatrix0to1[8][7] = -0.926790796347754;
   fWeightMatrix0to1[9][7] = -0.589413562322803;
   fWeightMatrix0to1[10][7] = 0.855684809595878;
   fWeightMatrix0to1[11][7] = -0.281452424157267;
   fWeightMatrix0to1[12][7] = 1.67843178757741;
   fWeightMatrix0to1[0][8] = 2.36994166573135;
   fWeightMatrix0to1[1][8] = 6.32103685004793;
   fWeightMatrix0to1[2][8] = 2.40779127682176;
   fWeightMatrix0to1[3][8] = 6.7156056148203;
   fWeightMatrix0to1[4][8] = 2.45564810072845;
   fWeightMatrix0to1[5][8] = -2.31032074059456;
   fWeightMatrix0to1[6][8] = 4.71451045217435;
   fWeightMatrix0to1[7][8] = 0.00756392990943125;
   fWeightMatrix0to1[8][8] = 3.13519213350581;
   fWeightMatrix0to1[9][8] = 0.931260951925698;
   fWeightMatrix0to1[10][8] = -21.6086443624096;
   fWeightMatrix0to1[11][8] = -0.204727463179684;
   fWeightMatrix0to1[12][8] = -0.271769341931972;
   fWeightMatrix0to1[0][9] = 0.802007776973654;
   fWeightMatrix0to1[1][9] = 1.04884684525156;
   fWeightMatrix0to1[2][9] = 0.718778468266352;
   fWeightMatrix0to1[3][9] = 3.7716528180739;
   fWeightMatrix0to1[4][9] = 0.655649938264107;
   fWeightMatrix0to1[5][9] = -0.893669950560319;
   fWeightMatrix0to1[6][9] = 1.91973286990977;
   fWeightMatrix0to1[7][9] = -0.15101287113548;
   fWeightMatrix0to1[8][9] = -1.06357735789692;
   fWeightMatrix0to1[9][9] = -0.278757961796375;
   fWeightMatrix0to1[10][9] = -6.59644586261913;
   fWeightMatrix0to1[11][9] = -0.323908116270344;
   fWeightMatrix0to1[12][9] = 0.9438205467102;
   fWeightMatrix0to1[0][10] = -0.108357907801928;
   fWeightMatrix0to1[1][10] = 0.491495460533793;
   fWeightMatrix0to1[2][10] = 6.06140302619746;
   fWeightMatrix0to1[3][10] = -16.886335295247;
   fWeightMatrix0to1[4][10] = 0.104635679009334;
   fWeightMatrix0to1[5][10] = 5.02576719598901;
   fWeightMatrix0to1[6][10] = 1.27696886294131;
   fWeightMatrix0to1[7][10] = -0.197481535829913;
   fWeightMatrix0to1[8][10] = -1.21986795376978;
   fWeightMatrix0to1[9][10] = 0.7878657544836;
   fWeightMatrix0to1[10][10] = -0.0016043122087511;
   fWeightMatrix0to1[11][10] = -0.283069446597914;
   fWeightMatrix0to1[12][10] = -3.79426412358332;
   fWeightMatrix0to1[0][11] = -0.49962751879617;
   fWeightMatrix0to1[1][11] = -1.4107234279061;
   fWeightMatrix0to1[2][11] = -0.610772290262387;
   fWeightMatrix0to1[3][11] = -0.0481313170105302;
   fWeightMatrix0to1[4][11] = -0.426889206118392;
   fWeightMatrix0to1[5][11] = -0.218346145595653;
   fWeightMatrix0to1[6][11] = -0.867515469703706;
   fWeightMatrix0to1[7][11] = 0.652901708923096;
   fWeightMatrix0to1[8][11] = 1.89475394287954;
   fWeightMatrix0to1[9][11] = 3.14253024643152;
   fWeightMatrix0to1[10][11] = 0.27263956234668;
   fWeightMatrix0to1[11][11] = -1.0160471479169;
   fWeightMatrix0to1[12][11] = 0.832705743836791;
   fWeightMatrix0to1[0][12] = 9.64913210678652;
   fWeightMatrix0to1[1][12] = 29.4218480705212;
   fWeightMatrix0to1[2][12] = -3.73211879532393;
   fWeightMatrix0to1[3][12] = 2.97608542052297;
   fWeightMatrix0to1[4][12] = 11.5636087730541;
   fWeightMatrix0to1[5][12] = -14.3052624291682;
   fWeightMatrix0to1[6][12] = -11.4796816193268;
   fWeightMatrix0to1[7][12] = 70.2091653429817;
   fWeightMatrix0to1[8][12] = -7.95170715925046;
   fWeightMatrix0to1[9][12] = 3.18435861642683;
   fWeightMatrix0to1[10][12] = -19.5971105442042;
   fWeightMatrix0to1[11][12] = 47.2546712832385;
   fWeightMatrix0to1[12][12] = -25.6903956534549;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.486814012682193;
   fWeightMatrix1to2[1][0] = 1.6966470660667;
   fWeightMatrix1to2[2][0] = 2.57398516889078;
   fWeightMatrix1to2[3][0] = -3.42356579566743;
   fWeightMatrix1to2[4][0] = 1.88025103937802;
   fWeightMatrix1to2[5][0] = 3.6716713861754;
   fWeightMatrix1to2[6][0] = -2.2331938513679;
   fWeightMatrix1to2[7][0] = -1.6278499971819;
   fWeightMatrix1to2[8][0] = 0.504101920726054;
   fWeightMatrix1to2[9][0] = 2.25444467199886;
   fWeightMatrix1to2[10][0] = -4.27471989602948;
   fWeightMatrix1to2[0][1] = -2.23623933262463;
   fWeightMatrix1to2[1][1] = 4.92094630839939;
   fWeightMatrix1to2[2][1] = 1.72237447632829;
   fWeightMatrix1to2[3][1] = -0.243354370160862;
   fWeightMatrix1to2[4][1] = 5.8733619847285;
   fWeightMatrix1to2[5][1] = -1.14683070625894;
   fWeightMatrix1to2[6][1] = -0.82374649056844;
   fWeightMatrix1to2[7][1] = 1.87668776944104;
   fWeightMatrix1to2[8][1] = 2.87878785734122;
   fWeightMatrix1to2[9][1] = -2.58152693242991;
   fWeightMatrix1to2[10][1] = -4.5678654979178;
   fWeightMatrix1to2[0][2] = 2.11556705968721;
   fWeightMatrix1to2[1][2] = 0.00147374510250238;
   fWeightMatrix1to2[2][2] = -1.6568556878651;
   fWeightMatrix1to2[3][2] = -0.238081284326702;
   fWeightMatrix1to2[4][2] = 4.32255428109413;
   fWeightMatrix1to2[5][2] = -6.86034294275171;
   fWeightMatrix1to2[6][2] = 6.2646381959276;
   fWeightMatrix1to2[7][2] = 0.371815359289738;
   fWeightMatrix1to2[8][2] = 1.50898037590834;
   fWeightMatrix1to2[9][2] = -2.45804902996714;
   fWeightMatrix1to2[10][2] = 0.274763121874987;
   fWeightMatrix1to2[0][3] = -3.64824903093549;
   fWeightMatrix1to2[1][3] = -0.735676698418053;
   fWeightMatrix1to2[2][3] = 2.10875088072856;
   fWeightMatrix1to2[3][3] = 2.66956904663436;
   fWeightMatrix1to2[4][3] = 0.91918707701729;
   fWeightMatrix1to2[5][3] = -6.88330980455125;
   fWeightMatrix1to2[6][3] = 0.208194680029297;
   fWeightMatrix1to2[7][3] = 3.01597074794294;
   fWeightMatrix1to2[8][3] = 1.92453625566077;
   fWeightMatrix1to2[9][3] = -0.475166762510384;
   fWeightMatrix1to2[10][3] = -1.73911432508891;
   fWeightMatrix1to2[0][4] = -6.18169207035236;
   fWeightMatrix1to2[1][4] = -4.60516871451639;
   fWeightMatrix1to2[2][4] = -7.13145766985497;
   fWeightMatrix1to2[3][4] = -0.23730772799396;
   fWeightMatrix1to2[4][4] = 0.36530905349376;
   fWeightMatrix1to2[5][4] = 8.92523882100492;
   fWeightMatrix1to2[6][4] = -8.45737185249311;
   fWeightMatrix1to2[7][4] = -0.973620798487604;
   fWeightMatrix1to2[8][4] = -2.06760644479376;
   fWeightMatrix1to2[9][4] = 5.41120137517638;
   fWeightMatrix1to2[10][4] = 11.1537568149107;
   fWeightMatrix1to2[0][5] = 0.112841795448729;
   fWeightMatrix1to2[1][5] = -9.42109804874015;
   fWeightMatrix1to2[2][5] = -1.49337216003382;
   fWeightMatrix1to2[3][5] = -4.67609170602343;
   fWeightMatrix1to2[4][5] = -0.99594932664525;
   fWeightMatrix1to2[5][5] = -0.0339260952327602;
   fWeightMatrix1to2[6][5] = -3.56145058410129;
   fWeightMatrix1to2[7][5] = -2.20044042827563;
   fWeightMatrix1to2[8][5] = 1.73006968616293;
   fWeightMatrix1to2[9][5] = 0.251041522589498;
   fWeightMatrix1to2[10][5] = 3.924026668192;
   fWeightMatrix1to2[0][6] = 2.13938272731442;
   fWeightMatrix1to2[1][6] = -3.2047787556205;
   fWeightMatrix1to2[2][6] = -0.191871390144375;
   fWeightMatrix1to2[3][6] = -3.4168829456749;
   fWeightMatrix1to2[4][6] = 0.35292902851381;
   fWeightMatrix1to2[5][6] = 4.44823085287744;
   fWeightMatrix1to2[6][6] = -4.19842660857061;
   fWeightMatrix1to2[7][6] = -2.89953514089718;
   fWeightMatrix1to2[8][6] = -2.18418694594675;
   fWeightMatrix1to2[9][6] = -2.25732129319151;
   fWeightMatrix1to2[10][6] = 6.77590534228308;
   fWeightMatrix1to2[0][7] = -18.1223313299683;
   fWeightMatrix1to2[1][7] = 0.382242698519921;
   fWeightMatrix1to2[2][7] = 3.14187390441528;
   fWeightMatrix1to2[3][7] = -7.99892304136108;
   fWeightMatrix1to2[4][7] = 5.05121918711456;
   fWeightMatrix1to2[5][7] = -0.985287740760785;
   fWeightMatrix1to2[6][7] = 8.49840477262495;
   fWeightMatrix1to2[7][7] = 12.3950370282379;
   fWeightMatrix1to2[8][7] = -1.09637651262041;
   fWeightMatrix1to2[9][7] = -1.95230664188583;
   fWeightMatrix1to2[10][7] = -15.0761657954551;
   fWeightMatrix1to2[0][8] = 0.580439289880638;
   fWeightMatrix1to2[1][8] = 2.00417971726166;
   fWeightMatrix1to2[2][8] = -1.56677464139947;
   fWeightMatrix1to2[3][8] = 1.88583189401026;
   fWeightMatrix1to2[4][8] = -1.08394144554506;
   fWeightMatrix1to2[5][8] = 0.7135102037946;
   fWeightMatrix1to2[6][8] = -2.30361486185613;
   fWeightMatrix1to2[7][8] = -2.15000792568433;
   fWeightMatrix1to2[8][8] = 0.21565780859898;
   fWeightMatrix1to2[9][8] = -0.863766331274794;
   fWeightMatrix1to2[10][8] = 1.33412971416681;
   fWeightMatrix1to2[0][9] = 0.893005424423203;
   fWeightMatrix1to2[1][9] = -3.65114394995605;
   fWeightMatrix1to2[2][9] = -2.81355420554947;
   fWeightMatrix1to2[3][9] = -1.31134496768994;
   fWeightMatrix1to2[4][9] = -0.102093443725155;
   fWeightMatrix1to2[5][9] = -1.93214987136766;
   fWeightMatrix1to2[6][9] = -1.75651185956881;
   fWeightMatrix1to2[7][9] = 6.61770397530708;
   fWeightMatrix1to2[8][9] = 0.516435419418181;
   fWeightMatrix1to2[9][9] = 5.79846092228512;
   fWeightMatrix1to2[10][9] = 1.317355963241;
   fWeightMatrix1to2[0][10] = 3.70326610425819;
   fWeightMatrix1to2[1][10] = -0.365441835513185;
   fWeightMatrix1to2[2][10] = 1.1578848740893;
   fWeightMatrix1to2[3][10] = -2.31492199184179;
   fWeightMatrix1to2[4][10] = -0.525720439947068;
   fWeightMatrix1to2[5][10] = -0.951688286327898;
   fWeightMatrix1to2[6][10] = 1.22447611854938;
   fWeightMatrix1to2[7][10] = 0.0333024179113254;
   fWeightMatrix1to2[8][10] = 1.66761463175493;
   fWeightMatrix1to2[9][10] = -3.00608130590768;
   fWeightMatrix1to2[10][10] = 2.03604480750915;
   fWeightMatrix1to2[0][11] = -9.61174644249782;
   fWeightMatrix1to2[1][11] = -1.24254804866588;
   fWeightMatrix1to2[2][11] = -8.12182726317251;
   fWeightMatrix1to2[3][11] = -2.69844937594072;
   fWeightMatrix1to2[4][11] = 1.2549596771848;
   fWeightMatrix1to2[5][11] = 2.13789186243345;
   fWeightMatrix1to2[6][11] = 0.827343061891545;
   fWeightMatrix1to2[7][11] = 3.80135394972917;
   fWeightMatrix1to2[8][11] = -8.88534724811155;
   fWeightMatrix1to2[9][11] = -2.38568864542651;
   fWeightMatrix1to2[10][11] = -5.24432206926619;
   fWeightMatrix1to2[0][12] = 1.41073333421063;
   fWeightMatrix1to2[1][12] = 1.7620418754365;
   fWeightMatrix1to2[2][12] = -0.734281993599998;
   fWeightMatrix1to2[3][12] = 1.8570534074588;
   fWeightMatrix1to2[4][12] = -4.42505826052884;
   fWeightMatrix1to2[5][12] = -1.74992763695233;
   fWeightMatrix1to2[6][12] = -3.74486379982083;
   fWeightMatrix1to2[7][12] = -1.52134809817551;
   fWeightMatrix1to2[8][12] = 0.123990867635292;
   fWeightMatrix1to2[9][12] = 1.16682198250579;
   fWeightMatrix1to2[10][12] = 2.10334686021068;
   fWeightMatrix1to2[0][13] = 1.62897408416919;
   fWeightMatrix1to2[1][13] = -4.94722659809315;
   fWeightMatrix1to2[2][13] = 7.86476897712432;
   fWeightMatrix1to2[3][13] = 1.49373174973669;
   fWeightMatrix1to2[4][13] = -11.1944415145513;
   fWeightMatrix1to2[5][13] = -2.96560302561488;
   fWeightMatrix1to2[6][13] = 4.25936939954238;
   fWeightMatrix1to2[7][13] = -0.585444202967563;
   fWeightMatrix1to2[8][13] = -3.85297750499141;
   fWeightMatrix1to2[9][13] = -4.21067042731274;
   fWeightMatrix1to2[10][13] = 3.25584806160147;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -4.49895514997797;
   fWeightMatrix2to3[0][1] = -7.05171588567008;
   fWeightMatrix2to3[0][2] = 6.59150059342035;
   fWeightMatrix2to3[0][3] = 5.21148439316706;
   fWeightMatrix2to3[0][4] = 8.21089811757041;
   fWeightMatrix2to3[0][5] = -2.06362184236729;
   fWeightMatrix2to3[0][6] = 2.87398563529729;
   fWeightMatrix2to3[0][7] = -4.9446577913567;
   fWeightMatrix2to3[0][8] = -3.91153693231233;
   fWeightMatrix2to3[0][9] = -1.6794112575089;
   fWeightMatrix2to3[0][10] = -2.17727743712468;
   fWeightMatrix2to3[0][11] = -1.97042485117151;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 62;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 619;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 619;
   fMin_1[0][1] = 8;
   fMax_1[0][1] = 90;
   fMin_1[1][1] = 7;
   fMax_1[1][1] = 1721;
   fMin_1[2][1] = 7;
   fMax_1[2][1] = 1721;
   fMin_1[0][2] = 0.335373044014;
   fMax_1[0][2] = 6.2951798439;
   fMin_1[1][2] = 0.13161996007;
   fMax_1[1][2] = 7.07395029068;
   fMin_1[2][2] = 0.13161996007;
   fMax_1[2][2] = 7.07395029068;
   fMin_1[0][3] = -0.236642047763;
   fMax_1[0][3] = 0.992675423622;
   fMin_1[1][3] = -0.30522954464;
   fMax_1[1][3] = 0.999846637249;
   fMin_1[2][3] = -0.30522954464;
   fMax_1[2][3] = 0.999846637249;
   fMin_1[0][4] = -0.183984965086;
   fMax_1[0][4] = 0.895310342312;
   fMin_1[1][4] = -0.230799347162;
   fMax_1[1][4] = 0.997701823711;
   fMin_1[2][4] = -0.230799347162;
   fMax_1[2][4] = 0.997701823711;
   fMin_1[0][5] = 9.17044830322;
   fMax_1[0][5] = 85.4750289917;
   fMin_1[1][5] = 1.00614476204;
   fMax_1[1][5] = 89.1572341919;
   fMin_1[2][5] = 1.00614476204;
   fMax_1[2][5] = 89.1572341919;
   fMin_1[0][6] = -220.659240723;
   fMax_1[0][6] = 320.099731445;
   fMin_1[1][6] = -328.751739502;
   fMax_1[1][6] = 354.241363525;
   fMin_1[2][6] = -328.751739502;
   fMax_1[2][6] = 354.241363525;
   fMin_1[0][7] = 2.05326771736;
   fMax_1[0][7] = 35.2620544434;
   fMin_1[1][7] = 0.0839482694864;
   fMax_1[1][7] = 45.7636070251;
   fMin_1[2][7] = 0.0839482694864;
   fMax_1[2][7] = 45.7636070251;
   fMin_1[0][8] = 3.97685885429;
   fMax_1[0][8] = 89.9764633179;
   fMin_1[1][8] = 0.602783739567;
   fMax_1[1][8] = 93.8956985474;
   fMin_1[2][8] = 0.602783739567;
   fMax_1[2][8] = 93.8956985474;
   fMin_1[0][9] = 1.52264273167;
   fMax_1[0][9] = 71.1907958984;
   fMin_1[1][9] = 0.130889728665;
   fMax_1[1][9] = 87.4943618774;
   fMin_1[2][9] = 0.130889728665;
   fMax_1[2][9] = 87.4943618774;
   fMin_1[0][10] = 3.28723144531;
   fMax_1[0][10] = 1690;
   fMin_1[1][10] = 3.28723144531;
   fMax_1[1][10] = 1690;
   fMin_1[2][10] = 3.28723144531;
   fMax_1[2][10] = 1690;
   fMin_1[0][11] = 11.4885377884;
   fMax_1[0][11] = 4881.84570312;
   fMin_1[1][11] = 14.9507255554;
   fMax_1[1][11] = 4940.76806641;
   fMin_1[2][11] = 11.4885377884;
   fMax_1[2][11] = 4940.76806641;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
